### ISSUE TITLE
Published unpackaged apps do not run

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#1677] opened 2021-10-29 08:33 UTC
Published app does not run in Self-Contained mode and framework-Dependent

**Steps to reproduce the bug**

1. Create a new UnPackaged winui 3 app (preview 3)
2. Publish app (Self-Contained or framework-dependent)
3. run published app

**Internal bug (for MS employees)**: https://microsoft.visualstudio.com/OS/_queries/edit/36900034

**Expected behavior**
app should be run

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.WindowsAppSDK 1.0.0-preview3

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| Windows 11 (22000)             | Yes                         |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by andrewleader** [comment] 2021-11-01 21:47
Hi @ghost1372, thanks for reporting this, we're looking into it!

**Comment by andrewleader** [comment] 2021-11-03 17:58
Hi @ghost1372, just an update, we identified the root cause of the .NET Publish not working with WinAppSDK and are working on a fix.

**Comment by ghost1372** [comment] 2021-11-03 18:25
excellent, Can we get it before 1.0 GA?

**Comment by andrewleader** [comment] 2021-11-03 18:39
I think it'll be more likely we fix this in a 1.0.x update soon after GA, but we don't know yet when the fix will come since we're working on the fix right now.

**Comment by wjk** [comment] 2021-11-06 00:45
@ghost1372 Details on what the bug actually _is_, please? Remember that we don’t all work for Microsoft. MS-internal bug links are not useful.

**Comment by riverar** [comment] 2021-11-06 04:03
@wjk Andrew added the internal bug for other Microsoft folks. The repro steps make it pretty clear that .NET publish scenario is busted. Not sure if additional details here would be beneficial or be a good use of their time.

**Comment by wjk** [comment] 2021-11-06 07:22
@riverar My apologies. I thought it was there from the beginning. That’s perfectly all right. Sorry to bother you @ghost1372.

**Comment by andrewleader** [comment] 2021-11-08 16:43
Good news, we're actually going to fix this in time for the 1.0 GA!

The root cause was that the app's `resources.pri`, which holds all of its assets (e.g. images, XBF, localized strings) is not being binplaced to the publish directory (PRI files are not one of the standard file types that .NET Publish knows about). This causes the published app to crash on startup when it can't find necessary resources.

I think single-file publish will be broken in 1.0 GA though, we were testing that and noticed some additional problems there (where there still were some files that weren't combined into the single EXE).

**Comment by andrewleader** [comment] 2021-11-08 16:44
Oh and I'm closing this issue since the fix has been checked into 1.0 GA.

**Closed by andrewleader** 2021-11-08 16:44 UTC
Labels: bug, area-Developer tools, v1.0.0-preview3

**Comment by ghost1372** [comment] 2021-11-08 18:39
Awesome, thanks🙏🙏
