### ISSUE TITLE
AppNotificationManager.Default.Register() throws E_FAIL

### ISSUE THREAD

**Issue by dkbennett** [microsoft/WindowsAppSDK#3540] opened 2023-03-27 09:27 UTC
### Describe the bug

WinAppSDK version 1.2.230313.1

This is on a C# packaged MSIX application. I am attempting to use the Notifications platform per documentation, and I am unable to make a notification manager because calling AppNotificationManager.Default.Register() throws E_FAIL.

I have all the manifest entries set correctly, and am attempting to get the toast activation to work and stopped cold by this error.

### Steps to reproduce the bug

1) Create desktop MSIX C# console app
2) Add winappsdk
3) Set the appropriate things in the appxmanifest
4) Try to make a notification manager and call AppNotificationManager.Default.Register().

### Expected behavior

Expect not to fail, or if it does, have a _little_ more descriptive error code that might indicate the problem.

### Screenshots
![efail1](https://user-images.githubusercontent.com/18407763/227901958-aba6d500-d80f-40be-b368-f54a6eb1373b.png)
![efail2](https://user-images.githubusercontent.com/18407763/227901986-9d0fa8fd-3eab-4393-92b0-d65b84e669e5.png)

### NuGet package version

Windows App SDK 1.2.5: 1.2.230313.1

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by dkbennett** [comment] 2023-03-27 20:12
With assistance from and huge thanks to @pmpurifoy we identified the issue:  The COM server registration specification for the executable in the AppManifest didn't match the exact case of the actual executable in the package. This didn't cause a failure in the other COM server registrations in the app manifest (which had the same mismatch), but it did for the notifications registration.

Two possible followups for this so it doesn't trip up other folks:

1) The COM server registration for notifications should probably not be case-sensitive on the executable name to be consistent with other COM registrations. It wasn't obvious this was the issue when there are other COM registrations in the package for the same executable. Copy-paste the COM registration from another working one in the manifest and then changing the guid and other values is how this occurred for me.

2) The E_FAIL message should include the message for the error: Msg:[Caller RegistrationProcess is not the same as manifest defined COM Server!] in Visual Studio if possible to more quickly resolve the issue when encountered.

And for anyone else reading this in the future who encountered this issue later - check that your executable name matches the name in the manifest, including case!

I'll leave issue open for WinAppSDK folks to decide if/how they want to address the bug.

**Comment by myokeeh** [comment] 2024-09-09 05:44
I'm getting this "Caller RegistrationProcess is not the same as manifest defined COM Server!" error. I'm converting a UWP to WinUI3 / WindowsAppSDK and trying to send out a notification from a background task. Is there anything below that needs to change? How can I make it work?

`AppNotificationManager.Default.Register();` fails. and `AppNotificationManager.Default.Show(appNotification);` doesn't show the notification.

```
<Extensions>
    <desktop:Extension Category="windows.toastNotificationActivation">
        <desktop:ToastNotificationActivation ToastActivatorCLSID="a220abcb-5132-4166-9ce5-1ccdb57d32a6" />
    </desktop:Extension>

    <com:Extension Category="windows.comServer">
        <com:ComServer>
            <com:ExeServer Executable="APPWTS.exe" Arguments="----AppNotificationActivated:" DisplayName="Toast activator">
                <com:Class Id="a220abcb-5132-4166-9ce5-1ccdb57d32a6" DisplayName="Toast activator"/>
            </com:ExeServer>
        </com:ComServer>
    </com:Extension>
	<Extension Category="windows.backgroundTasks" EntryPoint="APPBackgroundTasks.TokenRefreshBackgroundTask">
		<BackgroundTasks>
			<Task Type="timer"/>
			<Task Type="pushNotification"/>

		</BackgroundTasks>
	</Extension>
</Extensions>
```

```
<Extensions>
	<Extension Category="windows.activatableClass.inProcessServer">
		<InProcessServer>
			<Path>WinRT.Host.dll</Path>
			<ActivatableClass ActivatableClassId="APPBackgroundTasks.TokenRefreshBackgroundTask" ThreadingModel="both" />
		</InProcessServer>
	</Extension>
</Extensions>
```

**Comment by DominikErnst** [comment] 2024-10-08 05:46
Hi. I had a similar error that appeared after I renamed the projects from CTI2 to CTI.

`    public void Initialize()
    {
        AppNotificationManager.Default.NotificationInvoked += OnNotificationInvoked;

        AppNotificationManager.Default.Register();      // Exception Caller RegistrationProcess is not the same as manifest defined COM Server!
    }`

After searching for a while, I found the following entry in the Package.appxmanifest (right-click “open with” XML Editor).

`      <Extensions>
          <desktop:Extension Category="windows.toastNotificationActivation">
              <desktop:ToastNotificationActivation ToastActivatorCLSID="265d0efa-bb57-4da0-8b60-d69b36021559" />
          </desktop:Extension>

          <com:Extension Category="windows.comServer">
              <com:ComServer>
                  <com:ExeServer Executable="CTI2.exe" Arguments="----AppNotificationActivated:" DisplayName="Toast activator">
                      <com:Class Id="265d0efa-bb57-4da0-8b60-d69b36021559" DisplayName="Toast activator"/>
                  </com:ExeServer>
              </com:ComServer>
          </com:Extension>
      </Extensions>`

I changed the name from CTI2.exe to CTI.exe (the new name) and voilar the app is running again.

**Comment by DominikErnst** [comment] 2024-10-08 05:58
Hi. I had a similar error that appeared after I renamed the projects from CTI2 to CTI and CTI2.Core to CTI.Core.

`    public void Initialize()
    {
        AppNotificationManager.Default.NotificationInvoked += OnNotificationInvoked;

        AppNotificationManager.Default.Register();
    }`

After searching for a while, I found the following entry in the Package.appxmanifest (right-click “open with” XML Editor).

`          <com:Extension Category="windows.comServer">
              <com:ComServer>
                  <com:ExeServer Executable="CTI.exe" Arguments="----AppNotificationActivated:" DisplayName="Toast activator">
                      <com:Class Id="265d0efa-bb57-4da0-8b60-d69b36021559" DisplayName="Toast activator"/>
                  </com:ExeServer>
              </com:ComServer>
          </com:Extension>`

I changed the name from CTI2.exe to CTI.exe (the new name) and voilar the app is running again.

(Why is the markup broken here?)

**Comment by LegendaryBlair** [comment] 2024-11-12 03:13
The reporter mentioned that the root cause was the COM server registration for notifications is case sensitive, hence closing the issue.

**Closed by LegendaryBlair** 2024-11-12 03:13 UTC
Labels: area-Notifications
