### ISSUE TITLE
Build error APPX1101 (.NET 6 WinUI 3 and Microsoft.EntityFramework.Tools) 

### ISSUE THREAD

**Issue by BluVeneziano** [microsoft/WindowsAppSDK#1856] opened 2021-11-29 21:58 UTC
### Describe the bug

When building my app, I get this error:

APPX1101
Payload contains two or more files with the same destination path 'App4.deps.json'. Source files: 
C:\Users\bluve\source\repos\App4\App4\obj\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\App4.deps.json
C:\Users\bluve\source\repos\App4\App4\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\App4.deps.json	App4	C:\Users\bluve\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets	1370	

### Steps to reproduce the bug

1. Create a WinUI 3 app.
2. Add Microsoft.EntityFrameworkCore.Tools 6.0.0 from NuGet.
3. Run the app.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

May 2021 Update (19043)

### IDE

Visual Studio 2022

**Comment by andrewleader** [comment] 2021-11-29 22:20
Thanks @BluVeneziano, we're working with the EntityFrameworkCore team to investigate this, we'll update you when we have figured out more!

**Comment by hachadwick** [comment] 2022-01-06 18:42
This is stopping my development in WINUI 3. This has had no forward motion since Nov. of last year. Has there been an update?

**Comment by adixon501** [comment] 2022-01-06 18:42
@andrewleader is there any progress on this bug? I am having the same error on a WinUi 3 WPF app

**Comment by riverar** [comment] 2022-01-06 19:43
To unblock you for now, open your .csproj and make the changes indicated below.

```diff
+ <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.1" />
- <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.1">
-    <PrivateAssets>all</PrivateAssets>
-    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
- </PackageReference>
```

**Comment by hachadwick** [comment] 2022-01-06 19:59
wow, that did the trick. @riverar I sure appreciate the help!

**Comment by scott-moxham** [comment] 2022-01-29 20:59
I'm also having this problem.
However, I added Microsoft.EntityFrameworkCore.Design 6.0.1 instead of Tools from GitHub.

**Comment by kmgallahan** [comment] 2022-03-10 17:25
@andrewleader 

Could you clarify if this issue or the newly created one under WinUI should be used for this problem:

https://github.com/microsoft/microsoft-ui-xaml/issues/6814

EF Core team stated it is a WinUI issue.

https://github.com/dotnet/efcore/issues/27576#issuecomment-1064304575

**Comment by andrewleader** [comment] 2022-03-10 18:04
I no longer work on WinAppSdk, @mikebattista would you be the right person to help with the question above?

**Comment by mikebattista** [comment] 2022-03-10 18:17
I created https://task.ms/38479087 to track this. We'll take a look.

**Comment by kmgallahan** [comment] 2022-03-10 18:25
@mikebattista This issue was supposedly already being tracked internally: 

https://github.com/dotnet/efcore/issues/26973#issuecomment-993885102

https://github.com/dotnet/efcore/issues/27576#issuecomment-1064304575

I was just trying to prevent it from being duplicated in both the WinUI and WindowsAppSDK repos:

https://github.com/microsoft/microsoft-ui-xaml/issues/6814

**Comment by mikebattista** [comment] 2022-03-10 19:17
Confirmed still reproes with latest internal builds.

**Comment by sjb-sjb** [comment] 2022-03-11 13:42
Commenting that while the .csproj lines cited by @riverar also occur in libraries ("Class Library (WinUI 3 in Desktop)" template), the compile error only occurs for the app, not the libraries.

**Comment by Marren85** [comment] 2022-04-16 18:28
Does anything on this turd known as WinUI 3 actually work as it's supposed too? Is it safe to say this shouldn't have been released in the state it's in? 6 months and EF Core still doesn't work, still no designer, figured out today that it can't even detect circular dependency injection which was why my app wouldn't launch, WinUI is the future is it?!? Sticking with WPF

**Comment by DefaultRyan** [comment] 2022-05-16 15:52
I’ve tracked down the task invocations responsible for generating the two differing deps.json files. They are both calls to GenerateDepsFile in C:\Program Files\dotnet\sdk\6.0.203\Sdks\Microsoft.NET.Sdk\targets\..\tools\net472\Microsoft.NET.Build.Tasks.dll.


The first file to be generated is the deps.json under the bin folder. That comes from target GenerateBuildDependencyFile, with this dependency chain:

- [GenerateBuildDependencyFile](https://github.com/dotnet/sdk/blob/ad1ca90ad286288970a4ae1ec77e85848fef5a24/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L179) (Microsoft.NET.sdk.targets; .NET SDK)
- CopyFilesToOutputDirectory (Microsoft.Common.CurrentVersion.targets; VS)
- GenerateProjectPriFile (Microsoft.Build.Msix.Pri.targets; WinAppSDK Nuget)
- PrepareForRun
 

The second file to be generated is the deps.json under the obj folder. That comes from target GeneratePublishDependencyFile, with this dependency chain:

- [GeneratePublishDependencyFile](https://github.com/dotnet/sdk/blob/372756bf905d48b647f45fc3005a8729397b2102/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L957) (Microsoft.NET.Publish.targets; .NET SDK)
- ComputeFilesToPublish (Microsoft.NET.Publish.targets; .NET SDK)
- __GetPublishItems (Microsoft.Build.Msix.Packaging.targets; WinAppSDK Nuget)
- GetPackagingOutputs (Microsoft.Build.Msix.Packaging.targets; WinAppSDK Nuget)
- PrepareMsixPackage

The supplied parameters are *almost* identical. Aside from the output file being different, there are two differences:

- In GenerateBuildDependencyFile, the parameter ResolvedNuGetFiles contains a bunch of dlls that come from EntityFramework-related packages. In GeneratePublishDependencyFile, those files are absent, because this target filters out items that have “CopyToPublishDirectory” set to “False”.
This seems to be related to the EntityFramework package using DevelopmentDependency and the explicit runtime asset used in PackageReference as mentioned by Rafael Rivera in this comment https://github.com/microsoft/WindowsAppSDK/issues/1856#issuecomment-1006882973
- The parameter “IsSingleFile” is not set for GenerateBuildDependencyFile, but it is set and defaults to “False” in GeneratePublishDependencyFile.
 

I suspect it’s mostly the first difference to blame here, based on [this line in the GenerateDepsFile task](https://github.com/dotnet/sdk/blob/372756bf905d48b647f45fc3005a8729397b2102/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L957) that adds ResolvedNuGetFiles to ResolvedRuntimeTargetsFiles.

Handing over further investigation to @evelynwu-msft

**Comment by Ika59** [comment] 2022-05-18 09:51
see workarround: https://github.com/microsoft/WindowsAppSDK/issues/2524#issuecomment-1129733373

**Comment by rxDietel** [comment] 2022-08-22 08:07
Hello, we are trying to migrate a Xamarin App to MAUI.
We don't use entity Framework and are running into the exact same problem of two <App>.deps.json files being generated.
Is there any progress in this matter or a workaround I could use?

**Comment by EricJohnson327** [comment] 2022-08-22 20:04
@rxDietel Fix is coming in 1.2.  For workarounds there are two possibilities: https://github.com/microsoft/WindowsAppSDK/issues/1856#issuecomment-1006882973
https://github.com/microsoft/WindowsAppSDK/issues/2524#issuecomment-1129733373
Please follow up if neither of these work for you.

**Comment by dotMorten** [comment] 2022-08-23 19:40
I'm hitting this over and over today as well with my maui app.

**Comment by EricJohnson327** [comment] 2022-08-24 23:20
Fix is checked in and will ship with 1.2

**Comment by FrankSzendzielarz** [comment] 2022-08-28 15:51
Getting rid of privateassets="all" from the package ref worked for me

**Comment by Scottj1s** [comment] 2022-09-29 19:11
Reopening until @BluVeneziano and other customers can confirm the fix, which will be available in WinAppSDK 1.2 Preview 2.  In the meantime, here is a workaround to drop into your csproj or directory.build.targets:

```
    <Target Name="RemoveCollidingDepsJson" AfterTargets="GetPackagingOutputs" BeforeTargets="_ComputeAppxPackagePayload">
        <!-- If conflicting build and publish deps.json files are present, use only the publish deps.json, 
            and remove the corresponding build deps.json. -->
        <ItemGroup>
            <_PublishDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'PublishItemsOutputGroupOutput'))"
                Condition="'@(PackagingOutputs)'!='' and $([System.String]::Copy(%(FileName)%(Extension)).EndsWith('.deps.json'))" />
            <_BuildDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'GetCopyToOutputDirectoryItemsOutputGroup'))"
                Condition="'@(PackagingOutputs)'!='' and $([System.String]::Copy(%(FileName)%(Extension)).EndsWith('.deps.json'))" />
            <PackagingOutputs Condition="'@(_PublishDepsJson)'!='' and '@(_BuildDepsJson)'!=''" Remove="@(_BuildDepsJson)"/>
        </ItemGroup>
    </Target>

```

**Comment by julianadormon** [comment] 2022-10-10 23:51
@Scottj1s Hi. 
I placed your above code in my Maui csproj file just above the </Project> tag but I still get the same error.

Do I have it in the right spot? Thanks.

**Comment by Scottj1s** [comment] 2022-10-11 15:14
@julianadormon I'd recommend updating to WindowsAppSDK 1.2 Preview 2, which contains this fix.  If that would prevent you from publishing to the store, then you can produce a binlog and examine it with the https://msbuildlog.com/ tool to ensure that the RemoveCollidingDepsJson target above is executing correctly.

**Comment by MikeHillberg** [comment] 2022-10-12 03:04
I'm getting syntax errors on that Target, on the two String.Copy lines. I fixed it by removing the single quote at the front of it (in `Condition="'$([System.String] ...`), and adding single quotes to the Copy call (in `::Copy(%(FileName)%(Extension))`)

```xml
	<Target Name="RemoveCollidingDepsJson" AfterTargets="GetPackagingOutputs" BeforeTargets="_ComputeAppxPackagePayload">
		<!-- If conflicting build and publish deps.json files are present, use only the publish deps.json, 
            and remove the corresponding build deps.json. -->
		<ItemGroup Condition="'@(PackagingOutputs)'!=''" >
			<_PublishDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'PublishItemsOutputGroupOutput'))"
                Condition="$([System.String]::Copy('%(FileName)%(Extension)').EndsWith('.deps.json'))" />
			<_BuildDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'GetCopyToOutputDirectoryItemsOutputGroup'))"
                Condition="$([System.String]::Copy('%(FileName)%(Extension)').EndsWith('.deps.json'))" />
			<PackagingOutputs Condition="'@(_PublishDepsJson)'!='' and '@(_BuildDepsJson)'!=''" Remove="@(_BuildDepsJson)"/>
		</ItemGroup>
	</Target>

```

**Comment by sjb-sjb** [comment] 2022-11-24 03:38
This is still a problem, the standard templates still result in two deps.json as of today.

**Comment by fabiocannas** [comment] 2023-01-27 16:19
> I'm getting syntax errors on that Target, on the two String.Copy lines. I fixed it by removing the single quote at the front of it (in `Condition="'$([System.String] ...`), and adding single quotes to the Copy call (in `::Copy(%(FileName)%(Extension))`)
> 
> ```
> 	<Target Name="RemoveCollidingDepsJson" AfterTargets="GetPackagingOutputs" BeforeTargets="_ComputeAppxPackagePayload">
> 		
> 		<ItemGroup Condition="'@(PackagingOutputs)'!=''" >
> 			<_PublishDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'PublishItemsOutputGroupOutput'))"
>                 Condition="$([System.String]::Copy('%(FileName)%(Extension)').EndsWith('.deps.json'))" />
> 			<_BuildDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'GetCopyToOutputDirectoryItemsOutputGroup'))"
>                 Condition="$([System.String]::Copy('%(FileName)%(Extension)').EndsWith('.deps.json'))" />
> 			<PackagingOutputs Condition="'@(_PublishDepsJson)'!='' and '@(_BuildDepsJson)'!=''" Remove="@(_BuildDepsJson)"/>
> 		</ItemGroup>
> 	</Target>
> ```
Thank you @Scottj1s and @MikeHillberg. Had the same problem with the file Microsoft.Web.WebView2.Core.dll

**Comment by timseverson** [comment] 2023-03-21 14:33
> > I'm getting syntax errors on that Target, on the two String.Copy lines. I fixed it by removing the single quote at the front of it (in `Condition="'$([System.String] ...`), and adding single quotes to the Copy call (in `::Copy(%(FileName)%(Extension))`)
> > ```
> > 	<Target Name="RemoveCollidingDepsJson" AfterTargets="GetPackagingOutputs" BeforeTargets="_ComputeAppxPackagePayload">
> > 		
> > 		<ItemGroup Condition="'@(PackagingOutputs)'!=''" >
> > 			<_PublishDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'PublishItemsOutputGroupOutput'))"
> >                 Condition="$([System.String]::Copy('%(FileName)%(Extension)').EndsWith('.deps.json'))" />
> > 			<_BuildDepsJson Include="@(PackagingOutputs->WithMetadataValue('OutputGroup', 'GetCopyToOutputDirectoryItemsOutputGroup'))"
> >                 Condition="$([System.String]::Copy('%(FileName)%(Extension)').EndsWith('.deps.json'))" />
> > 			<PackagingOutputs Condition="'@(_PublishDepsJson)'!='' and '@(_BuildDepsJson)'!=''" Remove="@(_BuildDepsJson)"/>
> > 		</ItemGroup>
> > 	</Target>
> > ```
> 
> Thank you @Scottj1s and @MikeHillberg. Had the same problem with Microsoft.Web.WebView2.Core.dll


@fabiocannas How did you fix the Microsoft.Web.WebView2.Core.dll?

**Comment by Scottj1s** [comment] 2023-04-12 00:47
@mjfara, sorry you're still having trouble.  Are you seeing the same issue as reported here, with a duplicate deps.json file specifically? There were a few similar scenarios, which were addressed in the latest release, [1.3 Preview 1](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230228005-preview1).

**Comment by HakamFostok** [comment] 2023-09-28 08:55
This should not be closed

**Comment by Jimex** [comment] 2023-11-15 15:05
I encountered a similar issue while compiling my app with .NET 8, WINUI 3, and Native AOT. Unfortunately, the workaround mentioned above did not resolve the issue in this case either.

1>D:\AppCache\.nuget\microsoft.windowsappsdk\1.4.231008000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1500,5): error APPX1101: Payload contains two or more files with the same destination path 'DictTango.exe'. Source files: 
1>D:\AppCache\.nuget\microsoft.windowsappsdk\1.4.231008000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1500,5): error APPX1101: E:\Work\Development\Android\DictTango\DotnetSrc\DictTango\DictTangoWinUI\obj\x64\Debug\net8.0-windows10.0.19041.0\win-x64\apphost.exe
1>D:\AppCache\.nuget\microsoft.windowsappsdk\1.4.231008000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1500,5): error APPX1101: E:\Work\Development\Android\DictTango\DotnetSrc\DictTango\DictTangoWinUI\bin\x64\Debug\net8.0-windows10.0.19041.0\win-x64\native\DictTango.exe
1>Done building project "DictTangoWinUI.csproj" -- FAILED.

**Comment by kmgallahan** [comment] 2023-11-15 15:40
@Jimex AOT isn't supported at this time

https://github.com/microsoft/WindowsAppSDK/discussions/3856#discussioncomment-7017551

**Comment by robinwilson16** [comment] 2024-02-10 12:28
You still cannot use WinUI 3 alongside Microsoft.EntityFramework.Tools as both contain Microsoft.Web.WebView2.Core.dll and it leads to the error above when trying to publish your app whilst it builds and runs fine. This is because it tries to copy the dll file from both repositories.

The app is NET MAUI but it triggers this error as soon as you add Microsoft.EntityFramework.Tools to your project.

The errors have been here since 2021 but the file it fails on has changed from the json file to the dll file (perhaps it was briefly fixed in between).
When two repositories have the same dependency (in this case Web View 2) then Visual Studio just needs to be able to cope with this without just failing, especially if both files are identical or split web view off into its own repository rather than include it in the base WinUI one and one of the ones commonly added to projects for database connectivity.
Linux package manage handles this sort of thing easily but VS just fails then you waste hours researching workarounds.

A check was added to Visual Studio to fail on duplicated files whereas before they just used to overwrite each other but then no mechanism for how to deal with it was added and this overlap on dependencies was never addressed and the issue is closed.

I can't publish a self-contained app whilst this bug still remains but can publish it requiring NET 8 to be installed on the machine already with a workaround which is to add this to the project file which disables the check added to check for duplicated files:

```
<PropertyGroup>
  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
</PropertyGroup>
```

Please could it be re-looked at?

**Comment by Scottj1s** [comment] 2024-03-13 23:01
There are two distinct errors noted in this issue.  

The first is that the logic to address conflicting build vs publish deps.json files was incomplete.  The next release of Windows App SDK will include a fix that covers project references (transitive deps.json conflicts).  Meanwhile, the problem can be worked around with this *.csproj excerpt:

```
  <!-- Temporary workaround until WinAppSDK 1.5.2 provides fix -->
  <Target Name="RemoveConflictingDepsJsonFiles" AfterTargets="GetPackagingOutputs">
    <!-- If conflicting build and publish deps.json files exist in this or referenced projects,
        use only the publish deps.json files, and remove the corresponding build deps.json files. -->
    <ItemGroup>
      <_PublishDepsJsonFiles Include="@(PackagingOutputs->HasMetadata('CopyToPublishDirectory'))"
        Condition="$([System.String]::Copy(%(FileName)%(Extension)).EndsWith('.deps.json'))" />
      <PackagingOutputs Remove="@(_PublishDepsJsonFiles)" MatchOnMetadata="TargetPath"/>
      <PackagingOutputs Include="@(_PublishDepsJsonFiles)"/>
    </ItemGroup>
  </Target>

```

The second issue has to do with WebView2 implementation file conflicts (e.g., Microsoft.Web.WebView2.Core.dll).  The ultimate cause of this was the embedding of WebView2 into Windows App SDK.  The solution is to factor the WebView2 dependency out of Windows App SDK, and replace it with a standard Nuget package reference.  This will also permit a la carte updates to WebView2 outside the Windows App SDK ship cycle.  Our intent is to include this fix in Windows App SDK 1.6.

**Comment by DJRM2021** [comment] 2024-03-14 02:54
> There are two distinct errors noted in this issue.
> 
> The first is that the logic to address conflicting build vs publish deps.json files was incomplete. The next release of Windows App SDK will include a fix that covers project references (transitive deps.json conflicts). Meanwhile, the problem can be worked around with this *.csproj excerpt:
> 
> ```
>   
>   <Target Name="RemoveConflictingDepsJsonFiles" AfterTargets="GetPackagingOutputs">
>     
>     <ItemGroup>
>       <_PublishPackagingOutputs Include="@(PackagingOutputs->HasMetadata('CopyToPublishDirectory'))"/>
>       <_PublishDepsJsonFiles Include="@(_PublishPackagingOutputs)"
>         Condition="'@(_PublishPackagingOutputs)' != '' and $([System.String]::Copy(%(FileName)%(Extension)).EndsWith('.deps.json'))" />
>       <PackagingOutputs Remove="@(_PublishDepsJsonFiles)" MatchOnMetadata="TargetPath"/>
>       <PackagingOutputs Include="@(_PublishDepsJsonFiles)"/>
>     </ItemGroup>
>   </Target>
> ```
> 
> The second issue has to do with WebView2 implementation file conflicts (e.g., Microsoft.Web.WebView2.Core.dll). The ultimate cause of this was the embedding of WebView2 into Windows App SDK. The solution is to factor the WebView2 dependency out of Windows App SDK, and replace it with a standard Nuget package reference. This will also permit a la carte updates to WebView2 outside the Windows App SDK ship cycle. Our intent is to include this fix in Windows App SDK 1.6. We'll keep this issue open to track this work.

https://github.com/microsoft/WindowsAppSDK/issues/4249

**Comment by DJRM2021** [comment] 2024-03-14 02:56
> There are two distinct errors noted in this issue.
> 
> The first is that the logic to address conflicting build vs publish deps.json files was incomplete. The next release of Windows App SDK will include a fix that covers project references (transitive deps.json conflicts). Meanwhile, the problem can be worked around with this *.csproj excerpt:
> 
> ```
>   
>   <Target Name="RemoveConflictingDepsJsonFiles" AfterTargets="GetPackagingOutputs">
>     
>     <ItemGroup>
>       <_PublishPackagingOutputs Include="@(PackagingOutputs->HasMetadata('CopyToPublishDirectory'))"/>
>       <_PublishDepsJsonFiles Include="@(_PublishPackagingOutputs)"
>         Condition="'@(_PublishPackagingOutputs)' != '' and $([System.String]::Copy(%(FileName)%(Extension)).EndsWith('.deps.json'))" />
>       <PackagingOutputs Remove="@(_PublishDepsJsonFiles)" MatchOnMetadata="TargetPath"/>
>       <PackagingOutputs Include="@(_PublishDepsJsonFiles)"/>
>     </ItemGroup>
>   </Target>
> ```
> 
> The second issue has to do with WebView2 implementation file conflicts (e.g., Microsoft.Web.WebView2.Core.dll). The ultimate cause of this was the embedding of WebView2 into Windows App SDK. The solution is to factor the WebView2 dependency out of Windows App SDK, and replace it with a standard Nuget package reference. This will also permit a la carte updates to WebView2 outside the Windows App SDK ship cycle. Our intent is to include this fix in Windows App SDK 1.6. We'll keep this issue open to track this work.

For the 2nd issue (WebView2), I filed this issue, [4249](https://github.com/microsoft/WindowsAppSDK/issues/4249).

**Comment by Scottj1s** [comment] 2024-03-14 17:15
Closing this issue in favor of https://github.com/microsoft/WindowsAppSDK/issues/4249 for tracking EntityFramework build errors

**Comment by DJRM2021** [comment] 2024-03-15 00:28
> Closing this issue in favor of #4249 for tracking EntityFramework build errors

but 4249 is also closed without any permanent fix committed.

**Comment by kmgallahan** [comment] 2024-03-15 01:15
> Resolving this as a dup of https://github.com/microsoft/WindowsAppSDK/issues/1856

> Closing this issue in favor of https://github.com/microsoft/WindowsAppSDK/issues/4249 for tracking EntityFramework build errors

>but 4249 is also closed without any permanent fix committed.

😅

**Comment by robinwilson16** [comment] 2024-03-15 07:41
So with both issues now closed in favour of each other does this mean we are now stuck in an infinitive loop of uncertainty?
Hopefully it's still on someone's fixing lists in the depths of Microsoft.

**Comment by Scottj1s** [comment] 2024-03-19 12:32
Reopened https://github.com/microsoft/WindowsAppSDK/issues/4249 and retitled for clarity

**Closed by Scottj1s** 2024-03-19 12:32 UTC
Labels: area-DeveloperTools
