### ISSUE TITLE
SetDragRectangles area cannot be clickable

### ISSUE THREAD

**Issue by 0Kirby** [microsoft/WindowsAppSDK#2386] opened 2022-04-11 05:38 UTC
### Describe the bug

Reproduce the bug:  
https://github.com/0Kirby/ThrowObjectDetectionWinUI

Using customized TitleBar in my WinUI3 APP, settting **AppWindow.TitleBar.ExtendsContentIntoTitleBar** to "true".
![image](https://user-images.githubusercontent.com/26472465/162664766-a49a1c30-dfd4-4caf-b34d-cfbeb812097a.png)
In order to make the buttons in NavigationView clickable, using **AppWindowTitleBar.SetDragRectangles(RectInt32[])  Method** to set draggable area.  

`RectInt32 rect = new(Convert.ToInt32(leftOffset), 0, Convert.ToInt32(dragSpace), Convert.ToInt32(height));`
`_mainAppWindow.TitleBar.SetDragRectangles(new RectInt32[] { rect });`

![image](https://user-images.githubusercontent.com/26472465/162664987-5ba26dcb-a521-46f8-8c8b-da6927fd38a4.png)
In NavigationView's **Left** or **LeftCompact** display mode , setting `leftOffset=48` to make room for the back button(←).
And it works _**properly**_, the back button(←) cannot be draggable and can be clickable.

![image](https://user-images.githubusercontent.com/26472465/162665965-76ecd1b3-b642-4afd-bb6b-96c65d37e327.png)
In NavigationView's **LeftMinimal** display mode , setting `leftOffset=96` to make room for the back button(←) and the collapse button(≡). 
The area of two button cannot be draggable is _**OK**_. However, the back button(←) can be clickable but the the collapse button(≡) **cannot** be clickable.

### Steps to reproduce the bug

1. Create a WinUI 3 packaged app with some features.
2. When the WindowSize changes, use the method **SetDragRectangles(RectInt32[]**) to set corresponding draggable area according to the NavigationView' display mode.
3. As the NavigationView's display mode changes to **LeftMinimal**, the bug reproduces.

### Expected behavior

In NavigationView's **LeftMinimal** display mode, the back button(←) and the collapse button(≡)  can **both** be clickable.

### Screenshots

![image](https://user-images.githubusercontent.com/26472465/162668908-c81778c7-9ee6-4e21-8833-1e03ed2b40b9.png)
The blue area can be draggable is OK.
The green area should be clickable as expected, but only the red area can be clickable.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

Nuget Package Dependencies:  

    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.197" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.1.635-beta" PrivateAssets="all" />

**Comment by dongle-the-gadget** [comment] 2022-05-14 14:20
Areas defined in `SetDragRectangles` are handled by the system, meaning that your app will not receive any mouse input as the system absorbs them all. The only way to "resolve" this is to make sure that you have the drag rectangles are defined correctly.

**Comment by kingcean** [comment] 2022-05-25 12:20
Sounds like this issue happens when the drag rectangles have changed (including by resize window). In particular, the place will not be clickable anymore (nor can't drag) if it was in the drag rectangles.

It causes it is impossible to implement the design that there is a search box or any other things in title bar, because partial or complete those elements can't focus after the user decreases the window size at any time. The only work-around way is to call `ResetToDefault` of the app window title bar and then call `ExtendsContentIntoTitleBar = true` + `SetDragRectangles(...)` again, but the window will blink unexpectedly.

**Comment by dongle-the-gadget** [comment] 2022-05-26 07:29
You are responsible for keeping up...

**Comment by kingcean** [comment] 2022-05-26 09:31
> You are responsible for keeping up...

Yes, I have. This issue is what it still absorbs all mouse events after we update the drag rectangle. Repro like this way.

1. `SetDragRectangles` a bigger area.
2. `SetDragRectangles` a smaller area.
3. The complementary set area will have no response (no drag nor focusable).

Following is a simple example. Your app will no longer be available to click.

```csharp
appWindow.TitleBar.ExtendsContentIntoTitleBar = true;
appWindow.TitleBar.SetDragRectangles(new RectInt32[]
{
    new RectInt32(0, 0, 10000, 10000)
});
appWindow.TitleBar.SetDragRectangles(new RectInt32[]
{
    new RectInt32(0, 0, 10, 10)
});
```

**Comment by kingcean** [comment] 2022-06-04 10:25
The above issue still exists on Windows App SDK 1.1.0 so I filed a new bug report #2574.

**Comment by rkarman** [comment] 2022-06-07 18:35
From the sample code you provide though it looks like you're trying to set a drag region that is smaller than the icon-area, which would not be possible unless you first disable the icon and system menu by calling:
appWindow.TitleBar.IconShowOptions = IconShowOptions.HideIconAndSystemMenu;
This will allow you to set a drag region for the left-most part of the window as well.

This said, I am unable to reproduce your problem. I can set and re-set the drag region, without a call to ResetToDefault, and have the new drag region be properly set and window be draggable.

Can you create a bare minimal app that reproduces the bug that we can use to investigate further?

**Comment by rkarman** [comment] 2022-06-09 15:46
Thanks @kingcean, the clarification you made on the other thread was really helpful for me. I would like to fold these two issues into a single one though, as they are about the same root cause and any fix we do will be the same for both. It is then just a matter of servicing as appropriate to 1.0 and 1.1.

Since the other issue ( #2574 ) has the additional context that clarifies the problem I'd like to keep that as the one we track and close this one as a dupe of that.

**Closed** 2022-09-09 11:59 UTC
Labels: bug, area-Windowing
