### ISSUE TITLE
LaunchActivatedEventArgs does not contain command line input parameter

### ISSUE THREAD

**Issue by Code-ScottLe** [microsoft/WindowsAppSDK#1797] opened 2021-11-15 22:43 UTC
### Describe the bug

The app currently does not show any input parameters when launching from CMD using execution alias. LaunchedActivatedEventArgs.Arguments shows blank/null. This is using the Single-project packaged WinUI 3 project template.

### Steps to reproduce the bug

1. Create a single project packaged blank app with WinUI 3 desktop
2. Add execution alias in the Project package.appxmanifest
3. Build and deploy the app
4. Set a break point in OnLaunched override in App.xaml.cs
5.  From CMD, try to invoke the app with any input params.
6. Observe the breakpoint in step 4 hit, and see that LaunchActivatedEventArgs.Arguments does not contain any input that was used when invoking from the CMD

### Expected behavior

Was expecting the input params to be available in OnLaunched.

### Screenshots

![image](https://user-images.githubusercontent.com/10987612/141864332-c3b48895-9edc-4050-9e4d-6e25c243c8d3.png)

### NuGet package version

1.0.0-preview3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

**Comment by asklar** [comment] 2021-11-16 15:50
Duplicate of microsoft/microsoft-ui-xaml#3368

**Closed by asklar** 2021-11-16 15:50 UTC
