### ISSUE TITLE
Wrong mouse pointer con ContextFlyout open

### ISSUE THREAD

**Issue by LucaCris** [microsoft/WindowsAppSDK#4277] opened 2024-03-20 14:57 UTC
### Describe the bug

If you right click the mouse on an object with a ContextFlyout menu set, the mouse pointer shape unexpectedly change.

### Steps to reproduce the bug

- Create standard App from Wizard, and upgrade to latest SDK.

- Update the Button control with:

```
<Button x:Name="myButton" Click="myButton_Click">
  <Button.ContextFlyout>
    <MenuFlyout>
      <MenuFlyoutItem Text="Test"/>
    </MenuFlyout>
  </Button.ContextFlyout>
  Click Me
</Button>

```

- Launch App
- Right click on button without move pointer
- The hourglass will appear: wrong
- Resize the window
- Right click on button without move pointer
- The sizer will appear: wrong

### Expected behavior

No pointer shape change

### Screenshots

First try:
![20240320_153827](https://github.com/microsoft/WindowsAppSDK/assets/50824617/af88cc2d-6667-47a6-8f80-f91040e87802)

Second try, after resize:
![20240320_153854](https://github.com/microsoft/WindowsAppSDK/assets/50824617/a006dc7d-6a62-40f9-9383-7eb6c7274632)

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Also in latests 1.4... but not before!

**Comment by codendone** [comment] 2024-03-21 02:22
Thanks for this report! This looks like the same underlying issue as microsoft/microsoft-ui-xaml#8829. Closing as duplicate of that issue (which is currently being investigated).

**Closed by codendone** 2024-03-21 02:22 UTC
