### ISSUE TITLE
WinAppSDK v1.1.0 throws System.AccessViolationException on Unpackaged  WinUI 3 apps

### ISSUE THREAD

**Issue by AndrewKeepCoding** [microsoft/WindowsAppSDK#2578] opened 2022-06-05 14:18 UTC
### Describe the bug

Unpackaged WinUI 3 apps throw ``System.AccessViolationException`` at the very start you run the app.

### Steps to reproduce the bug

1. Create a WinUI 3 app from **Blank App, Packaged (WinUI 3 in Desktop)**.
2. Add ``<WindowsPackageType>None</WindowsPackageType>`` to the csproj file.
3. Change the debug property to **[projectname] (Unpackaged)**.
    * The app runs (Debugger or the EXE file) without problems to this point.
4. Update **WinAppSDK** NuGet package to v1.1.0.
5. Run the app (F5) but you get the exception.

### Expected behavior

Runs without exceptions or errors.

### Screenshots

![image](https://user-images.githubusercontent.com/80524586/172054397-5fb5894d-a243-4176-b56d-09e72336dc22.png)

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by AndrewKeepCoding** [comment] 2022-06-05 14:24
By the way, the **Issue: Bug report** form has no **1.1.0** option in the **NuGet package version** list.

**Comment by rocksdanister** [comment] 2022-06-05 16:29
I had the same problem, uninstalling preview WinAppSdk fixed it for me:

https://github.com/microsoft/PowerToys/pull/18603#issuecomment-1146690684

**Comment by AndrewKeepCoding** [comment] 2022-06-05 23:38
I haven't installed any **WinAppSDK** preview packages, but at least setting ``WindowsAppSDKSelfContained`` to ``true`` worked for me. Thanks!😊 But I think this is a bug, so I'll keep it open and let the team close it.

**Comment by aepot** [comment] 2022-06-29 11:30
Uninstalled everything related to Windows App SDK using PowerShell, then installed 1.1 from [website](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads) with the latest installer.

NuGet Package 1.1.0 works fine.
But 1.1.1 fails to start because `AccessViolationException` as described int the initial post.

`<WindowsAppSDKSelfContained>` doesn't work for me because Visual Studio 2022 failed to publish the app with this option but debug mode worked fine.

Downgrading **Microsoft.WindowsAppSDK** NuGet Package to 1.1.0 solved the problem.
So the 1.1.1 Package seems to be broken.

_Windows 11 21H2_

**Comment by mikebattista** [comment] 2022-07-01 16:26
Just confirmed this is fixed in 1.1.2 shipping soon.

**Closed by mikebattista** 2022-07-01 16:26 UTC
Labels: bug

**Comment by AndrewKeepCoding** [comment] 2022-07-02 04:41
@mikebattista Thank you all!😎
