### ISSUE TITLE
Installing a previous <major>.<minor> version fails to install the DDLM packages for that version

### ISSUE THREAD

**Issue by DHancock** [microsoft/WindowsAppSDK#3602] opened 2023-05-01 14:53 UTC
### Describe the bug

If you manually install the x64 Windows App Runtime version 1.3.0, using a non elevated terminal session on a machine that doesn't have any WinAppSdk installed on it and then install x64 version 1.2.5, the version 1.2.5 DDLM packages won't be installed. The installer doesn't indicate an error. Similarly if you then install version 1.1.4, the version 1.1.4 DDLM packages also won't be installed.

Interestingly, if you try to install version 1.2.5 for a second time the installer identifies that it needs to install the DDLM packages, but will again fail to install them.

### Steps to reproduce the bug

1. Open a non elevated terminal session (cmd or ps)
2. Install WinAppSdk runtime version 1.3.0 
3. Install WinAppSdk runtime version 1.2.5
4. Check for the existance of version 1.2.5 DDLM packages

<details>
<summary>For example...</summary>

````

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\david> (get-appxpackage *appruntime*).count
0
PS C:\Users\david> cd 'c:\test'
PS C:\test> ./WindowsAppRuntimeInstall-1.3.0.exe
INFO: Provisioning of WindowsAppSDK packages will be skipped as it requires elevation.
Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.3_3000.820.152.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.3_3000.820.152.0_x86__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: MicrosoftCorporationII.WinAppRuntime.Main.1.3_3000.820.152.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: MicrosoftCorporationII.WinAppRuntime.Singleton_3000.820.152.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: Microsoft.WinAppRuntime.DDLM.3000.820.152.0-x6_3000.820.152.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: Microsoft.WinAppRuntime.DDLM.3000.820.152.0-x8_3000.820.152.0_x86__8wekyb3d8bbwe
Package deployment result : 0x0
All install operations successful.
PS C:\test> ./WindowsAppRuntimeInstall-1.2.5.exe
INFO: Provisioning of WindowsAppSDK packages will be skipped as it requires elevation.
Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x86__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: MicrosoftCorporationII.WinAppRuntime.Main.1.2_2000.802.31.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: Microsoft.WinAppRuntime.DDLM.2000.802.31.0-x6_2000.802.31.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0
Deploying package: Microsoft.WinAppRuntime.DDLM.2000.802.31.0-x8_2000.802.31.0_x86__8wekyb3d8bbwe
Package deployment result : 0x0
All install operations successful.
PS C:\test> get-appxpackage *DDLM* | Select PackageFullName

PackageFullName
---------------
Microsoft.WinAppRuntime.DDLM.3000.820.152.0-x6_3000.820.152.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.3000.820.152.0-x8_3000.820.152.0_x86__8wekyb3d8bbwe


PS C:\test> get-appxpackage *appruntime* | Select PackageFullName

PackageFullName
---------------
Microsoft.WindowsAppRuntime.1.3_3000.820.152.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.3_3000.820.152.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Main.1.3_3000.820.152.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.3000.820.152.0-x6_3000.820.152.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.3000.820.152.0-x8_3000.820.152.0_x86__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x64__8wekyb3d8bbwe
Microsoft.WindowsAppRuntime.1.2_2000.802.31.0_x86__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Main.1.2_2000.802.31.0_x64__8wekyb3d8bbwe
MicrosoftCorporationII.WinAppRuntime.Singleton_3000.820.152.0_x64__8wekyb3d8bbwe


PS C:\test> ./WindowsAppRuntimeInstall-1.2.5.exe --dry-run
INFO: Provisioning of WindowsAppSDK packages will be skipped as it requires elevation.
Installing license: MSIX_MAINPACKAGE_LICENSE
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Deploying package: Microsoft.WinAppRuntime.DDLM.2000.802.31.0-x6_2000.802.31.0_x64__8wekyb3d8bbwe
Deploying package: Microsoft.WinAppRuntime.DDLM.2000.802.31.0-x8_2000.802.31.0_x86__8wekyb3d8bbwe
All install operations successful.
PS C:\test>

````

</details>

### NuGet package version

Windows App SDK 1.3.0: 1.3.230331000

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

#

**Comment by ssparach** [comment] 2024-11-11 19:32
This issue is an duplicate of https://github.com/microsoft/WindowsAppSDK/issues/3855

**Closed by ssparach** 2024-11-11 19:32 UTC
Labels: duplicate, area-Deployment, area-Installer
