### ISSUE TITLE
Update MessageDialog and PopupMenu with Sun Valley design

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/WindowsAppSDK#1302] opened 2021-08-24 09:00 UTC
# Proposal: Update MessageDialog and PopupMenu with Sun Valley design
MessageDialog and PopupMenu are the two classes in the Windows.UI.Popups namespace and are UI framework agnostic however they currently have an outdated design that doesn't match the rest of Windows 11. While XAML apps should use ContentDialog and MenuFlyout instead, many existing apps still use these classes and also it's the only pre-included option for apps that render on their own.

## Summary
Update the style and design of MessageDialog and PopupMenu with a modern design that matches WinUI 2.6 ContentDialog and MenuFlyout design as much as possible. Win32 GDI MessageBox and HMenu have gotten a refresh so MessageDialog and PopupMenu should also have a modern design. 

## Rationale

* More consistent user interface

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers that use MessageDialog or PopupMenu to use a more modern design | Must |

**Comment by Jaiganeshkumaran** [comment] 2021-08-24 09:03
One thing that I don't like about MessageDialog is that the title is repeated twice, one in the title bar as it's a separate window and inside the dialog. I feel like that's unnecessary and the title bar should be hidden. This issue also exists in system consent dialogs for permissions.

**Comment by asklar** [comment] 2021-08-24 19:30
CC @tjp9889  @SavoySchuler

**Comment by riverar** [comment] 2021-08-24 21:40
Seems like this should really be transferred to the WinUI repo.

**Comment by asklar** [comment] 2021-08-24 22:12
these are not xaml/winui APIs.

**Comment by riverar** [comment] 2021-08-25 01:58
This would fall under WinUI 2.x right?

**Comment by chigy** [comment] 2023-09-12 17:47
Thank you for the feature request. In order for us to be transparent to our community members, we are proactively closing any feature requests that we do not believe we can realistically get to in the next 1-2 years. If you feel this is feature is critical and urgent, and need to be prioritized over other issues our team is currently looking to delivering, please add detailed information about how the app ecosystem would benefit from it when reopening the issue. It will be very helpful for us, thanks!

**Closed by chigy** 2023-09-12 17:47 UTC
Labels: feature, area-Shell UX

**Comment by Sergio0694** [comment] 2023-09-13 13:38
> "these are not xaml/winui APIs"

What's the correct way for people to report stuff like this? I agree WinAppSDK is not the right place since this is just an OS API, but how can people outside report this kind of thing, given they can't just create a task/bug in the OS repo like we do?

**Comment by asklar** [comment] 2023-09-13 15:03
> > "these are not xaml/winui APIs"
> 
> What's the correct way for people to report stuff like this? I agree WinAppSDK is not the right place since this is just an OS API, but how can people outside report this kind of thing, given they can't just create a task/bug in the OS repo like we do?

@Sergio0694 my comment was in reply to @riverar who suggested this be moved to the WinUI repo. These apis aren't WinUI apis so it doesn't make a lot of sense to put the issue there.
WinAppSDK _could_ come up with a _new_ API (so the issue in this repo is fine) with the right styling. However as chigy mentioned, realistically the team is not going to prioritiz it in the next 1-2 years.

**Comment by riverar** [comment] 2023-09-13 15:36
Sergio is asking for an answer the eternal question: how do developers report OS API issues? I'm interested in that answer too.

I think the best option for developers right now is to post it on Microsoft Q&A ([Windows API - Win32](https://learn.microsoft.com/en-us/answers/tags/224/windows-api-win32) tag) which is staffed and supported. I'll check in with the Q&A folks but I suspect the FTEs/vendors there have backchannels they can use in the event a _question_ reveals an OS bug.

FTEs internally tell me the Feedback Hub (Developer Platform > API Feedback) is not actively triaged/unmonitored so developers should stay away from that. Or perhaps use that to generate a link to a VSO item, a necessary _currency_ when working with certain individuals.

**Comment by Sergio0694** [comment] 2023-09-13 16:03
> "WinAppSDK could come up with a new API"

@asklar right, but (as far as I understand), the point here was precisely to just update the built-in command instead. Not just because that'd benefit all existing users (and just make the end result look more consistent to users), but also because I'm not sure asking eg. WinForms/WPF developers to take over 50 MB worth of native dependencies (for WASDK in self-contained mode, and that's per CPU arch too) just to display a dialog is something that would necessarily be viable for them 😅

> "Sergio is asking for an answer the eternal question: how do developers report OS API issues?"

Yeah that was what I was trying to ask. Updating something in WUX is by definition an OS issue, and there doesn't seem to be a place for users to do that. Feedback Hub is (imho) not the right place for this kind developer proposals/reports. And opening issues in the WinAppSDK repo always ends up with them just being closed because they're "out of scope" (which of course they are, since they're OS bugs, not WASDK related at all). It seems like external devs are just not in a good position with respect to this, and unless they directly know Microsoft folks they can reach out too, there's just no proper process in place 🥲

**Comment by asklar** [comment] 2023-09-13 16:05
I understand your concerns. It is correct that feedback hub is the place to file OS issues.

**Comment by chigy** [comment] 2023-09-13 19:55
> I understand your concerns. It is correct that feedback hub is the place to file OS issues.

I want to confirm that Feedback Hub is the place to file OS issues as asklar mentioned.

I cannot comment on the past communication made on this topic, but we (Microsoft) are monitoring this area (Developer Platform > API Feedback) and appropriate follow up has been made internally. Please note, just as any feature request, an existence of an issue does not always mean there is enough priority for it to be acted upon. That said, we have not seen much input in Feedback Hub to my knowledge.
 
Also, please do not report OS API requests to Microsoft Q&A. It is not a bug reporting and tracking site, and they are most likely going to get lost.

**Comment by riverar** [comment] 2023-09-13 20:02
@chigy Thanks for following up. Be aware Feedback Hub is wiped regularly and that should be considered when looking at metrics.
