### ISSUE TITLE
WebView2 not handling DOM events properly

### ISSUE THREAD

**Issue by Foda** [microsoft/WindowsAppSDK#4477] opened 2024-06-06 17:16 UTC
### Describe the bug

Starting from WindowsAppSDK 1.4.240211001, DOM events fired inside WebView2 are not handled properly, making the use of custom select boxes (for instance) impossible.

Copied from https://github.com/dotnet/maui/issues/22697 as this issue is affecting customers of MAUI.

Note: this does NOT happen in the WPF/WinForms version of Webview2 -- it is an issue specifically w/ WinAppSDK

### Steps to reproduce the bug

1. Just create a new app and add the following XAML:
`<WebView2 x:Name="webView" Source="https://google.com"/>`

2. Click on the app selector icon.
3. Click on any link to be redirected to any Google app.
4. The menu closes and the navigation is not done.

![image](https://github.com/microsoft/WindowsAppSDK/assets/890772/c8d292e8-8a76-414d-9782-eb1f8dd09be3)
![image](https://github.com/microsoft/WindowsAppSDK/assets/890772/9abc2cd6-c306-4d52-b956-5cad7586c5d4)

### Expected behavior

The navigation to the selected Google app should have been done.

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022-preview, Visual Studio 2022, Visual Studio 2019

### Additional context

https://github.com/MicrosoftEdge/WebView2Feedback/issues/4598

**Comment by codendone** [comment] 2024-06-12 00:20
Closing as duplicate of microsoft/microsoft-ui-xaml#9566, which has a fix in [Version 1.5.4 (1.5.240607001)](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-154-15240607001).

**Closed by codendone** 2024-06-12 00:20 UTC
Labels: needs-triage
