### ISSUE TITLE
Cannot install Dev17 VSIX in China

### ISSUE THREAD

**Issue by masonwu21** [microsoft/WindowsAppSDK#1817] opened 2021-11-17 13:55 UTC
### Describe the bug

when i install WindowsAppSDK.Cs.Extension.Dev17.Standalone.vsix ,it couldn't download Microsoft.VisualStudio.Ide.Payload in china internet

2021/11/17 18:45:26 - 找到的已安装产品 - 全局位置
2021/11/17 18:45:26 - 找到的已安装产品 - Visual Studio Enterprise 2022 Current
2021/11/17 18:45:26 - ID 为“Microsoft.WindowsAppSDK.Cs.Dev17”的扩展未安装到 Visual Studio Enterprise 2022 Current。
2021/11/17 18:45:31 - BEGIN: Downloading extension: https://projectreunion.gallery.vsassets.io:443/_apis/public/gallery/publisher/ProjectReunion/extension/MicrosoftSingleProjectMSIXPackagingToolsDev17/0.9.10.2111041/assetbyname/Microsoft.VisualStudio.Ide.Payload?redirect=true&update=true
2021/11/17 18:50:04 - WebClient download failed: 操作超时. Bits download failed: 找不到文件。. WinInet download failed: Function: InternetOpenUrl, HR: -2147012894, Message: Unknown error 12002
2021/11/17 18:50:04 -    在 Microsoft.VisualStudio.Setup.Download.DownloadManager.DownloadWithRetry(IDownloadEngine[] engines, Uri uri, Stream outputStream, ProgressUpdateCallback progress, CancellationToken cancellationToken, DownloadContext downloadContext, Boolean verifySignature)
   在 Microsoft.VisualStudio.Setup.Download.DownloadManager.<>c__DisplayClass23_0.<Download>b__0()

### Steps to reproduce the bug

run WindowsAppSDK.Cs.Extension.Dev17.Standalone.vsix in china

### Windows version

Windows 11 (22000)

**Comment by andrewleader** [comment] 2021-11-17 21:30
Hey @DefaultRyan, this looks like a potential bug with installing the Dev17 VSIX in China.

**Comment by DefaultRyan** [comment] 2021-11-18 20:13
Hi @andrewleader and @masonwu21 , is there any data to suggest that this is due to running in China and not some other element? This bug, as currently written, is not really actionable for me - I can't take a trip to China with a laptop to try and reproduce. Can somebody come up with some steps to be able to reproduce this issue?

Judging from the error log snippet, it looks like the VSIX installer was attempting to download the single-project MSIX Packaging Tools extension. If, the Visual Studio Marketplace is unreachable (firewall, no internet), then one would hit this error.

**Comment by riverar** [comment] 2021-11-18 22:58
@DefaultRyan How is Microsoft testing Windows App SDK to ensure global readiness? Can't you reach out to someone in Microsoft China to try this?

**Comment by dotMorten** [comment] 2021-11-18 23:02
@masonwu21 Can you install this? https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17

**Comment by DefaultRyan** [comment] 2021-12-01 03:21
I'm almost positive this is an internet connectivity issue, and is a duplicate of #1846. Please try the workaround I posted to that issue and reopen if it doesn't work.

**Closed by DefaultRyan** 2021-12-01 03:21 UTC
Labels: area-Developer tools
