### ISSUE TITLE
Need to make title bar min/max/close buttons to top right corner when arabic language is selected for the system

### ISSUE THREAD

**Issue by Sunilam** [microsoft/WindowsAppSDK#3455] opened 2023-02-22 09:45 UTC
### Describe the bug

Hi Team,

Currently when i select arabic language for the system, the win ui3 app title bar min/max/close buttons are coming to top left corner.
Need to make title bar min/max/close buttons to top right corner when arabic language is selected for the system.

### Steps to reproduce the bug

Currently when i select arabic language for the system, the win ui3 app title bar min/max/close buttons are coming to top left corner.
Need to make title bar min/max/close buttons to top right corner when arabic language is selected for the system.

### Expected behavior

Need to make title bar min/max/close buttons to top right corner when arabic language is selected for the system.

### Screenshots

![image](https://user-images.githubusercontent.com/7436855/220582995-0056fb10-4400-40d8-96c6-c2565660409c.png)

### NuGet package version

1.1.5

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by JaiganeshKumaran** [comment] 2023-02-24 15:08
@Sunilam Arabic is right to left so wouldn't this be the expected behaviour?

**Comment by gabbybilka** [comment] 2023-03-02 17:12
Dupe of https://github.com/microsoft/WindowsAppSDK/issues/3452

**Closed by gabbybilka** 2023-03-02 17:12 UTC
