### ISSUE TITLE
Incompatible with dotnet FX and C++/WinRT runtime components

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/WindowsAppSDK#2740] opened 2022-07-15 10:16 UTC
### Describe the bug

Creating a single project MSIX package with reference to a C++/WinRT runtime component results in invalid appxmanifest.xml-file.
Invalid content in AppxManifest.xml:
```
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>RuntimeComponent1.dll</Path>
      </InProcessServer>
    </Extension>
  </Extensions>
```

### Steps to reproduce the bug

1. Download sample project ([wappsdk.zip](https://github.com/microsoft/WindowsAppSDK/files/9119961/wappsdk.zip))
2. Extract, and open developer terminal in that folder
3. Run
```
msbuild -p:RestorePackagesConfig=true -p:GenerateAppxPackageOnBuild=True -restore -t:Rebuild .\wappsdk.sln -p:Platform=x64 -p:Configuration=Debug
```
4. Observe: Package is generated successfully.
5. Run
```
msbuild -p:RestorePackagesConfig=true -p:GenerateAppxPackageOnBuild=True -restore .\wappsdk.sln -p:Platform=x64 -p:Configuration=Debug
```
6. Observe error:
`Error info: error C00CE012: App manifest validation error: The app manifest must be valid as per schema: Line 37, Column 8,`
7. Behavior is non-deterministic
  - With `/t:Rebuild` (or `/t:Clean;Build`) package creation works always
  - With `/t:Build` using previous built output results in bad manifest generation, this makes working in Visual Studio extremely frustrating, as deploying forces a new build, which fails, due to manifest validation issues

### Expected behavior

Expected part of AppxManifest.xml:
```
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>RuntimeComponent1.dll</Path>
        <ActivatableClass ActivatableClassId="RuntimeComponent1.Class" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>
```

### NuGet package version

1.1.2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

This worked fine in WindowsAppSdk `1.0`.

**Comment by muramasa** [comment] 2022-07-18 02:52
I'm facing the same issue with  Visual Studio 2019.

**Comment by btueffers** [comment] 2022-07-21 19:29
Looks like it may be related to https://github.com/microsoft/WindowsAppSDK/issues/2749

**Comment by AliveDevil** [comment] 2022-07-21 19:32
@btueffers yes, I‘d agree. That are the same symptoms, with the same cause, possibly.

**Comment by DefaultRyan** [comment] 2022-07-21 19:45
Duplicate of #2749

**Comment by DefaultRyan** [comment] 2022-07-21 19:46
This is already being tracked by internal bug http://task.ms/40265852, assigned to @evelynwu-msft. If it's OK with you, I'll close this as a duplicate.

**Closed by DefaultRyan** 2022-07-21 19:46 UTC
Labels: bug, area-Developer tools

**Comment by rtorr** [comment] 2022-07-22 00:17
How should we track internal bug's status?

**Comment by AliveDevil** [comment] 2022-07-22 10:49
I assume #2749 is closed or assigned a milestone once there is an internally tracked solution, though I'd like to see that that github issue is updated from Microsoft with status update comments.
