### ISSUE TITLE
App Crashes with "ResourceMap not found" depending on the Package Name, and the use of NavigationView

### ISSUE THREAD

**Issue by DominicMaas** [microsoft/WindowsAppSDK#2527] opened 2022-05-18 19:19 UTC
### Describe the bug

This was a nightmare bug that I accidently managed to reproduce. Also not sure if it belongs in the WinUI Repo (feel free to transfer if it does).

If you set the package name of a Packaged WinUI3 application to something like 'Test' (in my case, it was the app name, four alpha characters "Xxxx"), and also use a NavigationView. The app will crash during runtime with "ResourceMap Not Found". 

Changing the package name to something like "TestApp.MyApp" fixes the crash. "TestAppMyApp" doesn't work, but "ThisIsMyReallyCoolTestApp" does. So, I'm not really sure what is going on.

I managed to fix it in my case by using "CompanyName.AppName", but this behaviour is extremely inconsistent, and almost impossible to track down. 

```
Exception thrown at 0x768CC3A2 in WinUIWAPTest.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x02B7CF00.

UnhandledExceptionEventArgs: ResourceMap Not Found
```

### Steps to reproduce the bug

1. Create a new "Blank App, Packaged with Windows Application Packaging Project (C#)"
2. Replace the contents of `MainWindow.xaml` with a `NavigationView`.
3. Under the packaging project, change the package name to `Test` (or Identity->Name within the xml)
4. Run within Visual Studio / Create MSIX. Observe how the MSIX is created successfully, but app crashes.

### Expected behavior

The app does not crash on runtime. If these package ids are invalid, throw an error during package creation.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000), Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by evelynwu-msft** [comment] 2022-05-18 20:28
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6360.

**Closed** 2022-05-18 20:28 UTC
