### ISSUE TITLE
windowsappsdk can't build with normal checkout, nuget restore keep asking private/internal microsoft azure aritfact credential

### ISSUE THREAD

**Issue by uppet** [microsoft/WindowsAppSDK#4374] opened 2024-04-28 13:23 UTC
### Describe the bug

I'm trying to use winappsdk to learn window app samples

### Steps to reproduce the bug

checkout windowsapp sdk
run nuget restore

it keep telling me to login with microsoft account. when log in. it says I'm not(of course) Microsoft organize member. 

### Expected behavior

should be buildable without internal account

### NuGet package version

Windows App SDK 1.5.2: 1.5.240404000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ghost1372** [comment] 2024-04-28 14:28
if you want to run samples, you need to clone sample repo
https://github.com/microsoft/windowsappsdk-samples

**Comment by uppet** [comment] 2024-04-29 15:43
> if you want to run samples, you need to clone sample repo https://github.com/microsoft/windowsappsdk-samples

the first time I run [windowsappsdk-samples](https://github.com/microsoft/windowsappsdk-samples) it fail.
but after I try many step to build windowsappsdk, the sample run wroks.

still want to build the windowsappsdk, for study reason.

**Comment by codendone** [comment] 2024-05-03 01:55
Closing as duplicate of #4315.

**Closed by codendone** 2024-05-03 01:55 UTC
