### ISSUE TITLE
x64 Runtime installer includes x86 and ARM files

### ISSUE THREAD

**Issue by aqibbanday** [microsoft/WindowsAppSDK#2280] opened 2022-03-17 05:06 UTC
### Describe the bug

x64 Runtime installer includes x86 and ARM files which increases the size of installer.

![image](https://user-images.githubusercontent.com/10510359/158740936-011ac774-a62c-48d8-a290-9c0c59988124.png)

### Steps to reproduce the bug

Install x64  WinSDK Runtime.

**Comment by DrusTheAxe** [comment] 2022-03-23 07:07
Yes, it does. This isn't a bug, it's ByDesign.

The installer installs whatever packages are applicable for a system (x64 systems can run x86 as well as x64 apps, and arm64 can run x86+x64+arm64). This is significant for the Framework and DDLM packages. OTOH the Main and Singleton packages only need one flavor, but it's the native (matching host cpu) that's installed (the optimal choice).

**Comment by BenJKuhn** [comment] 2022-03-28 19:16
Resolving as by design per Howard's comments.

**Closed by BenJKuhn** 2022-03-28 19:16 UTC
