### ISSUE TITLE
HyperLinkButton cannot navigate to an email URI

### ISSUE THREAD

**Issue by myfix16** [microsoft/WindowsAppSDK#3381] opened 2023-01-30 13:25 UTC
### Describe the bug

In my application, I added a HyperLinkButton with a `mailto:` navigation URI for users to submit inquiries, which looked like this:
`<HyperlinkButton Content="hyperlink"  NavigateUri="mailto:someone@example.com" />`

However, I clicked the button, and nothing happened.

### Steps to reproduce the bug

1. Create an empty Windows App SDK 1.2 packaged app
2. Add a `HyperLinkButton` as shown above
3. Run the application and click the button

### Expected behavior

The default email application should launch and ask you to send an email.

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by castorix** [comment] 2023-01-30 14:06
There was a similar issue : [Hyperlinkbutton not working with uri of type mailto:someone@somewhere.com #4438](https://github.com/microsoft/microsoft-ui-xaml/issues/4438)

**Comment by gabbybilka** [comment] 2023-02-02 17:19
Closing as dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/4438, thanks @castorix for linking

**Closed by gabbybilka** 2023-02-02 17:19 UTC
