### ISSUE TITLE
Exception in combase.dll trying to launch App on Windows 11 Insider Preview

### ISSUE THREAD

**Issue by ePirat** [microsoft/WindowsAppSDK#999] opened 2021-06-29 21:20 UTC
**Describe the bug**

Using a simple project I created on Windows 10 with Visual Studio Community 2019 Preview (16.11.0 Preview 2.0) and Project Reunion 0.8, when building and running that after updating to the Windows 11 Insider preview (21H2, Build 22000.51) it now crashes with an exception in `combase.dll`. (There are no symbols available for combase.dll, so the debugger does not give me much details)

**Steps to reproduce the bug**

1. Create a project in Visual Studio using Project Reunion 0.8
2. Update to Windows 11 Insider preview

**Expected behavior**

The app does not crash

**Version Info**

- Windows 11 21H2 Build 22000.51
- Visual Studio Community 2019 Preview Version 16.11.0 Preview 2.0

NuGet package version: 

- Microsoft.ProjectReunion (0.8.0)
- Microsoft.ProjectReunion.Foundation (0.8.0)
- Microsoft.ProjectReunion.WinUI (0.8.0)
- System.Drawing.Common (5.0.2)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.51 co_release)              |  Yes   |
| May 2020 Update (19041)            | No   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by asklar** [comment] 2021-06-30 00:16
Duplicate of microsoft/microsoft-ui-xaml#5295

**Closed by asklar** 2021-06-30 00:16 UTC
