### ISSUE TITLE
DEP2500: Registration succeeded, but package registration information cannot be found.

### ISSUE THREAD

**Issue by axelriet** [microsoft/WindowsAppSDK#1505] opened 2021-09-29 08:45 UTC
Not sure if it's the right place to report this but I tried to use the WindowsAppSDK to make a blank WinUI desktop app and it does not start: the deployment fails. The error is _"DEP2500: Registration succeeded, but package registration information cannot be found. The layout folder is "E:\Misc\App1\App1\App1 (Package)\bin\x64\Debug\AppX"_

Project Reunion 0.8.4.53805616
Windows App SDK 1.0.0.50489432
Windows 19042.1237

I de-installed/reinstalled a few times, tried stable, preview, experimental: same result.

**Comment by andrewleader** [comment] 2021-09-30 19:18
Hey @cwruss, can you look into this?

**Comment by sachintaMSFT** [comment] 2022-04-26 12:43
The issue is raised on 0.8 and 1.0 preview releases. There are no reports from stable releases. Closing the issue.

**Closed by sachintaMSFT** 2022-04-26 12:43 UTC
Labels: bug, area-App deployment
