### ISSUE TITLE
Restart API not working with unpackaged apps in 1.1.3

### ISSUE THREAD

**Issue by Balkoth** [microsoft/WindowsAppSDK#2792] opened 2022-07-27 12:58 UTC
### Describe the bug

Official documents https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#app-lifecycle--restart mention this should work for packaged and unpackaged apps, but using
`Microsoft.Windows.AppLifecycle.AppInstance.Restart("");`
as described here https://github.com/microsoft/WindowsAppSDK/blob/main/specs/AppLifecycle/Restart/restartApi.markdown#new-api
 just crashes the app.

### Steps to reproduce the bug

Just use this sample to verify:
[TestRestartManager.zip](https://github.com/microsoft/WindowsAppSDK/files/9198925/TestRestartManager.zip)

### NuGet package version

1.1.3

### Packaging type

Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by Balkoth** [comment] 2022-07-27 13:54
It just crashes the whole application without getting a chance to debug even with native debugging enabled and all exceptions checked.

Once `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` is set on the project you get  a file not found exception. Turn out that RestartAgent.exe is not distributed:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/80055480/181264633-4d1d38b0-a763-43d2-961a-8d66fc488da6.png">

**Comment by kanismohammed** [comment] 2022-08-01 17:36
@Balkoth  thanks for providing the feedback. We will take a look at the issue and keep you posted on the updates

**Comment by mikebattista** [comment] 2022-08-01 21:50
With Template Studio 5.2 using 1.1.3, `Restart("")` works fine for me for both packaged and unpackaged projects. I do see a failure though when switching to self-contained. I get FileNotFound exceptions from the API which I assume is referring to RestartAgent.exe that you shared above.

**Comment by mikebattista** [comment] 2022-08-01 22:17
https://task.ms/40728649

**Comment by mikebattista** [comment] 2022-08-02 15:27
My next guess would be that it's a downlevel problem since you're on 19044. @kanismohammed are these APIs supported downlevel?

**Comment by kanismohammed** [comment] 2022-08-02 17:08
> My next guess would be that it's a downlevel problem since you're on 19044. @kanismohammed are these APIs supported downlevel?

@dhoehna  - Can you please take a look?

**Comment by dhoehna** [comment] 2022-08-02 17:44
It was already answered here: https://github.com/microsoft/WindowsAppSDK/issues/2792#issuecomment-1196793506

The restart agent isn't being included when WASDK is self-contained.

**Comment by dhoehna** [comment] 2022-08-02 17:45
I can work on getting the restart agent to deploy with everything else.

**Comment by mikebattista** [comment] 2022-08-02 17:48
Thanks. There are two issues though. The self-contained issue is one. It's possible the Restart API doesn't work for unpackaged apps downlevel. We need to investigate.

**Comment by Balkoth** [comment] 2022-08-09 19:23
Is there some more investigation ongoing or will this just be buried like all other bug reports?

**Comment by dhoehna** [comment] 2022-08-09 19:28
I'm looking into it.  Progress has been slow, that's all.

**Comment by dhoehna** [comment] 2022-08-29 19:07
Sorry for the gap in communication. I'm reporting in that I did find the root cause of the issue.

The root cause of the issue is in the OS code.  More research is needed to figure out where a fix should go.  Most likely Windows App SDK.

Again, sorry for the delay in communication.  It took a bit longer than expected to hunt down this issue.

@mikebattista We might need to add internal hours to find a fix for this issue.
@kanismohammed FYI.

**Comment by mikebattista** [comment] 2022-08-29 19:16
@dhoehna I've already filed https://task.ms/40728649. Do we need another bug?

**Comment by dhoehna** [comment] 2022-09-14 18:47
Alrighty.  Updating this.  Sorry it took so long.  The bug was deeper than I though.

This is a platform issue in VB.  The ACLs on the folder in Windows Apps is Low IL.  What this means is, even if the parent app is medium-IL, any process made in the frameworks folder, for example, RestartAgent.exe, "...\windowsapps\[Fwp]\RestartAgent.exe" is lowIL.

Since restartAgent.exe creates the same process that was restarted, and, new processes inherit the parent processes IL, that means, the new process is also LowIL.

Now I'll be talking with peeps to figure out "What do we do about this and how do we fix it."

Again, sorry this is taking so long.  I'm still working on it though.

**Comment by dhoehna** [comment] 2022-10-19 16:55
The ACLs are being changed and should be serviced in February.

**Comment by Balkoth** [comment] 2022-12-14 09:54
Will this also be fixed for unpackaged application with <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>?

**Comment by Balkoth** [comment] 2023-02-27 06:48
Has this been serviced?

**Comment by appindus-ibiller** [comment] 2023-03-08 18:43
> The ACLs are being changed and should be serviced in February.

Is this fixed? If so what needs to be updated on our ends?

**Comment by dhoehna** [comment] 2023-03-08 20:46
Sorry for the late reply.  This change was serviced on February 2nd.  

To get the correct ACLs for Windows App SDK please either
1. Remove then add Windows App SDK, or
2. Update Windows App SDK to a newer version.

Essentially the framework package needs to be removed, then installed.

**Comment by dhoehna** [comment] 2023-03-08 20:46
I'm currently looking into a way to verify the fix is on a system so I can let ya'll know if the patch is present.

**Comment by appindus-ibiller** [comment] 2023-03-08 21:08
@dhoehna Thanks for the reply! This will work for self-contained as well? Will we need to upgrade to 1.3 preview/wait for stable? or Will the WASDK's Feb release 1.2.4 suffice?

**Comment by Balkoth** [comment] 2023-03-09 06:55
It is not fixed for self-contained apps as the original problem that `RestartManager.exe` is not distributed still persists.

**Comment by Balkoth** [comment] 2023-05-15 07:21
Still not fixed in `1.3.1`

**Comment by SlavDeV1991** [comment] 2023-07-20 11:06
Any update on this?
I'm able to restart the C++ packaged app, but I'm unable to restart the unpackaged application.

**Comment by ivan-miracle** [comment] 2023-07-31 13:36
Is there any update on this issue? I have WindowsAppSDK **1.3.230724000** installed, and the problem is still there. My app is also an unpackaged applications with `WindowsAppSDKSelfContained` enabled. Thanks.

**Comment by zhuxb711** [comment] 2023-08-02 01:23
It takes over one year and this issue is still there. Is that reasonable for WinUI team?

**Comment by AdamBraden** [comment] 2023-08-17 14:47
The issue with RestartAgent.exe not being included in selfcontained apps is fixed in 1.4 preview 2.

**Closed by AdamBraden** 2023-08-17 14:47 UTC
