### ISSUE TITLE
Application as a ShareTarget works but it's opening an additional window with the splash image

### ISSUE THREAD

**Issue by itonx** [microsoft/WindowsAppSDK#3943] opened 2023-11-08 03:07 UTC
### Describe the bug

Original report in [MAUI issue #18536](https://github.com/dotnet/maui/issues/18536)

Same problem with a new fresh WinUI3 application.

### Steps to reproduce the bug

I described all steps for a .NET MAUI application [here](https://github.com/dotnet/maui/issues/18536)

For WinUI3 it's kind of the same:
1. Create a new WinUI3 application (I used the Template Studio for WinUI but it's the same if you create the app with the "Blank App, Packaged (WinUI 3 in Desktop)" option).
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/ad005cae-b9f6-4518-accd-c46e639118c7)
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/c7b1b75e-435c-4b2c-ac8c-e8b0a84535cc)
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/9700586c-9d05-4d16-a41c-49a2dae7f16f)
2. Set up the application as a Share Target by updating the Package.appxmanifest.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/3e5cff19-736a-4980-a2a8-a5e84f76fa05)
3. Run the application.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/6ccfd0db-5c6c-4c7f-b71d-6a57803da389)
4. Go to a file and share it using the WinUI3 application.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/36bf25ec-51c3-4a2d-afae-5b148e7e0bfa)
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/c6163b16-0424-4652-a1ed-318e9efed4f2)

Two windows will be opened:
- The WinUI3 application.
- A blank window with the splash logo.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/ee08e8bd-3a7a-4a37-aa6c-49ba9577d525)

WinUI3 is also showing the splash logo in the blank window. The difference between .NET MAUI and WinUI3 is that WinUI3 has the splash logo at Assets/SplashScreen.scale-200.png. You can confirm that with the next steps:
1. Uninstall the WinUI3 app from Windows (and stop the app if you're running it with visual studio).
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/2035b73e-a25c-4ca1-b011-ca1fd9ef4179)
2. Replace the Assets/SplashScreen.scale-200.png file with a custom png file.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/ad5c09e8-1058-47dd-8148-d1f33c4d0870)
3. Clean the solution.
4. Build the solution.
5. Run the application.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/eb38c5b6-c9be-40da-ac14-d9d7e40009cd)
6. Share a file using the WinUI3 app.
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/a642533f-8c60-48d5-9559-7b0812e27ecd)
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/3484d6b8-d40a-41db-b878-934d3a1180c5)

Two windows will be opened:
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/9aee438f-c508-4915-b5ba-eda45140356f)

### Expected behavior

Only the application window should be opened after selecting the application to share a file.

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022

### Additional context

I am using Windows 11 version 23H2 (OS Build 22631.2506)

More info:
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/c6d0154f-aa42-4bc9-9bf3-f2155af84b6c)
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/745271f4-6912-4de3-a496-399aad69b32f)

**Comment by michael-hawker** [comment] 2023-11-08 20:43
@itonx, do you think this is just a duplicate of the issue I had opened? https://github.com/microsoft/WindowsAppSDK/issues/3941

I included my minimal repo project (and comparison with UWP) there as well.

**Comment by kmahone** [comment] 2024-03-01 21:17
Dupe of #3941. See the comment that I added there for me info.

**Closed by kmahone** 2024-03-01 21:17 UTC
Labels: area-Share
