### ISSUE TITLE
System backdrop shows error after theme changed in 1.2 preview 2

### ISSUE THREAD

**Issue by Scighost** [microsoft/WindowsAppSDK#3095] opened 2022-11-01 04:16 UTC
### Describe the bug

At the beginning, the `ApplicationTheme` and `ElementTheme` are both default, and the backdrop color and fallback color are both correct. Then change theme in application. Backdrop color is correct but fallback color is wrong. Comparatively, change theme in system. Fallback color is correct but backdrop color is wrong. When change back to the original theme, both are correct.

This problem occurs in 1.2 preview 2 and not exist in 1.1.5.

### Steps to reproduce the bug

See the video

### Expected behavior

Same as 1.1.5

### Screenshots

https://user-images.githubusercontent.com/61003590/199155612-a04025b0-1ead-4652-b7d3-1066b0e23000.mp4

### NuGet package version

1.2.220930.4-preview2

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

### Additional context

Windows version: 22621

**Comment by DarranRowe** [comment] 2022-11-01 13:05
While part of that is clearly WinUI related, are you able to reproduce the backdrop not changing theme independently? I.e., not part of a WinUI/Xaml application?

The Xaml Window class uses the ICompositionSupportsSystemBackdrop interface to communicate with the system backdrop, where using it via the desktop composition doesn't. This helps figure out if it is WinUI or the backdrop itself that is the problem.

Also, does it fail in the same way with Desktop Acrylic?

**Comment by Scighost** [comment] 2022-11-01 13:35
> While part of that is clearly WinUI related, are you able to reproduce the backdrop not changing theme independently? I.e., not part of a WinUI/Xaml application?

I don't know how to do it.

> Also, does it fail in the same way with Desktop Acrylic?

Yes, it still occurs with Acrylic.

**Comment by DarranRowe** [comment] 2022-11-02 00:28
Okay. I got a little sample together. It is a Windows API window which doesn't use WinUI/Xaml.

https://user-images.githubusercontent.com/52577874/199365645-376186c7-5d56-49ff-a372-87a0527bc7b3.mp4

As you can see, the backdrop doesn't properly change with the system theme change in this case either.

**Comment by gabbybilka** [comment] 2022-11-03 16:14
Closing as dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/7801, we're currently testing a fix.

**Closed by gabbybilka** 2022-11-03 16:14 UTC
Labels: bug, area-Composition
