### ISSUE TITLE
Resources return wrong value after change RootTheme

### ISSUE THREAD

**Issue by steam3d** [microsoft/WindowsAppSDK#3487] opened 2023-03-05 18:25 UTC
### Describe the bug

Resources return wrong value after change RootTheme

### Steps to reproduce the bug

```cs
//Root theme is dark when app runs
if (((FrameworkElement)window.Content).Resources.TryGetValue("ApplicationPageBackgroundThemeBrush", out object value))
	var brush = (SolidColorBrush)value; //has dark color


if (window.Content is FrameworkElement rootElement)
	rootElement.RequestedTheme = ElementTheme.Light;
	
if (((FrameworkElement)window.Content).Resources.TryGetValue("ApplicationPageBackgroundThemeBrush", out object value))
	var brush = (SolidColorBrush)value; // Always will has dark color until restarting app
```

### Expected behavior

When theme changed resources should return color from new theme.

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment] 2023-03-09 17:10
Closing as dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/8249, thanks for filing.

**Closed by gabbybilka** 2023-03-09 17:10 UTC
