### ISSUE TITLE
WebView2 HDR enabled for Microsoft store apps submitted in the gaming category

### ISSUE THREAD

**Issue by gaviny82** [microsoft/WindowsAppSDK#3577] opened 2023-04-16 11:53 UTC
### Describe the bug

I am using WebView2 to display an authentication dialog in my app, and HDR is enabled for the content in the WebView2 control while the other area of the app looks normal (making the dialog much brighter). I am testing on Windows 11 with auto HDR enabled and this issue only happens with MSIX packaged app with a particular package ID.

This app is a tool that helps manage data for a game and it is submitted in the category Gaming > Tools. It cannot pass the certification process for Utility & Tools category because it contains game content. I think this is because Windows enables HDR for all apps that are identified as games.

### Steps to reproduce the bug

1. Register an app in Partner Center in the game category.
2. Associate a WinUI 3 app with the app id.
3. Add a WebView2 control in the app and set a URL.
4. Enable auto HDR in Windows 11.
5. The content in the WebView2 control has HDR enabled.

### Expected behavior

I am not sure if this is really a bug or expected behavior, but I am unable to find any workaround to solve this issue except changing the package id.

### NuGet package version

Windows App SDK 1.2.5: 1.2.230313.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment] 2023-04-27 16:16
From the Webview2 team, if the monitor is HDR, it will use HDR regardless of category of the software

**Comment by gaviny82** [comment] 2023-04-29 21:18
> From the Webview2 team, if the monitor is HDR, it will use HDR regardless of category of the software

I tried to create a blank WinUI app and run this in the MainWindow.
```csharp
ContentDialog dialog = new ContentDialog
{
    XamlRoot = this.XamlRoot,
    Style = Application.Current.Resources["DefaultContentDialogStyle"] as Style,
    Title = "Test WebView2",
    Content = new WebView2() { Width = 500, Height = 1000, Source = new("https://bing.com/") }
};

await dialog.ShowAsync();

```
It looks normal on a HDR enabled monitor.

For my app submitted to the store, HDR is enabled for the WebView2 content.

**Comment by LegendaryBlair** [comment] 2024-11-12 03:14
According to WebView2 team, this behavior is by design. Closed as won't fix.

**Closed by LegendaryBlair** 2024-11-12 03:14 UTC
