### ISSUE TITLE
FileOpenPicker PickMultipleFilesAsync Break in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/WindowsAppSDK#467] opened 2021-02-15 21:39 UTC
**Describe the bug**

The FileOpenPicker in WinUI3 Preview4 Desktop sample solution breaks and closes the application when trying to open multiple items. Exception details below in the last section.

**Steps to reproduce the bug**

1. Clone the [WinUI3 Preview4 Problems FilePicker repository](https://github.com/eleanorleffler/WinUI3Preview4_Problems_FileOpenPicker). 
2. Go to the FilePickerWinUIPreview4 folder.
3. Open the FilePickerWinUIPreview4 solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click the second / bottom button "FileOpenPicker: Multiple Files". (The first button should work as expected.)
6. Select one or more files.
7. Click "Open". Crash should occur.

**Expected behavior**

We expect the application to display the path of the selected file(s) or folder.

We expect the FileOpenPicker to allow the user to select multiple files as it does in UWP.

**Screenshots**

![ExpectedBehavior](https://user-images.githubusercontent.com/9272634/107994895-338a8300-6fa3-11eb-8e1d-4a42ec3ce9a9.PNG)

![CurrentBehavior2](https://user-images.githubusercontent.com/9272634/107994919-3eddae80-6fa3-11eb-9aa6-6a34eb30d416.PNG)

Screenshot#1a and 1b - Current Behavior (Single File working and Crash Error Message)

![CurrentBehavior1](https://user-images.githubusercontent.com/9272634/107994904-36857380-6fa3-11eb-94f2-bed6d016faa1.PNG)

Screenshot#2 - Expected Behavior (File paths of selected files)

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1803 (10.0; Build 17134)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| 		Yes 	   |  				  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

Exception Details

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef)
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.<.ctor>b__8_1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.AsInternal(InterfaceTag`1 _)
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.GetEnumerator()
   at FileOpenPickerWinUIPreview4.MainWindow.<fileOpenPickerMultipleButton_Click>d__2.MoveNext() in \FileOpenPickerWinUIPreview4\FileOpenPickerWinUIPreview4\MainWindow.xaml.cs:line 60

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))

**Comment by andrewleader** [comment] 2021-03-01 21:24
Hey @BenJKuhn, gentle reminder to triage this bug 😊

**Comment by AmSmart** [comment] 2021-05-12 18:40
I get a similar error with ``FolderPicker``'s ``PickSingleFolderAsync``.

Any workarounds for now?

**Comment by andrewleader** [comment] 2021-05-12 19:05
Hi @AmSmart, for PickSingleFolderAsync, are you using `IInitializeWithWindow`? In desktop apps, you need to use `IInitializeWithWindow` to associate your HWND with the API before calling PickSingleFolderAsync, see this example: https://github.com/microsoft/ProjectReunion/issues/466#issuecomment-779628934

**Comment by AmSmart** [comment] 2021-05-12 19:51
Yeah, I used the ``IInitializeWithWindow`` interface. The issue was that I didn't specify a file type filter. Looking through the [docs](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker?view=winrt-19041#methods), I discovered that not specifying it generates an exception. It's all resolved now. Thanks for the swift response!

**Comment by freistli** [comment] 2021-05-19 05:49
I got the same issue on PickMultipleFilesAsync, which crashes WinUI/Reunion WPF desktop app. But PickSingleFolderAsync works well. Do we have workaround or fix now? Thanks in advance.

**Comment by Aloento** [comment] 2021-06-04 05:58
FileSavePicker also crashed even use InitializeWithWindow

**Comment by andrewleader** [comment] 2021-06-04 17:45
**PickMultipleFilesAsync is unfortunately not supported right now**. You can instead use the Win32 API GetOpenFileName, we're working on posting a workaround sample for that.

@Aloento make sure when you're calling `this.As<IWindowNative>()`, the `this` object is a `Window` object. If you're still seeing problems, you can open a new issue, and please provide a full example of the code you're calling, what specifically is failing, etc. Thanks!

**Comment by Aloento** [comment] 2021-06-05 00:44
> **PickMultipleFilesAsync is unfortunately not supported right now**. You can instead use the Win32 API GetOpenFileName, we're working on posting a workaround sample for that.
> 
> @Aloento make sure when you're calling `this.As<IWindowNative>()`, the `this` object is a `Window` object. If you're still seeing problems, you can open a new issue, and please provide a full example of the code you're calling, what specifically is failing, etc. Thanks!

https://github.com/microsoft/ProjectReunion/issues/909

**Comment by freistli** [comment] 2021-06-05 06:14
I'd like to share the workaround of using Interop GetOpenFileName API call.

By researching several links and verifying some experiments:

https://docs.microsoft.com/en-us/windows/win32/dlgbox/open-and-save-as-dialog-boxes
https://stackoverflow.com/questions/9088227/using-getopenfilename-instead-of-openfiledialog
https://social.msdn.microsoft.com/forums/vstudio/en-US/2f4dd95e-5c7b-4f48-adfc-44956b350f38/getopenfilename-for-multiple-files

I can  workaround this issue as below:

Notes:  This works in Project Reunion 0.8 Preview. If you are using WinUI3 Preview or Project Reunion 0.5, may hit this bug:

https://github.com/microsoft/microsoft-ui-xaml/issues/4952

And need to upgrade the project to 0.8 by going through:
https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release

The helper class is as attached: 
[Libwrap.txt](https://github.com/microsoft/ProjectReunion/files/6602028/Libwrap.txt)

The calling sample code snippet:
`
            string[] files = LibWrap.ShowOpenFileDialog("Select Files","c:\\users\freistli\\documents", "All files\0 *.*\0", true, true);

            if (files != null)
            {
                FPS.Text = "";
                foreach (var file in files)
                {
                    Debug.WriteLine("Selected file with full path: {0}", file);
                    FPS.Text += file + "\r\n";
                }
            }
`

Hope this helps.

**Comment by tom-huntington** [comment] 2021-08-11 00:31
Just confirming this is not an issue on cppwinrt after
```
picker.as<IInitializeWithWindow>()->Initialize(hwnd);
```

**Comment by manodasanW** [comment] 2021-08-18 03:06
The wrong thread exception in the repro app looks to be fixed with the CsWinRT update in .NET SDK 5.0.302.  Specifically, the CsWinRT fix for calling non agile objects (https://github.com/microsoft/CsWinRT/issues/844) resolves it.

**Comment by andrewleader** [comment] 2021-08-18 15:28
Awesome @manodasanW, so can you confirm that PickMultipleFilesAsync is now functional for C# apps if you use .NET SDK 5.0.302 and the IInitializeWithWindow?

**Comment by andrewleader** [comment] 2021-08-18 15:41
I just confirmed that `PickMultipleFilesAsync` is now functional thanks to @manodasanW's fix available in the latest .NET SDK `5.0.302`!

**Update VS using the Visual Studio Installer to get the latest .NET**, and then the following code should work! I tested this in a WinUI 3 Desktop app using Microsoft.ProjectReunion 0.8. You can replace the following code in a File->New project to see the picker working!

```csharp
private async void myButton_Click(object sender, RoutedEventArgs e)
{
    myButton.Content = "Picking files...";

    var picker = new Windows.Storage.Pickers.FileOpenPicker
    {
        // Make sure you specify FileTypeFilter, it's required
        FileTypeFilter =
        {
            "*"
        }
    };

    // Make sure to get the HWND from a Window object... if calling from a helper method,
    // you'll have to pass a Window reference to GetWindowHandle
    var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
    WinRT.Interop.InitializeWithWindow.Initialize(picker, hwnd);

    var files = await picker.PickMultipleFilesAsync();

    myButton.Content = string.Join(", ", files.Select(i => i.Name));
}
```

**Closed by andrewleader** 2021-08-18 15:41 UTC
Labels: area-Infrastructure, servicing-consider

**Comment by harvinders** [comment] 2021-11-01 11:07
` var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);`, in the example given `this` is a `Windows`. 

@andrewleader How do we get the `Window` object in a `Page` object?

**Comment by andrewleader** [comment] 2021-11-01 16:20
@harvinders you'll have to statically store the current `Window` somewhere you can access it globally. If your app only has one single window, the easiest thing to do is, **in your App.xaml.cs**, refactor...

```csharp
private Window m_window;
```

to...

```csharp
public static readonly Window MainWindow;
```

And then when you need to reference it, you can do...

```csharp
var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(App.MainWindow);
```

**Comment by volvereabhi** [comment] 2023-10-30 05:48
[Is there any way to pick multiple files and folders with the same OpenPicker in WinUi 3?]

**Comment by castorix** [comment] 2023-10-30 09:20
> [Is there any way to pick multiple files and folders with the same OpenPicker in WinUi 3?]

For both files and folders, a way is with [IFileDialogCustomize ](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ifiledialogcustomize)
(I had posted a test sample at [WinUI3_IFileDialog](https://github.com/castorix/WinUI3_IFileDialog))

**Comment by volvereabhi** [comment] 2023-10-30 09:32
@castorix Getting error.

![Screenshot 2023-10-30 145930](https://github.com/microsoft/WindowsAppSDK/assets/28340316/aebbaf54-fd96-48bb-8d21-00d40ae008f2)

**Comment by castorix** [comment] 2023-10-30 11:00
> @castorix Getting error.
> 
> ![Screenshot 2023-10-30 145930](https://user-images.githubusercontent.com/28340316/279002282-aebbaf54-fd96-48bb-8d21-00d40ae008f2.png)

It is another error that some people met from Google
Did you build as Unpackaged ?
Do you have windows10.0.19041.0 SDK installed ?

**Comment by volvereabhi** [comment] 2023-10-30 11:02
@castorix No, I am trying with windows 11

**Comment by castorix** [comment] 2023-10-30 11:35
> @castorix No, I am trying with windows 11

Maybe try from a new WinUI 3 blank project, then set it Unpackaged, then add code by copy/paste...

**Comment by volvereabhi** [comment] 2023-10-31 05:15
@castorix Still can't select multiple folder.

What is use of this button ?
![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/b49f99f3-5b8e-4824-af06-3006cc1fc3a5)

**Comment by volvereabhi** [comment] 2023-10-31 05:28
2nd option ( choose directory ) can't select multiple folders 

![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/1b9c6d10-8082-4cc7-86f3-edb0b84577c1)

**Comment by volvereabhi** [comment] 2023-10-31 05:41
@castorix Can we select multiple folders and multiple files at the same time?

**Comment by castorix** [comment] 2023-10-31 07:57
> @castorix Can we select multiple folders and multiple files at the same time?

Yes, with the custom Button added in the Dialog Box (that I named "Return selected items") :

![IFileDialogTest](https://github.com/microsoft/WindowsAppSDK/assets/22345506/78ea83c7-c6c9-4787-82a0-56b646c76744)

**Comment by volvereabhi** [comment] 2023-10-31 10:08
@castorix Can we remot this button from picker?

![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/00e0d63c-a1ce-40bd-9ad2-a740125c1a6a)

**Comment by volvereabhi** [comment] 2023-10-31 13:56
@castorix Can we change the position to return the selected item button?

**Comment by castorix** [comment] 2023-10-31 15:04
I copied-pasted _CFileDialog.cs_ with quick changes to hide Open button and resize the custom button, to be improved : https://pastebin.com/NqLCLytq

![IFileDialogTest_Resize](https://github.com/microsoft/WindowsAppSDK/assets/22345506/7196a4bc-232d-452e-bc88-e94dbf053a98)

**Comment by volvereabhi** [comment] 2023-10-31 15:12
![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/2ec5372e-f659-43f4-b3a2-a4482b5913d4)

**Comment by castorix** [comment] 2023-10-31 16:01
Yes, I made a last change that I did not test...
For quick fix (but not great because the button text is hardcoded atm) :
Remove _static_  at
_static ObservableCollection<PushButton>_
Uncomment/Comment at :
_IntPtr hWndButton = FindWindowEx(m_hWndDialog, IntPtr.Zero, null, " Return selected items ");
//IntPtr hWndButton = FindWindowEx(m_hWndDialog, IntPtr.Zero, null, m_Buttons[0].Label);_

**Comment by castorix** [comment] 2023-10-31 16:25
Is it the custom button that you renamed ?
If yes, change the text " Return selected items " by your button text ("Select" or other) (in WindowSubClass) 
or _FindWindowEx_ won't find it to change its position with _SetWindowPos_

**Comment by volvereabhi** [comment] 2023-10-31 17:30
Like that,

![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/29244a30-3237-4d08-a27b-159fc88b9e09)

**Comment by castorix** [comment] 2023-10-31 17:39
Yes, if the text is exactly "Select" (without paces)
And  for a cleaner code, a test should be added to check if hWndButton != IntPtr.Zero

**Comment by volvereabhi** [comment] 2023-10-31 18:03
Did it still not change select folder location,

![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/46e004df-fc1b-4b7d-b3c1-737bc4ddaa19)

![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/b450f7d4-2b96-4389-8d39-39917b5ec315)

**Comment by castorix** [comment] 2023-10-31 18:23
You have set 0, 0 for location in _SetWindowPos_, instead of 
_pt.x + (rcOpen.right - rcOpen.left) + 12, pt.y_

**Comment by volvereabhi** [comment] 2023-10-31 18:40
Still not change position of that select button,

![image](https://github.com/microsoft/WindowsAppSDK/assets/28340316/a361df4c-0fd3-479c-8fbc-1f434fba0ebe)

Can you share your code snippet if it's changing at your side ?

**Comment by castorix** [comment] 2023-10-31 19:22
In the main code :
_cfd.AddPushButton(ID_PUSHBUTTON, "Select");_

The class :
https://pastebin.com/a2Ntn335

Result :

![image](https://github.com/microsoft/WindowsAppSDK/assets/22345506/554d309d-b8b1-4654-ab58-05fb023d8fa9)

**Comment by volvereabhi** [comment] 2023-11-01 17:01
@castorix All going perfectly but the files/folder picker is open in full screen. Can we change the size?

**Comment by castorix** [comment] 2023-11-02 08:57
> @castorix All going perfectly but the files/folder picker is open in full screen. Can we change the size?

On my OS, Windows 10 22H2, it saves the position/dimensions and it is opened at the latest ones.
For example, if I double-click on caption to set it Fullscreen, it will be re-opened Fullscreen next time; if I set it at 50, 50 with 100*100, it will be re-opened exactly at same location/size next time, and so on...

**Comment by castorix** [comment] 2023-11-20 15:52
Are you sure it is the same code ? (I don't see the test on _bOpen_ for example)
I get **S_OK** as result when I click on Select button (Unpackaged, Windows 10 22H2)) :

![image](https://github.com/microsoft/WindowsAppSDK/assets/22345506/69dc96a7-5590-4b96-a051-b6019e0f9c32)

**Comment by albus25** [comment] 2023-11-20 16:16
@castorix Yes, it is the same code, as I don't need the bOpen, so I removed that variable.

**Comment by castorix** [comment] 2023-11-20 19:08
Does the code go in _WM_APP_FILEDIALOG_ where I fill the file names and return S_OK ? : 

![image](https://github.com/microsoft/WindowsAppSDK/assets/22345506/fe6c245a-66d5-4389-afe7-a6ad2ce8bd78)

**Comment by albus25** [comment] 2023-11-21 05:52
@castorix No, it does not go.

**Comment by castorix** [comment] 2023-11-21 06:35
Is _m_hWndOwner_ correct at :
 (the window handle passed as 1st parameter of _ShowDialog_)

            public void OnButtonClicked([In][MarshalAs(UnmanagedType.Interface)] IFileDialogCustomize pfdc, [In] int dwIDCtl)
            {
                IntPtr pClassPtr = Marshal.GetIUnknownForObject(this);
                SendMessage(parentCFD.m_hWndOwner, WM_APP_FILEDIALOG, (IntPtr)dwIDCtl, (IntPtr)pClassPtr);
                return;
            }

**Comment by volvereabhi** [comment] 2023-12-16 10:41
Hello @castorix  Brother, We have been getting unknown expectations for 7-10 days. I can't share the whole project with you due to the large dependency on a backend server and complexity. So, can we connect on a remote session for 15 min ([ Link](https://calendly.com/volvere--universe/screen-sharing-session-with-abhi) )? It will save a lot time of and it will be very helpful to us. I hope you can understand our situation. Thanks a lot in advance. 

![error_1](https://github.com/microsoft/WindowsAppSDK/assets/28340316/3594508c-d521-4816-9cf9-c496a97ceed8)
