### ISSUE TITLE
In UWP Release version cannot run by double clicking the exe file in the folder?

### ISSUE THREAD

**Issue by sudharsan-narayanan** [microsoft/WindowsAppSDK#4407] opened 2024-05-13 14:08 UTC
### Describe the bug

When UWP compiled into Release version, after build

Cannot run by double clicking the exe file in the folder?

### Steps to reproduce the bug

1. Create a new UWP project.
2. Add any MS control. 
3. Run the UWP project.
4. Now open the bin folder and try to launch the exe.

Note: exe won't launch.

### Expected behavior

Need to launch the exe in double click by UWP.

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

**Comment by ghost1372** [comment] 2024-05-13 15:20
UWP app can not be opened by exe! If you mean winui app or wasdk app you need to change your app from packaged to unpackaged so you can run your app by double clicking on exe file

**Comment by jonwis** [comment] 2024-05-13 18:58
Generally, packaged apps are designed to only run when _activated_ - like launched from the start menu, or from a file-type/protocol-scheme invocation, etc.  Windows App SDK does not support UWP (packaged, AppContainer, CoreWindow presentation, CoreApplication lifecycle) applications at this time.

As @ghost1372 says, UWP applications built with the Windows Platform SDK using one of the Visual Studio Universal Windows App projects cannot be launched by double-click.  Instead, use the "Run" option in Visual Studio.  Or use the "Deploy" option and then find your application in the Start Menue.

This is by design.

**Comment by DrusTheAxe** [comment] 2024-05-19 04:07
> Generally, packaged apps are designed to only run when _activated_

As Jon mentioned, UWP apps are run via _activation_ via [ApplicationActivationManager's ActivateApplication()](https://learn.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-iapplicationactivationmanager-activateapplication) or [AppListEntry.LaunchAsync()](https://learn.microsoft.com/uwp/api/windows.applicationmodel.core.applistentry.launchasync?view=winrt-22621). This is what Visual Studio does when you hit F5 to run you project.

But if you need to run your app by launching an executable (via CreateProcess, ShellExecute, etc) you can define an [App Execution Alias](https://learn.microsoft.com/uwp/schemas/appxpackage/uapmanifestschema/element-uap5-appexecutionalias) for your app and run that.

Here's additional information about App Executation alias: https://blogs.windows.com/windowsdeveloper/2017/07/05/command-line-activation-universal-windows-apps/

**Comment by codendone** [comment] 2024-05-23 16:39
Closing as answered / By Design.

**Closed by codendone** 2024-05-23 16:39 UTC
Labels: area-UWP, area-External
