### ISSUE TITLE
using dotnet build in Class Library failed

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#3509] opened 2023-03-15 21:28 UTC
### Describe the bug

i want to use dotnet build command and other dotnet commands in terminal but it fails.

### Steps to reproduce the bug

1. create a winui3 class library
2. open terminal
3. type dotnet build

### Expected behavior

project should be compile

### Screenshots

![Uploading image.png…]()

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

```

C:\Users\mahdi\.nuget\packages\microsoft.windowsappsdk\1.2.230313.1\buildTransitive\MrtCore.PriGen.targe
ts(911,5): error MSB4062: The "Microsoft.Build.Packaging.Pri.Tasks.ExpandPriContent" task could not be l
oaded from the assembly C:\Program Files\dotnet\sdk\7.0.202\\Microsoft\VisualStudio\v17.0\AppxPackage\\M
icrosoft.Build.Packaging.Pri.Tasks.dll. Could not load file or assembly 'C:\Program Files\dotnet\sdk\7.0
.202\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.Build.Packaging.Pri.Tasks.dll'. The system canno
t find the path specified. Confirm that the <UsingTask> declaration is correct, that the assembly and al
l its dependencies are available, and that the task contains a public class that implements Microsoft.Bu
ild.Framework.ITask. [D:\Programming\Github\WinUICommunity\WinUICommunity.Shared\WinUICommunity.Shared\W
inUICommunity.Shared.csproj::TargetFramework=net7.0-windows10.0.19041.0]
```

**Comment by gabbybilka** [comment] 2023-03-16 16:30
Closing as dupe of https://github.com/microsoft/WindowsAppSDK/issues/2981, see comments for additional info.

**Closed by gabbybilka** 2023-03-16 16:30 UTC
