### ISSUE TITLE
[1.1.4] [Regression?] WindowsAppRuntimeInstaller.exe fails if newer version is present 

### ISSUE THREAD

**Issue by DominicMaas** [microsoft/WindowsAppSDK#2997] opened 2022-09-26 21:06 UTC
### Describe the bug

Installing 1.1.4 on a system with 1.1.5 fails. 

Easy to test this out in Windows Sandbox.

### Steps to reproduce the bug

1. Run `WindowsAppRuntimeInstall.exe` for version 1.1.5
2. Run `WindowsAppRuntimeInstall.exe` for version 1.1.4, see error, even though it was fixed in #2723

```
Installing license: MSIX_MAINPACKAGE_LICENSE
Install result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe
Package deployment result : 0x80073d06 The package could not be installed because a higher version of this package is already installed.
ErrorMessage: Windows cannot install package Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe because it has version 1004.584.2120.0. A higher version 1005.616.1651.0 of this package is already installed.One or more install operations failed. Result: 0x80073d06
```

### Expected behavior

Installer should report a success error code, as the dependency is installed. This breaks my current installer on machines that have 1.1.5 already installed.

**Comment by DrusTheAxe** [comment] 2022-09-26 23:42
@sachintaMSFT tag you're it

Seems a dupe of a known issue. And fix in progress?

**Comment by sachintaMSFT** [comment] 2022-09-28 13:36
> @sachintaMSFT tag you're it
> 
> Seems a dupe of a known issue. And fix in progress?

No, it is not a known issue. Nothing changed in the code path of this fix. So, looking into it.

**Comment by tristanlabelle** [comment] 2024-01-16 22:29
I'm seeing this issue as well with 1.4:
```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073D06, The package could not be installed because a higher
version of this package is already installed.
Windows cannot install package Microsoft.WindowsAppRuntime.1.4_4000.1049.117.0_x64__8wekyb3d8bbwe because it has
version 4000.1049.117.0. A higher version 4000.1082.2259.0 of this package is already installed.
NOTE: For additional information, look for [ActivityId] 40eea5b5-47a2-0002-def0-f640a247da01 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 40eea5b5-47a2-0002-def0-f640a247da01

**Closed** 2024-10-25 17:20 UTC
Labels: bug, duplicate, area-Installer
