### ISSUE TITLE
unpackaged app using gets meaningless error when trying to call DD manually

### ISSUE THREAD

**Issue by asklar** [microsoft/WindowsAppSDK#2213] opened 2022-03-06 22:23 UTC
0. Have an unpackaged winappsdk C++ app 
1. call the MddBootstrapInitialize API
expected: success
actual: fails with "not supported".

the reason is that there's the AutoInitialize code that will initialize WinAppSDK on dll attach.
Later on when we try to call MddBootstrapInitialize manually, it fails becuse it's already been initialized
We need better error messaging than "not supported". Requiring people to debug into the winappsdk code to figure out what's going wrong is a failure.

**Comment by DrusTheAxe** [comment] 2022-03-07 20:55
This was ByDesign. Bootstrapper could only be initialized once. Subsequent calls fail as it was expected to be an overt (explicit) act in main. That was a year ago. Then late 2022 we added the auto-initialization in WinUI projects.

I'll update the bootstrapper allow multiple calls and succeed if compatible, else give a clear error why it fails.

**Comment by DrusTheAxe** [comment] 2022-03-14 18:23
This has multiple follow ups:

1. Documentation -- in progress
2. Improved logging -- in progress e.g.  https://github.com/microsoft/WindowsAppSDK/issues/1883#

Closing this issue as it's a dupe of others

**Comment by riverar** [comment] 2022-03-14 18:31
I'd argue it should continue to fail on multiple initialize (e.g. with a `ERROR_ALREADY_INITIALIZED`) to ward off potential explosions when an enterprising developer dedupes the calls on the caller's side.

**Comment by DrusTheAxe** [comment] 2022-03-14 18:33
> I'd argue it should continue to fail on multiple initialize (e.g. with a `ERROR_ALREADY_INITIALIZED`) to ward off potential explosions when an enterprising developer dedupes the calls on the caller's side.

Oops. Yes. Sorry, that is being addressed . My bad I didn't realize this is the bug tracking that.

This bug is _mostly_ a dupe of others, the unique issue left is "MddBootstrapInitialize() cannot be called 2+ times". It will be

**Comment by riverar** [comment] 2022-03-14 18:39
> [...] the unique issue left is "MddBootstrapInitialize() cannot be called 2+ times". It will be

This is what I'm arguing _against_. I am not sure this is a great idea.

**Comment by DrusTheAxe** [comment] 2022-03-14 18:58
It'll be OK to call multiple times...**if additional calls are satisfied with what's loaded.**

```
MddBootstrapInitialize(1.0, experimental1, minversion=1.2.3.4)
=> v1.3.5.7 is loaded
MddBootstrapInitialize(1.0, experimental1, minversion=1.2.3.4)
=> Today=FailFast, Tomorrow=Success
MddBootstrapInitialize(1.1, experimental1, minversion=0.0.0.0)
=> Today=FailFast, Tomorrow=Error
MddBootstrapInitialize(1.0, preview2, minversion=0.0.0.0)
=> Today=FailFast, Tomorrow=Error
MddBootstrapInitialize(1.0, experimental1, minversion=2.4.6.8)
=> Today=FailFast, Tomorrow=Error
```

1st to ask causes Bootstrapper to resolve the criteria to a specific package.

2nd+ to ask will succeed _if the resolved package meets the requested criteria_. If the resolved package doesn't satisfy the criteria MddBootstrapInitialize will fail.

Multiple asks for compatible answers is OK. Multiple calls to incompatible answers will are not (and will error, rather than failfast)

**Comment by riverar** [comment] 2022-03-14 18:58
My thinking is: initializing twice is an indication of a programming error.

Some prior art:

* `CoInitialize`
   - Subsequent calls result in `S_FALSE`
   - Appears to mutate internal state which requires caller to pair each call with a `CoUninitialize`
* `IAudioProcessingObject::Initialize`
   - Subsequent calls result in `APOERR_ALREADY_INITIALIZED`
* `IInitializeWithFile::Initialize`
   - Subsequent calls result in `ERROR_ALREADY_INITIALIZED`
* `ICertPropertyRenewal::Initialize`
   - Subsequent calls result in `ERROR_ALREADY_INITIALIZED`
* https://www.google.com/search?q=site%3Adocs.microsoft.com+intitle%3AInitialize+%2B%22ERROR_ALREADY_INITIALIZED%22

**Comment by DrusTheAxe** [comment] 2022-03-14 22:32
`S_FALSE` &lt;shudder&gt;

Yes lots of Win32 APIs return `*_ALREADY_INITIALIZE` and only give one bite at the apple. Of course the state of the art's advanced a bit since Win95... :P

The rationale behind 2nd+ MddBootstrapInitialize() with compatible criteria succeeding is they're idempotent, you go the desired result and it can be awkward to ensure ThereCanBeOnlyOne(TM) solutions.

For instance, should `File.Delete(f)` succeed or fail if `f` doesn't exist? Windows' `DeleteFile` says it's `ERROR_FILE_NOT_FOUND` because you didn't find and delete the file, but other systems treat it as an success "What? You wanted it gone. It's gone..." in a "It's the destination that matters, not the journey..." sort of way.

From a general usability perspective, you asked for a result and you got it. Seems the better approach than `ERROR_ALREADY_INITIALIZED`

**Comment by asklar** [comment] 2022-03-14 22:47
Agree w/Howard. In addition, there are scenarios where you aren't in complete control of initializing winappsdk in the context of the app (e.g. libraries and other components) so using an "intents" approach makes sense.

**Comment by riverar** [comment] 2022-03-14 23:38
> For instance, should `File.Delete(f)` succeed or fail if `f` doesn't exist? Windows' `DeleteFile` says it's `ERROR_FILE_NOT_FOUND`

Both of those options fail; `File.Delete` returns false and Win32 `DeleteFile` returns `ERROR_FILE_NOT_FOUND`. Those behaviors seems to support my suggestion of not swallowing subsequent calls to Initialize.

> In addition, there are scenarios where you aren't in complete control of initializing winappsdk in the context of the app (e.g. libraries and other components) so using an "intents" approach makes sense.

Do those scenarios actually exist? I'd be interested in learning more if so. Libs calling MddBootstrapInitialize quietly behind the scenes sounds like a recipe for disaster. If the API failed on subsequent calls, it'd make it much easier for developers to detect naughty libs.

**Comment by DrusTheAxe** [comment] 2022-03-14 23:46
> Both of those options fail; `File.Delete` returns false

Sorry, I meant a conceptual DeleteSomeFile() API. I didn't mean to imply .NET or other any specific implementation

Generally libraries _should not_ call `MddBootstrapInitialize` as it alters process state (not per-thread state like `CoInitialize`)

**Closed** 2022-03-23 16:04 UTC
Labels: feature, area-DynamicDependencies
