### ISSUE TITLE
Reunion 0.8 preview templates generate reference error for Package project

### ISSUE THREAD

**Issue by pjmlp** [microsoft/WindowsAppSDK#905] opened 2021-06-03 14:59 UTC
**Describe the bug**

Visual Studio template for Reunion 0.8 preview seems to be incorrect in some way.

Getting _Project must have a reference to an application. Please add a reference under the 'Applications' node in the Solution Explorer.	App2 (Package)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets	742_ while the projects are clearly linked together.

**Steps to reproduce the bug**

1. Generate a new Project Reunion project based on the 0.8 preview template for C++/WinRT
2. Build solution

**Expected behavior**

Everything compiles properly.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/608876/120666415-db618900-c48c-11eb-8d56-3ae6ec259723.png)

**Version Info**
0.8-Preview

NuGet package version: 
0.8.0-preview

**Comment by andrewleader** [comment] 2021-06-03 19:17
Hey @aeloros, can you look into this?

**Comment by aeloros** [comment] 2021-06-03 21:17
yup

**Comment by aeloros** [comment] 2021-06-03 23:48
@pjmlp I'm unable to reproduce the problem you're seeing.  Here is a snip of my screen showing the successful build and the version of VS I'm using.

![image](https://user-images.githubusercontent.com/20483794/120725695-65a8ed80-c48b-11eb-8351-fc107a498e80.png)

This is the project I chose for testing purposes.

![image](https://user-images.githubusercontent.com/20483794/120725755-807b6200-c48b-11eb-86b4-ec72219ed452.png)

In your repro what project are you using, and version of VS?

Thanks
--Scott

**Comment by pjmlp** [comment] 2021-06-04 06:49
@aeloros 

Just reproduced it, however the error is not on the template as I thought.

Rather when the project is fully created, we get the Visual Studio as shown below.

![grafik](https://user-images.githubusercontent.com/608876/120753387-684b2780-c50b-11eb-99d3-b85bc504892a.png)

When closing the package overview, we get asked if we want to save, which is kind of odd as nothing was changed.

![grafik](https://user-images.githubusercontent.com/608876/120753546-9d577a00-c50b-11eb-83b5-a7e11e680648.png)

However apparently it was, and not saving will produce a corrupt packing project, as _EntryPointProjectUniqueName_ won't be present on the project file.

I am also attaching the build log and generatd project.

I guess the bug would be not to have such change take place as many developers would do what I did and press _"Don't Save"_ without realising the consequences.

[App5.zip](https://github.com/microsoft/ProjectReunion/files/6596299/App5.zip)

[Output.log](https://github.com/microsoft/ProjectReunion/files/6596135/Output.log)

**Comment by aeloros** [comment] 2021-06-04 21:31
If you manually hit save later does it fix it, or are the changes lost somehow after these actions?

**Comment by aeloros** [comment] 2021-06-04 21:40
Nevermind, I was able to repro the problem now.  Hitting 'Save All' afterward does not fix the build error. :(

**Comment by aeloros** [comment] 2021-09-09 23:12
Closing this issue as it isn't Windows App SDK related and now has internal tracking.

**Closed by aeloros** 2021-09-09 23:12 UTC
Labels: bug, area-Developer tools
