### ISSUE TITLE
Empty .net Maui deployed as msix package cannot be uninstalled with error 0x80073cfa

### ISSUE THREAD

**Issue by nefen** [microsoft/WindowsAppSDK#4885] opened 2024-11-14 18:02 UTC
### Describe the bug

I use a laptop for development:
Device name	DESKTOP-IG7JGPU
Processor	Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz   2.59 GHz
Installed RAM	16,0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

with Win10 Pro:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎4/‎11/‎2024
OS build	19045.5131
Experience	Windows Feature Experience Pack 1000.19060.1000.0

Visual Studio:
Microsoft Visual Studio Community 2022
Version 17.12.0
VisualStudio.17.Release/17.12.0+35506.116
Microsoft .NET Framework
Version 4.8.09037

Xamarin   17.12.0.153 (d17-12@1d0906d)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.12.3.17 (remotes/origin/main@0912a005b9)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

The first time the MSIX package is deployed, but then it cannot be uninstalled and no other attempt to debug works.
The MauiApp1 exits with code 0x80073cf9

### Steps to reproduce the bug

1. Create a .net Maui Empty project (standard or Blazor hybrid)
2. make sure that packaged deployment is enabled (in my installation this is the default)
3. Debug the app on Windows Machine.
4. Exit the app
5. Try to debug again.
6. The app will not run and exits with error 0x80073cf9
7.  If I try to uninstall the previous version from "Add & Remove Apps", I get error 0x80073cfa

### NuGet package version

None

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by RDMacLachlan** [comment] 2024-11-14 18:50
This issue is a duplicate of #4884.

**Closed by RDMacLachlan** 2024-11-14 18:50 UTC
Labels: needs-triage

**Comment by nefen** [comment] 2024-11-15 04:50
I do not understand how is this duplicate to #4884.

I am stuck with 3 installed apps that do not go away.

The good thing is that I tested the .net9 blazor maui and this works ok.

**Comment by codendone** [comment] 2024-11-26 20:14
The duplicate reference should have been to #4881.
