### ISSUE TITLE
Binding Error with the Navigation View Component

### ISSUE THREAD

**Issue by D-Naveenz** [microsoft/WindowsAppSDK#4241] opened 2024-03-01 08:57 UTC
### Describe the bug

There is a binding error with the Navigation View after upgrading the project to DotNet 8 and the latest version of WindowsAppSDK.

<code>Error: Converter failed to convert value of type 'Windows.Foundation.IReference`1<Microsoft.UI.Xaml.GridLength>' to type 'Double'; BindingExpression: Path='TemplateSettings.CompactPaneGridLength' DataItem='Microsoft.UI.Xaml.Controls.SplitView'; target element is 'Microsoft.UI.Xaml.Media.Animation.SplineDoubleKeyFrame' (Name='null'); target property is 'Value' (type 'Double')</code>

### Steps to reproduce the bug

1. Create a new WinUI 3 project using template studio
2. Change the dotnet version to 8
3. Change runtime identifiers according to the dotnet 8 requirments. <code>win-x86;win-x64;win-arm64</code>
4. Update all the nuget packages including WindowsAppSDK (to the 1.5.24)
5. Debug the project and see binding errors

### Screenshots

![Screenshot 2024-03-01 142613](https://github.com/microsoft/WindowsAppSDK/assets/55798200/af473392-c9f4-49e7-a28e-2b8f814458bc)

### NuGet package version

Windows App SDK 1.5.0: 1.5.240227000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DFX-Coding** [comment] 2024-03-01 21:02
I am experiencing the same issue with Windows 11 23H2, Visual Studio 2022 version 19.2, Windows App SDK 1.5.0: 1.5.240227000, and an unpacked WinUI 3 app.

**Comment by bpulliam** [comment] 2024-03-04 23:25
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/9392

**Closed by bpulliam** 2024-03-04 23:25 UTC
