### ISSUE TITLE
`Exception code: 0xc000027b` caused by `Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll` during application startup.

### ISSUE THREAD

**Issue by sharpninja** [microsoft/WindowsAppSDK#1020] opened 2021-07-03 12:58 UTC
**Describe the bug**

`Exception code: 0xc000027b` caused by `Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll` during application startup.

**Steps to reproduce the bug**

Pull code at: [gatewayprogrammingschool/WinRepoSearch](https://github.com/gatewayprogrammingschool/WinRepoSearch)

Start `WinRepoSearch` project.

**Expected behavior**

Application starts correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/16146732/124354813-88860900-dbd3-11eb-8d62-b57f218055ac.png)

**Version Info**

All Packages

```xml
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="7.0.3" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.0.3" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.0.3" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.3.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.0.4" />
    <PackageReference Include="YamlDotNet" Version="11.2.1" />
  </ItemGroup>
```

NuGet package version: 

`<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />`

```
Edition	Windows 11 Pro
Update	21H2
Installed on	‎6/‎29/‎2021
OS build	22000.51
Experience	Windows Feature Experience Pack 421.16300.0.3
```

**Additional context**

Event Viewer Log

```
Faulting application name: WinRepoSearch.exe, version: 1.0.0.0, time stamp: 0x60513887
Faulting module name: CoreMessagingXP.dll, version: 10.0.22386.1009, time stamp: 0x164cf1ba
Exception code: 0xc000027b
Fault offset: 0x0000000000090fec
Faulting process id: 0x2e34
Faulting application start time: 0x01d770096e84277d
Faulting application path: C:\GitHub\WinRepoSearch\WinRepoSearch (Package)\bin\x64\Debug\AppX\WinRepoSearch\WinRepoSearch.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
Report Id: a5ad73ea-11ca-4d70-b5d9-181019f65271
Faulting package full name: 784A22BD-98EB-499E-855B-737EFC87FB8E_1.0.0.0_x64__8q4myk08gpkq4
Faulting package-relative application ID: App
```

```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-07-03T12:46:27.2052961Z" /> 
  <EventRecordID>2068</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="26300" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Payton-Rog</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>WinRepoSearch.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>60513887</Data> 
  <Data>CoreMessagingXP.dll</Data> 
  <Data>10.0.22386.1009</Data> 
  <Data>164cf1ba</Data> 
  <Data>c000027b</Data> 
  <Data>0000000000090fec</Data> 
  <Data>2e34</Data> 
  <Data>01d770096e84277d</Data> 
  <Data>C:\GitHub\WinRepoSearch\WinRepoSearch (Package)\bin\x64\Debug\AppX\WinRepoSearch\WinRepoSearch.exe</Data> 
  <Data>C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll</Data> 
  <Data>a5ad73ea-11ca-4d70-b5d9-181019f65271</Data> 
  <Data>784A22BD-98EB-499E-855B-737EFC87FB8E_1.0.0.0_x64__8q4myk08gpkq4</Data> 
  <Data>App</Data> 
  </EventData>
  </Event>
```

**Comment by riverar** [comment] 2021-07-03 15:12
Two issues: You have to start the packaging project. And you're not going to get far on Windows 11 due to a known issue.  https://github.com/microsoft/WindowsAppSDK/issues/998

**Comment by asklar** [comment] 2021-07-05 00:49
Duplicate of #992

**Closed by asklar** 2021-07-05 00:49 UTC

**Comment by diemperdiem** [comment] 2023-03-21 21:50
> **Describe the bug**
> 
> `Exception code: 0xc000027b` caused by `Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll` during application startup.
> 
> **Steps to reproduce the bug**
> 
> Pull code at: [gatewayprogrammingschool/WinRepoSearch](https://github.com/gatewayprogrammingschool/WinRepoSearch)
> 
> Start `WinRepoSearch` project.
> 
> **Expected behavior**
> 
> Application starts correctly.
> 
> **Screenshots**
> 
> ![image](https://user-images.githubusercontent.com/16146732/124354813-88860900-dbd3-11eb-8d62-b57f218055ac.png)
> 
> **Version Info**
> 
> All Packages
> 
> ```
>   <ItemGroup>
>     <PackageReference Include="CommunityToolkit.Mvvm" Version="7.0.3" />
>     <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.0.3" />
>     <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.0.3" />
>     <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.3.0" />
>     <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.3.0" />
>     <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
>     <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
>     <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.0.4" />
>     <PackageReference Include="YamlDotNet" Version="11.2.1" />
>   </ItemGroup>
> ```
> 
> NuGet package version:
> 
> `<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />`
> 
> ```
> Edition	Windows 11 Pro
> Update	21H2
> Installed on	‎6/‎29/‎2021
> OS build	22000.51
> Experience	Windows Feature Experience Pack 421.16300.0.3
> ```
> 
> **Additional context**
> 
> Event Viewer Log
> 
> ```
> Faulting application name: WinRepoSearch.exe, version: 1.0.0.0, time stamp: 0x60513887
> Faulting module name: CoreMessagingXP.dll, version: 10.0.22386.1009, time stamp: 0x164cf1ba
> Exception code: 0xc000027b
> Fault offset: 0x0000000000090fec
> Faulting process id: 0x2e34
> Faulting application start time: 0x01d770096e84277d
> Faulting application path: C:\GitHub\WinRepoSearch\WinRepoSearch (Package)\bin\x64\Debug\AppX\WinRepoSearch\WinRepoSearch.exe
> Faulting module path: C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
> Report Id: a5ad73ea-11ca-4d70-b5d9-181019f65271
> Faulting package full name: 784A22BD-98EB-499E-855B-737EFC87FB8E_1.0.0.0_x64__8q4myk08gpkq4
> Faulting package-relative application ID: App
> ```
> 
> ```
> - <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
> - <System>
>   <Provider Name="Application Error" /> 
>   <EventID Qualifiers="0">1000</EventID> 
>   <Version>0</Version> 
>   <Level>2</Level> 
>   <Task>100</Task> 
>   <Opcode>0</Opcode> 
>   <Keywords>0x80000000000000</Keywords> 
>   <TimeCreated SystemTime="2021-07-03T12:46:27.2052961Z" /> 
>   <EventRecordID>2068</EventRecordID> 
>   <Correlation /> 
>   <Execution ProcessID="26300" ThreadID="0" /> 
>   <Channel>Application</Channel> 
>   <Computer>Payton-Rog</Computer> 
>   <Security /> 
>   </System>
> - <EventData>
>   <Data>WinRepoSearch.exe</Data> 
>   <Data>1.0.0.0</Data> 
>   <Data>60513887</Data> 
>   <Data>CoreMessagingXP.dll</Data> 
>   <Data>10.0.22386.1009</Data> 
>   <Data>164cf1ba</Data> 
>   <Data>c000027b</Data> 
>   <Data>0000000000090fec</Data> 
>   <Data>2e34</Data> 
>   <Data>01d770096e84277d</Data> 
>   <Data>C:\GitHub\WinRepoSearch\WinRepoSearch (Package)\bin\x64\Debug\AppX\WinRepoSearch\WinRepoSearch.exe</Data> 
>   <Data>C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8000.167.1906.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll</Data> 
>   <Data>a5ad73ea-11ca-4d70-b5d9-181019f65271</Data> 
>   <Data>784A22BD-98EB-499E-855B-737EFC87FB8E_1.0.0.0_x64__8q4myk08gpkq4</Data> 
>   <Data>App</Data> 
>   </EventData>
>   </Event>
> ```

Where you able to fix this?
