### ISSUE TITLE
[Packaged App]`co_await` does't return to ui thread. when the call `PickSingleFolderAsync` is completed

### ISSUE THREAD

**Issue by shelllet** [microsoft/WindowsAppSDK#1782] opened 2021-11-12 02:18 UTC
### Describe the bug

Internal bug https://task.ms/37013204

windowsappsdk preivew-3:
`StorageFolder folder = co_await picker.PickSingleFolderAsync();`

at this point

call `DependencyObject::SetValue`  throw errors.

`The application called an interface that was marshalled for a different thread`
//

### Steps to reproduce the bug

1.  Create c++ package app by windowsappsdk.

2. Call `FolderPicker` to  open select folder dialog on button clicked event.

3. then DependencyObject::SetValue

### Expected behavior

before windowsappsdk preview-3

c++/winrt will restore to ui thread automatically.

why preview-3 change this ？

### Screenshots

![image](https://user-images.githubusercontent.com/16729017/141397605-20c522a9-9c39-4892-baf0-aaaf4831ba1c.png)

### NuGet package version

1.0.0-preview3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

### Additional context

to avoid me bebing wrong, I recreate an empty pacakged project and test .

![image](https://user-images.githubusercontent.com/16729017/141739780-e0b1f477-ba24-43aa-8ad5-179b42e8d566.png)

![image](https://user-images.githubusercontent.com/16729017/141739887-1711cfd6-8713-4685-aa0d-dda30610d1a9.png)

unpackaged app:
![image](https://user-images.githubusercontent.com/16729017/141740160-d137e7da-d158-42e9-95e1-8cf2a722b390.png)

**Comment by andrewleader** [comment] 2021-11-15 18:44
@BenJKuhn @Scottj1s would this co_await issue be either of your areas of expertise? It sounds like in Preview 3 we possibly regressed the behavior of co_await in C++ apps and it doesn't return back to the UI thread anymore?

**Comment by andrewleader** [comment] 2021-11-16 15:32
@BenJKuhn this looks like a dupe of https://microsoft.visualstudio.com/OS/_workitems/edit/37013204 which @MikeHillberg is assigned to. @MikeHillberg is this indeed a dupe of your `co_await` bug?

**Comment by BenJKuhn** [comment] 2022-08-26 18:16
This was fixed some time ago (in 1.0, I believe), but the public issue never got closed out. Just cleaning up books.

**Closed by BenJKuhn** 2022-08-26 18:16 UTC
Labels: bug, v1.0.0-preview3, servicing-consider-1.0
