### ISSUE TITLE
IsMaximizable Ignored When Content Extends into Title Bar

### ISSUE THREAD

**Issue by jamespack** [microsoft/WindowsAppSDK#3465] opened 2023-02-27 01:28 UTC
### Describe the bug

AppWindow::Presenter::IsMaximizable is ignored when MainWindow::ExtendsContentIntoTitleBar(true);

<img width="293" alt="image" src="https://user-images.githubusercontent.com/2086722/221451157-a66f2a52-cd9f-492a-b2f3-402686a4aaac.png">

<img width="239" alt="image" src="https://user-images.githubusercontent.com/2086722/221451267-4d5b1045-403c-4831-be42-36d0eacfe9a8.png">

### Steps to reproduce the bug

1. New Blank WinUI 3 Project
2. MainWindow::ExtendsContentIntoTitleBar(true)
3. Get the AppWindow using <winrt/Microsoft.UI.Interop.h>
4. Get the AppWindow::Presenter
5. Set Presenter::IsMaximizable(false);

### Expected behavior

The maximize button should be disabled the same as when the content is not extended into the title bar.

### Screenshots

See above

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by sotanakamura** [comment] 2023-02-27 13:14
Could you share your code to reproduce the bug?

**Comment by jamespack** [comment] 2023-02-27 15:44
Yep. Give me a few mins. I'll push a branch and link it here.

**Comment by jamespack** [comment] 2023-02-27 16:14
Here you go.

https://github.com/jamespack/IsMaximizableBug

**Comment by sotanakamura** [comment] 2023-02-28 03:40
I cannot resolve the  bug, but I will share information related to AppWindow.
https://github.com/microsoft/microsoft-ui-xaml/issues/7628
https://github.com/microsoft/microsoft-ui-xaml/issues/8201

**Comment by jamespack** [comment] 2023-03-02 02:20
Thanks for the material. I was able to get it working by setting an empty custom titlebar and setting its ExtendsContentIntoTitleBar property to true. Thats a hack though. Id still say this is a bug unless the intention is to remove this api at some point in favor of the AppWIndow api.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/2086722/222314211-de2ba3cc-ee2d-4a8f-bba9-81c5d12d586a.png">

**Comment by jamespack** [comment] 2023-03-02 02:21
With a hopefully improved AppWindow API :)

**Comment by peterjtan** [comment] 2023-03-15 01:40
Unfortunately, there are 2 different "ExtendsContentIntoTitleBar" right now:
- WinUI 3's custom title bar in Microsoft.UI.Xaml.Window class
- AppWindow's custom title bar in Microsoft.UI.Windowing.AppWindowTitleBar

Since the `IsMaximizable` property is set on an AppWindow presenter, you would need to use `appWindow.TitleBar().ExtendsContentIntoTitleBar(true);` for it to function properly. 

We might look into merging some of these title bar customization options in the future, so that the API surface is easier to use and unambiguous.

**Comment by jamespack** [comment] 2023-03-16 14:34
The entire window/title bar api is kind of messy. I know it's still relatively early. So hoping that improved over time. Over all super excited about Windows Apps and the future for windows devs!

**Comment by dotMorten** [comment] 2023-10-16 06:03
I hit the same and had [a user report this](https://github.com/dotMorten/WinUIEx/issues/142) in WinUIEx as well. The `IsMinimizable` and `IsMaximixable` does gray out the buttons, but they are still fully interactive.

**Comment by HO-COOH** [comment] 2024-04-30 08:59
> Unfortunately, there are 2 different "ExtendsContentIntoTitleBar" right now:
> 
> * WinUI 3's custom title bar in Microsoft.UI.Xaml.Window class
> * AppWindow's custom title bar in Microsoft.UI.Windowing.AppWindowTitleBar
> 
> Since the `IsMaximizable` property is set on an AppWindow presenter, you would need to use `appWindow.TitleBar().ExtendsContentIntoTitleBar(true);` for it to function properly.

Thanks for saving my life.

**Comment by codendone** [comment] 2024-06-06 16:02
Closing this as duplicate. microsoft/microsoft-ui-xaml#8666 looks like a direct duplicate which we have an internal tracking issue for.

**Closed by codendone** 2024-06-06 16:02 UTC
Labels: bug, area-Windowing
