### ISSUE TITLE
Update productboard to be consistent with 1.1 roadmap announcement

### ISSUE THREAD

**Issue by Samuel12321** [microsoft/WindowsAppSDK#2326] opened 2022-03-28 22:03 UTC
In the [roadmap](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/roadmap.md) published 2 weeks ago it was announced that background acrylic would be part of the 1.1 release, this is not reflected on [productboard ](https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/2-planned) where [background acrylic](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/28-background-acrylic) is still listed as under consideration.

Please update productboard to be consistent with 1.1 roadmap announcement so as not to confuse people by telling them different things in different places.

**Comment by riverar** [comment] 2022-03-28 22:27
Dupe of https://github.com/microsoft/WindowsAppSDK/issues/2271

**Comment by Samuel12321** [comment] 2022-03-29 00:26
yep, didn't see that one
seems they said they fixed it when in fact they didn't

**Comment by btueffers** [comment] 2022-03-31 23:10
Thank you @Samuel12321 and @riverar. Acrylic as been moved in productboard.

**Closed** 2022-03-31 23:12 UTC
