### ISSUE TITLE
`ResourceLoader` doesn't honor `ApplicationLanguages.PrimaryLanguageOverride`

### ISSUE THREAD

**Issue by nxtn-staged** [microsoft/WindowsAppSDK#2806] opened 2022-08-02 06:27 UTC
### Describe the bug

`ResourceManager` uses the app's preferred language, but `ResourceLoader` uses Windows display language.

### Steps to reproduce the bug

*App.xaml.cs*

```cs
using Microsoft.UI.Xaml;

namespace Test.WinUI
{
    public partial class App : Application
    {
        public App()
        {
            this.InitializeComponent();
        }

        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
            // Windows display language is en-US.
            Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = "de-DE";

            var rm = new Microsoft.Windows.ApplicationModel.Resources.ResourceManager();
            var rc = rm.MainResourceMap.GetValue("Resources/Text");
            var expected = rc.ValueAsString; // in de-DE

            var rl = new Microsoft.Windows.ApplicationModel.Resources.ResourceLoader();
            var actual = rl.GetString("Text"); // in en-US
        }
    }
}
```

### Expected behavior

`Microsoft.Windows.ApplicationModel.Resources.ResourceLoader.GetString` should use the app's preferred language.

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

A workaround is to use `Windows.ApplicationModel.Resources.ResourceLoader.GetString` instead.

**Comment by AndrewKeepCoding** [comment] 2022-08-02 07:55
I'm not sure why (couldn't find any good documentation about this) but instead of creating a **new** instance of the ``ResourceLoader``, you should get it using the static ``GetForViewIndependentUse()`` method.

```csharp
var rl = Windows.ApplicationModel.Resources.ResourceLoader.GetForViewIndependentUse();
```

**Comment by nxtn-staged** [comment] 2022-08-02 08:36
I intend to use the MRT Core version of `ResourceLoader` that doesn't have a `GetForViewIndependentUse` method.

I'm now using a persistent `ResourceContext` to mimic `GetForViewIndependentUse`, which I think should be the default behavior for `M.W.AM.R.ResourceLoader`.

```cs
using Microsoft.UI.Xaml;
using Microsoft.Windows.ApplicationModel.Resources;

namespace Test.WinUI
{
    public partial class App : Application
    {
        private static readonly ResourceManager resourceManager = new();
        private static readonly ResourceMap resourceMap = resourceManager.MainResourceMap.GetSubtree("Resources");
        private static readonly ResourceContext resourceContext = resourceManager.CreateResourceContext();

        public App()
        {
            this.InitializeComponent();
        }

        internal static string GetResourceString(string resource)
        {
            return resourceMap.GetValue(resource, resourceContext).ValueAsString;
        }
    }
}

**Comment by riverar** [comment] 2022-08-02 23:51
Related (but not a duplicate of) #1687

**Comment by axelandrejs** [comment] 2022-08-11 21:42
This should be addressed by https://github.com/microsoft/WindowsAppSDK/pull/2559. Can you try the scenario in the 1.2 experimental release and see if it works now?

**Closed by axelandrejs** 2022-08-11 21:42 UTC
Labels: bug, area-MRTCore
