### ISSUE TITLE
FileOpenPicker crashes on call to method `PickSingleFileAsync()`, if there are no FileTypeFilters

### ISSUE THREAD

**Issue by Shailosingh** [microsoft/WindowsAppSDK#2931] opened 2022-09-03 04:03 UTC
### Describe the bug

In my C# WinUI 3 project, if I try to use a FileOpenPicker without any FileTypeFilters, it causes exception: 
`System.Runtime.InteropServices.COMException: 'Error HRESULT E_FAIL has been returned from a call to a COM component.'`

### Steps to reproduce the bug

1. Create a C# WinUI 3 Packaged Desktop Project
2. In MainWindow.xaml.cs, add the following field to the MainWindow class:
`public static MainWindow CurrentInstance;`
3. In the constructor, put the following line so, other pages can access the window class and its handle:
`CurrentInstance = this;`
4. Create a button and put the following code in the button click handler:
```
//Get the window handle
IntPtr hwnd = WinRT.Interop.WindowNative.GetWindowHandle(MainWindow.CurrentInstance);

//Initialize the file picker
FileOpenPicker openPicker = new FileOpenPicker();
WinRT.Interop.InitializeWithWindow.Initialize(openPicker, hwnd);
openPicker.ViewMode = PickerViewMode.List;
openPicker.CommitButtonText = "Select File";
openPicker.SettingsIdentifier = "Select File To Be Split";

//Get file
StorageFile file = await openPicker.PickSingleFileAsync();
if (file != null)
{
    FileDirectoryBox.Text = file.Path;
}

else
{
    StatusBox.Text = "File select failed!";
}
```
5. Click the button, thus invoking the click handler. 
6. The app will throw the exception at `StorageFile file = await openPicker.PickSingleFileAsync();`

### Expected behavior

I should be able to use the FileOpenPicker without applying a FileTypeFilter. In most cases, I am willing to accept any files (no need for filters) and it is very strange that it throws such a cryptic exception when I simply don't specify a filter.

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

The workaround for this bug is applying the following filter:

`openPicker.FileTypeFilter.Add("*");`

This will allow the FileOpenPicker to work without any issues. However, I shouldn't need to add a line like this to simply not have filters. 

What is stranger is that supposedly, on Windows 11, this bug does not exist https://github.com/microsoft/WindowsAppSDK/issues/1188#issuecomment-1066261574. According to this comment, it works on Windows 11 but, will throw an exception similar to mine on Windows 10 specifically, unless I add a filter.

**Comment by roxk** [comment] 2022-09-07 13:45
Just tested and the API also works this way in windows 11 in UWP. The [doc](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.filetypefilter?view=winrt-22621#windows-storage-pickers-fileopenpicker-filetypefilter) also has an example of applying the `*` filter, which seems to indicate this is working as intended.

**Comment by gabbybilka** [comment] 2022-09-16 16:53
This looks like existing behavior of the API outside of WinAppSDK, closing as external.

**Closed by gabbybilka** 2022-09-16 16:53 UTC

**Comment by Smileher** [comment] 2022-09-19 06:28
> Just tested and the API also works this way in windows 11 in UWP. The [doc](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.fileopenpicker.filetypefilter?view=winrt-22621#windows-storage-pickers-fileopenpicker-filetypefilter) also has an example of applying the `*` filter, which seems to indicate this is working as intended.

I also tested this problem on Windows10 21H2. In any case, if I use the await openPicker.PickSingleFileAsync() method, I must set openPicker.FileTypeFilter.Add("*") so that it will not be abnormal; if it is on a Windows11 system, there is no need to add the following In other words, the reason is probably that the default value of FileTypeFilter is set to "*" on Windows 11, but not on Windows 10. I think it should be unified in the two systems, which is a problem that needs to be solved.

**Comment by Smileher** [comment] 2022-09-19 06:35
> This looks like existing behavior of the API outside of WinAppSDK, closing as external.



> This looks like existing behavior of the API outside of WinAppSDK, closing as external.

This looks like  a problem within the API of WinAppSDK. The performance is not uniform on Windows 10 and 11. On Windows 10, I need to add "*" to the FileTypeFilter, but not on Windows 11. It should be added by default on Windows 11. *. I think there needs to be unity on Windows 11 and on Windows 10.
这看起来是WinAppSDK的API里的问题，Windows10和11上表现不统一，在Windiows10上，我需要将FileTypeFilter添加 "*"，而在Windows11上则不需要，应该是Windows11上默认增加了*。我认为在Windows11上和Windows10上需要保持统一。
