### ISSUE TITLE
NETSDK1206 warning for .NET 8

### ISSUE THREAD

**Issue by smaillet** [microsoft/WindowsAppSDK#4597] opened 2024-07-23 23:46 UTC
### Describe the bug

When targeting .NET 8 I get the following waning:

`C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.`

Only way to get around this is if the Windows App SDK is updated to support the new RID scheme for .NET. (Yeah, another one... [sigh...])

### Steps to reproduce the bug

* Update an existing project to .NET 8.0
* Update Microsoft.WindowsAppSDK to version 1.5.240627000
* Build
* Get warning...

### Expected behavior

No warning and library works properly with .NET 8

### NuGet package version

Windows App SDK 1.5.5: 1.5.240627000

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Microsoft official docs have a "workaround" that simply silences the warning - but that is a dangerous thing as it hides ALL other cases of this error and may not even be valid for this one. (One needs to test to be sure there isn't an issue with not locating assets and it isn't obvious what specific things testing should focus on.

**Comment by whiskhub** [comment] 2024-07-28 19:55
Can reproduce with following steps:

* Create new "Blank App, packaged" WinUI 3 solution in Visual Studio 2022
* Right click on the solution and Add -> New Project
* Add new "Class Library" WinUI 3 project to the solution
* Build the solution

**Comment by whiskhub** [comment] 2024-09-06 17:48
This seems to be fixed in WinAppSDK 1.6 stable.

**Closed** 2024-09-30 20:05 UTC
Labels: area-dotnet, Status: Fixed, fix-released
