### ISSUE TITLE
Documentation for adding Windows App SDK to an existing project skips necessary steps.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/WindowsAppSDK#2675] opened 2022-06-24 19:57 UTC
### Describe the bug

[Adding Windows App SDK to an existing project](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project) does not mention steps that, if not done, will cause the project to crash, either ar runtime, or at compile time.

These are
  1. CppWinrt needs to be installed.
  2. Adding a `PackageDependency` to the framework package.

### Steps to reproduce the bug

N/A

### Expected behavior

I could hand the document to someone who knows nothing about Windows App SDK and they could add Windows App SDK to their app with no issues.

**Comment by stevewhims** [comment] 2022-07-06 23:45
Let's use https://github.com/MicrosoftDocs/windows-uwp/issues/3922. This is a dupe of that.

**Closed** 2022-07-07 17:54 UTC
Labels: needs-triage :mag:
