### ISSUE TITLE
[uwp] Frame.Navigate( typeof(non_xaml_class_derived_from_Page)) crashes w/ Native Toolchain

### ISSUE THREAD

**Issue by baskren** [microsoft/WindowsAppSDK#1743] opened 2021-11-06 15:45 UTC
### Describe the bug

When given a Non-XAML (pure code) class derived from Page, Frame.Navigate crashes when compiled using Native Toolchain.

## USING SAMPLE PROJECT 

1. Clone the following repo: https://github.com/baskren/NativeToolchain_NonXamlPage_crash.git
2. Run in **Debug** WITHOUT **Native Toolchain**
3. Click **NOT A XAML PAGE** button to navigate from **XAML PAGE** to **NOT A XAML PAGE**, successfully
4. Run in **Debug** WITH **Native Toolchain** or run in **Release**
5. Click **NOT A XAML PAGE** button to crash app.

## FROM SCRATCH
1. Create a new UWP App
2. Create a new class file, named **NoXaml.cs** and derive the class **NoXaml** from Windows.UI.Xaml.Controls.Page
3. Add `[Windows.UI.Xaml.Data.Bindable]` attribute to the **NoXaml** class
4. In App.xaml.cs, replace `rootFrame.Navigate(typeof(MainPage), e.Arguments);` with `rootFrame.Navigate(typeof(NoXaml), e.Arguments);`
5. In the project's options, enable the **Native Toolchain**
6. Build, run, watch crash

### Expected behavior

Frame.Navigate works with Non-XAML Pages.

### Screenshots

![image](https://user-images.githubusercontent.com/2528888/140615319-8a00c395-f7cb-456e-bd66-b8e13944e33f.png)

### IDE

Visual Studio 2019

### Project type

- [X] Packaged
- [X] Unpackaged

### Windows version

May 2021 Update (19043)

### Additional context

Note: recommendation from https://github.com/microsoft/microsoft-ui-xaml/issues/1949 was applied

**Comment by asklar** [comment] 2021-11-07 17:09
Duplicate of microsoft/microsoft-ui-xaml#6250

**Closed by asklar** 2021-11-07 17:09 UTC
