### ISSUE TITLE
RoGetActivationFactoryDetour not supporting re-entrance

### ISSUE THREAD

**Issue by ShashankNay** [microsoft/WindowsAppSDK#1523] opened 2021-10-01 21:24 UTC
**Describe the bug**

>	
Microsoft.WindowsAppRuntime.dll!RoGetActivationFactoryDetour does not support re-entrance, may need to use std::recursive_mutex instead of std::mutex to allow access when called recursively. 

**Steps to reproduce the bug**

1.  Run XCG Unpackaged with debug configuration

**Expected behavior**

XamlControlsGallery should be running normally. 

NuGet package version: 

WASDK 1.0.0-20210929.0-CI, modified to include Bootstrap targets.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
Version	10.0.19043 Build 19043

**Comment by riverar** [comment] 2021-10-03 05:18
Appears to be a duplicate of  #1277, related discussion #1246

**Comment by btueffers** [comment] 2021-10-04 19:22
@ShashankNay this appears to be a duplicate of https://github.com/microsoft/WindowsAppSDK/issues/1277 I'll close this issue since this has less activity.

**Closed by btueffers** 2021-10-04 19:22 UTC
Labels: needs-triage :mag:
