### ISSUE TITLE
WindowsAppRuntimeInstall.exe works incorrectly

### ISSUE THREAD

**Issue by Woopsalla** [microsoft/WindowsAppSDK#3166] opened 2022-11-21 10:36 UTC
### Describe the bug

The Bootstrap DLL requests a specific version (Major+Minor) of the SDK runtime for an application. Therefore, different runtime versions must be installable in parallel on a target computer, because different applications can of course require different runtime versions. However, the current runtime installer does not support this correctly.

Example A (x64):
Precondition: no runtime installed on the system
Step 1: Installer v1.1.5 is executed.
Step 2: Installer v1.2.221116.1 is executed.
Result: Installer v1.2.221116.1 deletes the singleton package that was installed by Installer v1.1.5. Only the singleton package from installer v1.2.221116.1 is left on the system. All other packages are correctly present in both versions.
Note: Since I may not have fully understood the function of the Singleton package, this example may not be an error. Then an explanation would be useful in a suitable place.

Example B (x64):
Precondition: no runtime installed on the system
Step 1: Installer v1.2.221116.1 is executed.
Step 2: Installer v1.1.5 is executed. 
Result: During the installation of the Singleton package in step 2, the following error occurs:
"ErrorMessage: Windows cannot install package MicrosoftCorporationII.WinAppRuntime.Singleton_1005.616.1651.0_x64__8wekyb3d8bbwe because it has version 1005.616.1651.0. A higher version 2000.684.1510.0 of this package is already installed.One or more install operations failed. Result: 0x80073d06" 
The further installation is aborted and missing packages are not installed, among others the DDLM packages which are important for the enumeration by the Bootstrap DLL. Thus, an application that requires runtime version v1.1.5 cannot be executed in this case.

### Steps to reproduce the bug

see above

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment] 2022-11-22 18:39
@DrusTheAxe

**Comment by DrusTheAxe** [comment] 2022-11-22 19:07
>Result: Installer v1.2.221116.1 deletes the singleton package that was installed by Installer v1.1.5. Only the singleton package from installer v1.2.221116.1 is left on the system. All other packages are correctly present in both versions.

Correct. Each major.minor has its own fwk+main packages. The singleton is different there being 1 for all versions (or at least all 1.x versions. TBD if there's 1 singleton for all versions or 1 per major release). To achieve this the singleton package has no version in its package family name i.e. it's how folks usually name their packages :-)

>Result: During the installation of the Singleton package in step 2, the following error occurs:
"ErrorMessage: Windows cannot install package MicrosoftCorporationII.WinAppRuntime.Singleton_1005.616.1651.0_x64__8wekyb3d8bbwe because it has version 1005.616.1651.0. A higher version 2000.684.1510.0 of this package is already installed.One or more install operations failed. Result: 0x80073d06"

That's a bug

0x80073d06 == ERROR_INSTALL_PACKAGE_DOWNGRADE. The newer singleton (v1.2.*) is designed to work for all previous versions so then installing 1.1.* it shouldn't try to install the older (1.1) singleton. Net result should be Fwk=1.1+1.2, Main=1.1+1.2, Singleton=1.2

This is a bug in the 1.1 installer (and maybe 1.0?)

@sachintaMSFT tag you're it

@MikeHillberg heads up this is worthy of servicing

**Comment by ssparach** [comment] 2024-10-25 21:54
The issue is no longer reproducible in latest installer versions and has been fixed with code present inside https://github.com/microsoft/WindowsAppSDK/blob/main/installer/dev/install.cpp.

**Closed by ssparach** 2024-10-25 21:54 UTC
Labels: bug, area-Installer, fix-released
