### ISSUE TITLE
Proposal: FileTypeAssociation/ context menus: context menus support for FileTypeAssociation where the app is not default for the file typ

### ISSUE THREAD

**Issue by mfe-** [microsoft/WindowsAppSDK#56] opened 2020-05-31 08:45 UTC
# Proposal: FileTypeAssociation/ context menus: context menus support for FileTypeAssociation where the app is not default for the file typ

## Summary
the integration into the windows explorer context menu ist much easier for uwp apps compared to regular win32 apps. However, UWP apps should have the capability to add context menu items even the app is not the default for the selected file type(s).
UWP apps should also have capability to prompt a user dialog where the user can allow or deny the installation of those context menu items. This way the user does not need to set the app as default for the related file types. 

## Rationale

The integration into the context menu of the windows explorer for UWP apps is much easier than for “regular” win32 apps. The integration can be done with the FileTypeAssociation extension in the app capability declarations. 

```xml
<uap:Extension Category="windows.fileTypeAssociation">
      <uap3:FileTypeAssociation Name="bla" >
        <uap2:SupportedVerbs>
          <uap3:Verb Id="Resize" Extended="false" MultiSelectModel="Player">Resize</uap3:Verb>
          <uap3:Verb Id="Edit1" Extended="false" MultiSelectModel="Player">Edit1</uap3:Verb>
        </uap2:SupportedVerbs>
        <uap:SupportedFileTypes>
          <uap:FileType>.jpg</uap:FileType>
          <uap:FileType>.txt</uap:FileType>
          <uap:FileType>.banana</uap:FileType>
          <uap:FileType>.foo</uap:FileType>
        </uap:SupportedFileTypes>
      </uap3:FileTypeAssociation>
    </uap:Extension>
```
The downside of this capability is, the context menu items will only be shown when the app is the default for the selected file type(s).
![image](https://user-images.githubusercontent.com/3492683/83348025-78915b00-a329-11ea-92aa-1f697348fc25.png)

I think the term global context menu can be used in Windows 10 if we are referring to the windows explorer context menu. See sample picture below. I’m not familiar with Windows 10X but the global context menu will hopefully appear somewhere else, since there is no classic windows explorer.
![image](https://user-images.githubusercontent.com/3492683/83348037-82b35980-a329-11ea-84c2-690882b29d90.png)

Imagine the following scenarios with the current restrictions.
* Scenario one: 
A UWP app for resizing images can only add an entry to the global context menu for .jpgs if it is the default app for opening .jpgs. The resize app itself does not support displaying images. For the user it does not make sense to set the resizing image app as the default for the file typ .jpg, as the user still wants to open the images with a picture viewer app. On the other hand, it should be possible to call the resize functionality from within the windows explorer by calling the context menu item “resize” on the selected file(s). 
* Scenario two: 
A developer wants to create a compression tool, and therefore has the requirement to display the option to compress a file in the context menu. In order to accomplish this with the current re-strictions, the user would need to set the compression app as default for every filetype. Which makes no sense since the user still wants to open e.g docx files with Word and not with the compres-sion tool.
* Win32 apps (and Fulltrustedapps?) do not have this restriction because the installer can make the necessary changes in the registry to deal with Scenario one and two. But Win32 apps could benefit from this capability as well, since the installer doesn’t need to deal with the context menu entries.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Allow developers to add context menu entries to the “global” context menu even when the app is not the default app.  | Must |
| UWP apps should also have the capability to prompt a user dialog where the user can allow or deny the installation of those context menu items | Must |
| End customer benefit from a more user friendly integration of the app with windows | |

## Important Notes

API Proposal for:
UWP apps should also have the capability to prompt a user dialog where the user can allow or deny the installation of those context menu items

Request by code:
`await Windows.FileTypeAssociation.RequestAddingContextMenu(string[] entries, string filetyps)`
Or maybe the parameter entries are not necessary as this information could be taken from the apps capability declarations.

`await Windows.FileTypeAssociation.RequestAddingContextMenu()`

![image](https://user-images.githubusercontent.com/3492683/83348052-9fe82800-a329-11ea-8670-e93f83e464b8.png)

## Related links

- https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-filetypeassociation
- https://docs.microsoft.com/en-US/windows/uwp/packaging/app-capability-declarations
- https://stackoverflow.com/questions/50664134/how-integrate-uwp-app-into-context-menu-of-windows-explorer-for-jpg

**Comment by Poopooracoocoo** [comment] 2020-09-12 08:05
paint 3d is uninstalled but still shows up in the file explorer context menus. yuck. looks like its handled by the file explorer

**Comment by stevewri** [comment] 2020-12-03 20:30
@andreww-msft - this looks like a variant or dupe of another file association/type Reunion request you already have. Can you take a look and close as dupe or merge?

**Comment by andreww-msft** [comment] 2020-12-10 00:36
Yes, we do have filetype association registration as part of AppLifecycle. The initial release will be very simple. I'll keep this open for now, as it has some useful additional context that we can include for consideration in a later version of AppLifecycle.

**Comment by andreww-msft** [comment] 2022-01-04 21:18
Thanks for the proposal. I've added this to the backlog for the Shell team to consider for a possible future release. Internal ID is 37597964.

**Closed by andreww-msft** 2022-01-04 21:18 UTC
Labels: feature proposal, needs-attention :wave:, area-Shell UX
