### ISSUE TITLE
Single project msix can't load assets from project reference

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/WindowsAppSDK#1691] opened 2021-10-30 20:45 UTC
**Describe the bug**
Single project msix can't load assets from project reference, including XBF and images.

**Steps to reproduce the bug**

1. Create a single project WinUI project, do some necessary modification, and verify it works.
2. Create a class library project, with a UserControl in it. Do necessary modification to make it builds.
3. Add the user control to main window. Build and run the app.
4. Throws XamlParseException that can't load XBF for the UserControl.

**Expected behavior**
Runs without exception.

**Version Info**

NuGet package version: 
[Microsoft.WindowsAppSDK 1.0.0-preview3]

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 19043             | Yes   |

**Additional context**
It's not specific for XBF. Asset images from class library project don't load neither.
It reproduces on platform-ed and AnyCPU (with workaround) class library.

**Comment by evelynwu-msft** [comment] 2021-11-01 19:47
Duplicate of internal bug http://task.ms/36600654 which is assigned to @ryalanms.

**Comment by andrewleader** [comment] 2021-11-11 00:39
Closing as we've fixed this in the upcoming 1.0 GA release!

**Closed by andrewleader** 2021-11-11 00:39 UTC
Labels: bug, area-Developer tools
