### ISSUE TITLE
[Unpackaged] - Improve error when bootstrapper cannot find default WindowsAppRuntime framework

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/WindowsAppSDK#1825] opened 2021-11-18 21:31 UTC
### Describe the bug

Using `<WindowsPackageType>None<WindowsPackageType>` feature in 1.0, auto-initializes the lookup for the WindowsAppRuntime framework package. However if the framework cannot be found, it results in a generic exception:

Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll

Recommend a better exception or logging a debug output error message.

### Steps to reproduce the bug

On a clean machine that does not have the Windows App SDK installed
1. Start a new C# Winforms app targeting .NET6
2. Add a packagereference to the windows app sdk, and add <WindowsPackageType>None</> to auto-intialize your app code to find the MSIX framework package, eg: 

~~~
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifiers>win10-x86;win10-x64</RuntimeIdentifiers>
    <UseWindowsForms>true</UseWindowsForms>
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0-preview3" />
  </ItemGroup>

</Project>
~~~

3. F5 to run the app, note the bootstrapper initialization will not find the framework and fail with this error:
'WinFormsApp5.exe' (CoreCLR: clrhost): Loaded 'D:\repos\WinFormsApp5\bin\Debug\net5.0-windows10.0.19041.0\Microsoft.WindowsAppRuntime.Bootstrap.Net.dll'. Symbol loading disabled by Include/Exclude setting.
Exception thrown: 'System.DllNotFoundException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll

### Expected behavior

No exception

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

Windows 11 (22000), May 2021 Update (19043), October 2020 Update (19042), May 2020 Update (19041), November 2019 Update (18363), May 2019 Update (18362), October 2018 Update (17763)

### IDE

Visual Studio 2022

**Comment by dotMorten** [comment] 2021-11-18 21:39
This! Better errors that tells us what is wrong is essential for a good developer experience.

**Comment by riverar** [comment] 2021-11-18 21:51
@zaryaf @DrusTheAxe

**Comment by stewienj** [comment] 2021-11-23 00:08
The bootstrapper should also check for the C++ runtime DLLs being available. These missing DLLs were the cause of #1762 .

**Comment by DrusTheAxe** [comment] 2021-11-25 21:54
> The bootstrapper should also check for the C++ runtime DLLs being available. These missing DLLs were the cause of #1762 .

WinAppSDK 1.0 requires the CRT runtime. This is a documented prerequisite. @zaryaf got link?

WinAppSDK 1.1 is moving to the [Hybrid CRT](https://github.com/microsoft/WindowsAppSDK/blob/main/docs/Coding-Guidelines/HybridCRT.md) per https://task.ms/35544838. WinUI is the last remaining component to update. @Scottj1s has an update in progress for 1.1

**Comment by DrusTheAxe** [comment] 2021-11-25 21:56
>However if the framework cannot be found, it results in a generic exception:
>Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll
>Recommend a better exception or logging a debug output error message.

Or both :-)

It's in my queue. Happy holidays

**Comment by smaillet** [comment] 2022-01-17 19:09
@AdamBraden Thanks for reporting this as a really bad error/experience, I couldn't agree more - I've spent several hours trying to get a simple WinU 3 app to build and run unpackaged to no avail but a **LOT** of frustration. 

So What's the solution/workaround to this? I have this error and have no idea what to do about it... (sadly even this bug report leaves out any form of a solution)

**Comment by riverar** [comment] 2022-01-17 22:51
> [Update] Finally figured it out, apparently just adding the VSIX package to VS isn't enough, we also need to run (with admin rights) an additional installer that's only provided as a ZIP file leaving users to guess which one is needed for their systems.)

Did you read the [Windows App SDK deployment guide for unpackaged apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps?WT.mc_id=WD-MVP-5002756#overview) beforehand?

Perhaps whatever error is added should have an _aka.ms_ pointing to these docs.

**Comment by smaillet** [comment] 2022-01-18 16:14
@riverar Yes, I did RTFM, thank you. The docs are a jumbled mess of steps that vaguely reference one another and worse reference two almost identically named things VSIX installer AND an MSIX installer (or a set of them packaged as a ZIP file) there is literally one letter difference between the acronyms for those two things so it is all VERY confusing. Additionally the expectation is that one would NOT Need any sort of MSIX installer involved. I have the VSIX applied and I added the NuGet Package - there is pretty much no precedent to expect one needs anything more. (And I'd call it a serious design flaw that we do need more to support unpackaged apps - XCOPY deployment is the standard of .NET. Packaging should have any impact or the inner loop development of apps before they are even ready for any sort of deployment to anyone but other development team members. One can't even run the code built without the added MSIX stuff installed - that's VERY surprising with any library from NuGet. Bottom line here is that WinUI 3 is **NOT** XCOPY deploy compatible and the docs need to make that crystal clear right up front and the error message(s) should provide more helpful details people can understand that.

**Comment by riverar** [comment] 2022-01-18 20:42
@smaillet I think that's all fair feedback!

To summarize your comment:
* You found the docs confusing (adding @zaryaf)
* You found the packaging-project/single-project templates are confusing (adding @andrewleader for the rest)
* You suspect the lack of xcopy deployment is contributing to confusion given it's a default in the .NET (Core) ecosystem
* WAS/WinUI error messages suck

**Comment by DrusTheAxe** [comment] 2022-01-20 02:40
>You found the docs confusing
+@AdamBraden

**Comment by DrusTheAxe** [comment] 2022-03-14 04:53
1.0.1 and 1.1 include improved logging

**Closed** 2022-04-01 05:17 UTC
Labels: feature, area-DynamicDependencies, servicing-consider-1.0
