### ISSUE TITLE
NavView not crisp hambuger middle not crisp on 100% scale

### ISSUE THREAD

**Issue by crutkas** [microsoft/WindowsAppSDK#3053] opened 2022-10-13 21:17 UTC
### Describe the bug

From https://github.com/microsoft/PowerToys/issues/19463, the hamburger at 100% scaling is blurry

![image](https://user-images.githubusercontent.com/1462282/195712210-d71d5a2e-28c3-4ac7-9b0a-06a9c651e07f.png)

### Steps to reproduce the bug

1. create app with navview
2. have computer at 100 scale dpi
3. see blurriness

### Screenshots

![image](https://user-images.githubusercontent.com/1462282/195712210-d71d5a2e-28c3-4ac7-9b0a-06a9c651e07f.png)

### NuGet package version

1.1.5

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by Jay-o-Way** [comment] 2022-10-13 21:27
> **Note**
> it's not only Win.11 (also on Win.10) and these images are from WinUI 3 Gallery (N.B.)

**Comment by gabbybilka** [comment] 2022-10-17 23:27
Thanks for filing, dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/7048

**Closed by gabbybilka** 2022-10-17 23:27 UTC
