### ISSUE TITLE
Content doesn't fill the entire screen when using FullScreenPresenter at a first time after app start

### ISSUE THREAD

**Issue by aepot** [microsoft/WindowsAppSDK#1853] opened 2021-11-29 17:14 UTC
### Describe the bug

When I execute at a first time
``` C#
_appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
```
There's two white thick borders on the Window at the bottom and the right sides. Bottom one looks like a Taskbar-size and the right one looks like a scrollbar-size.

When I restore Presenter to `Default` and then go Full Screen again, everything seems to be fine. 

### Steps to reproduce the bug

1. Create **Blank App, packaged (WinUI 3 Desktop)**
2. Create a `Button` on non-white-backgrounded `Grid`
3. Fill the `Click` event handler using `AppWindow.SetPresenter` (sample code below)
4. Run: **Unpackaged**, **x64**, **Debug** (other configurations didn't tested)
5. Click the button

**Result**

The app went to full screen mode. Window's content doesn't fill the entire screen.

### Expected behavior

There're no borders. `Window` content fills the full screen.

### Screenshots

Preview image on a full screen, it's clickable. White borders on a white back are invisible (in case you're using a light GitHub theme).

[![image][1]][1]

  [1]: https://user-images.githubusercontent.com/31999345/143908447-4b876788-1423-436b-9862-2f5ed53185db.png

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

October 2020 Update (19042)

### IDE

Visual Studio 2022

### Additional context

Reproducibility: 100%

Sample code, only changes to default template.

MainWindow.xaml
```xaml
<Grid Background="CadetBlue" BorderBrush="Red" BorderThickness="2">
    <Button x:Name="myButton" Click="myButton_Click" HorizontalAlignment="Center">Full Screen</Button>
</Grid>
```
MainWindow.xaml.cs
```C#
public sealed partial class MainWindow : Window
{
    private AppWindow _appWindow;

    public MainWindow()
    {
        this.InitializeComponent();
        _appWindow = GetAppWindowForCurrentWindow();
    }

    private void myButton_Click(object sender, RoutedEventArgs e)
    {
        if (_appWindow.Presenter.Kind == AppWindowPresenterKind.FullScreen)
        {
            _appWindow.SetPresenter(AppWindowPresenterKind.Default);
            myButton.Content = "Full Screen";
        }
        else
        {
            _appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
            myButton.Content = "Exit Full Screen";
        }
    }

    private AppWindow GetAppWindowForCurrentWindow()
    {
        IntPtr hWnd = WindowNative.GetWindowHandle(this);
        WindowId myWndId = Win32Interop.GetWindowIdFromWindow(hWnd);
        return AppWindow.GetFromWindowId(myWndId);
    }
}
```

There's no workaround found yet.

Also my default Windows theme is Light. If i set explicitly add `RequestedTheme = ApplicationTheme.Dark;` in the `App` ctor, the bug stops reproducing.

**Comment by rkarman** [comment] 2021-11-29 18:10
We've filed a bug internally to track this and it's been assigned to the dev team for investigation.

**Comment by sowenzhang** [comment] 2021-12-19 16:06
ah, I had the exact same problem. 

My workaround is running this in `InitializeComponent` 

```
            AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
            AppWindow.SetPresenter(AppWindowPresenterKind.Default);
```

It's a stupid workaround, but I couldn't find another way.

**Comment by riverar** [comment] 2021-12-19 18:58
Sounds like a potential regression introduced by the fix for #1255. cc: @dotmorten

**Comment by rkarman** [comment] 2022-02-03 21:34
Tracked by http://task.ms/37197163

**Comment by BenHarnett** [comment] 2022-02-27 23:45
> ah, I had the exact same problem.
> 
> My workaround is running this after `InitializeComponent`
> 
> ```
>             AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
>             AppWindow.SetPresenter(AppWindowPresenterKind.Default);
> ```
> 
> It's a stupid workaround, but I couldn't find another way.

This doesn't work for me either. My code:

         ```
var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

            // Retrieve the WindowId that corresponds to hWnd.
            Microsoft.UI.WindowId windowId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);

            // Lastly, retrieve the AppWindow for the current (XAML) WinUI 3 window.
            AppWindow appWindow = AppWindow.GetFromWindowId(windowId);

            if (appWindow != null)
            {
                appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
                Task.Delay(250).Wait();
                appWindow.SetPresenter(AppWindowPresenterKind.Default);
                appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
                
                appWindow.Title = "";
            }
```

**Comment by ispysoftware** [comment] 2022-03-18 02:31
This is not fixed in Windows AppSDK 1.1

**Comment by riverar** [comment] 2022-03-18 02:37
1.1 did not release. 1.0.1 did.

**Comment by MarkBrainfire** [comment] 2022-04-21 03:12
I'm experiencing the same problem using 1.1.0 preview 2.
Being able to reliably change the Presenter is a key reason for using the Microsoft.UI.Windowing API so this needs to be fixed.
I'll let you know later if I'm able to come up with a work around.

**Comment by MarkBrainfire** [comment] 2022-04-21 04:37
Ok I found a simple (albeit bizarre) workaround. Everyone confronting this problem knows that it only happens the first time you set the presenter.  So, set a flag, and the first time, surround your call to SetPresenter with a toggle for extending content into the title bar.

            if (isFullScreenFirstTime)
            {
                isFullScreenFirstTime = false;
                WinUI3Window.ExtendsContentIntoTitleBar = true;
                AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
                WinUI3Window.ExtendsContentIntoTitleBar = false;
            }
            else AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);

**Comment by TorstenKannler** [comment] 2022-04-21 08:35
Simple workaround with great effect.
Thanks a lot!

**Comment by MarkBrainfire** [comment] 2022-04-21 15:46
> Simple workaround with great effect. Thanks a lot!

Thanks @TorstenKannler !  One caveat ... this works fine on the primary display.  However, if you are developing for multiple monitors this work around still has issues when attempting to use a FullScreen presenter on a non-primary display.  I'll follow up if I am able to crack this.

**Comment by MarkBrainfire** [comment] 2022-04-21 18:38
This alternative work around will work on both primary and non-primary displays.   It is not as smooth as the work around I suggested above, but the stutter is barely noticeable.  On my machine a delay of 1 ms, along with the plumbing for async / await, is sufficient.

    private async void GoFullScreen()
    {
        if (isFullScreenFirstTime)
        {
            isFullScreenFirstTime = false;
            AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
            await WaitAWhile(1);
            AppWindow.SetPresenter(AppWindowPresenterKind.Default);
            AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
        }
        else AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);

    }
    static async Task WaitAWhile(int ms)
    {
        await Task.Delay(ms);
    }

**Closed** 2022-06-07 19:02 UTC
Labels: bug, area-Windowing

**Comment by riverar** [comment] 2022-06-07 20:36
@rkarman I'd argue this issue is not fixed, as the fullscreen presenter still does not cover taskbar correctly unless applied multiple times. See also https://github.com/microsoft/WindowsAppSDK/issues/2577 .

**Comment by rkarman** [comment] 2022-06-07 21:28
Different root causes for those bugs, this particular one is fixed now, just not when you're maximized and thus hitting #2577. 😃 I see your point, but we track them separately and should close them as they get fixed and serviced.

If we want to track them as a "hey bug 1, 2, and 3 all need to be fixed before the entire feature works end-to-end with no hiccups/gotchas" we should create an item that these all links up to for that purpose, but we'll continue to close the individual bugs as the root cause for them gets fixed and serviced (I assume you don't want us to hold back releasing a fix just because another related issue is not fixed yet).

**Comment by riverar** [comment] 2022-06-07 21:42
@rkarman Sounds great, thanks!
