### ISSUE TITLE
onecoreuap\windows\dwm\legacymarshal\marshal\inputmanagerexports.cpp(97)\marshal.dll!7969BBBE: (caller: 79A18F62) ReturnNt(1) tid(6378) C000000D Exception thrown at 0x7B0789FC (Microsoft.ui.xaml.dll): 0xC0000005: Access violation reading location 0x00000028.

### ISSUE THREAD

**Issue by xperiandri** [microsoft/WindowsAppSDK#739] opened 2021-04-18 12:44 UTC
App throws exception in a loop
`onecoreuap\windows\dwm\legacymarshal\marshal\inputmanagerexports.cpp(97)\marshal.dll!7969BBBE: (caller: 79A18F62) ReturnNt(1) tid(6378) C000000D Exception thrown at 0x7B0789FC (Microsoft.ui.xaml.dll) in Elmish.Uno.Samples.Windows.Desktop.exe: 0xC0000005: Access violation reading location 0x00000028.`

**Steps to reproduce the bug**
1. Clone [Elmish.Uno](https://github.com/xperiandri/Elmish.Uno/)
2. Check-out [uno_winui](https://github.com/xperiandri/Elmish.Uno/tree/uno_winui) branch
3. Open Elmish.Uno.sln
4. Start **Samples.Windows.Package**

See exception

**Expected behavior**
Application runs without the exception

**Version Info**
|   |  |
| :--- | :--- |
| Edition | Windows 10 Pro |
| Version | 20H2 |
| Installed on | 27.‎11.‎2020 |
| OS build | 19042.928 |
| Serial number | 013396683853 |
| Experience | Windows Feature Experience Pack 120.2212.551.0 |

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
In F# projects I reference
```XML
<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.5" Condition="$(TargetFramework.StartsWith('net5.0-windows10'))" />
```
and work around missing targets with
``` XML
<Target Name="XamlPreCompile" Condition="$(TargetFramework.StartsWith('net5.0-windows10'))" />
```

**Comment by andrewleader** [comment] 2021-04-19 21:11
Thanks for reporting this, I'm working on finding the right owner to investigate this issue!

**Comment by riverar** [comment] 2021-04-19 21:27
Would greatly help if a smaller repro is provided. But a good starting point is observing that carving out MainWindow.xaml resolves the crash. Perhaps mux:Frame related issue?

**Comment by xperiandri** [comment] 2021-04-19 21:28
You can remove all the projects except Windows Desktop and Shared

**Comment by xperiandri** [comment] 2021-04-19 21:31
Do you mean `MainPage.xaml`?

**Comment by riverar** [comment] 2021-04-19 21:33
@xperiandri Oops, yep. That one. Edited.

**Comment by riverar** [comment] 2021-04-19 21:35
@xperiandri I deleted everything, leaving an empty `<Grid>` behind. Can you ship with that workaround? 😂 (Kidding.) Was just slowly trying to narrow a root cause down.

**Comment by andrewleader** [comment] 2021-04-22 21:07
Note to team, internal bug ID is 32619102.

**Comment by xperiandri** [comment] 2021-04-22 21:08
Thanks. Will you post here when resolved?

**Comment by andrewleader** [comment] 2021-04-22 21:10
Yes! If you don't hear a response in a month though, feel free to ping and check in... it's always possible we might forget to post back when resolved, but that is not our intent.

**Comment by kevinguo305** [comment] 2022-03-18 19:29
Hi Andrii,

Thanks for your patience. We've taken a look into this bug and were not able to reproduce. Given the version updates of WinAppSDK since this bug was opened, this bug may have been resolved on its own. I'm going to close this issue, but if you're still experiencing issues, please reopen/reach out!

**Closed by kevinguo305** 2022-03-18 19:29 UTC
Labels: bug

**Comment by xperiandri** [comment] 2022-03-18 19:46
Yes, I confirm that it is resolved. Elmish.Uno runs perfectly now
