### ISSUE TITLE
Regression: Can't install 1.1.3 Package in GitHub actions for MSTest projects (1.0.3 is fine)

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WindowsAppSDK#2768] opened 2022-07-22 17:52 UTC
### Describe the bug

We're trying to update our Windows App SDK version in our project here: https://github.com/CommunityToolkit/Labs-Windows/pull/183

This is still failing to install in our GitHub action CI when trying to run our tests with MSTest with the following message:

```
Installing missing frameworks...
DEP0800: The required framework "C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe from:  (Microsoft.WindowsAppRuntime.1.1.msix)  failed with error 0x8000000B. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
	DeploymentSucceeded = False
	DeploymentError = Err_Deploy_SDKInstall
	DeploymentUserError = False
	DeploymentHRESULT = 2147958009
	HasSharedCode = False
	SDKFileName = 
Deleting file "vs.appxrecipe" from layout...
```

This seems like it's still a problem related to changes which broke 1.0.3 in #2631.

Our CI (and VS) have no issues when running with 1.0.3.

This is blocking us from updating to 1.1.x still which we need for other fixes (though still trying to identify if there are other blocking issues related to MSTest but can't validate what's working in our CI first because of these deployment issues since 1.1.1).

### Steps to reproduce the bug

See https://github.com/CommunityToolkit/Labs-Windows/runs/7460607269?check_suite_focus=true

1. Create MSTest project for Windows App SDK
2. Create [GitHub workflow](https://github.com/CommunityToolkit/Labs-Windows/blob/main/.github/workflows/build.yml) to run `windows-latest` with a step to execute tests after building them in release mode:

```yml
  - name: Run experiment tests against WinAppSDK
    run:  vstest.console.exe ./tests/**/ProjectName.Tests.WinAppSdk.build.appxrecipe /Framework:FrameworkUap10 /logger:"trx;LogFileName=WinAppSdk.trx"
```

See failure to install package.

### Expected behavior

Package installs and tests run.

### Screenshots

![image](https://user-images.githubusercontent.com/24302614/180495024-6947b764-20b0-43a6-9b8e-c990ed71141f.png)

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

Related to Regression #2631 (fixed for main build, but still failing for mstest - raising this new issue to track specifically [as haven't gotten traction replying to closed issue there](https://github.com/microsoft/WindowsAppSDK/issues/2631#issuecomment-1175456903))

Also see #2706

**Comment by DrusTheAxe** [comment] 2022-08-01 18:43
>Installing missing frameworks...
DEP0800: The required framework "C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe from:  (Microsoft.WindowsAppRuntime.1.1.msix)  failed with error **0x8000000B**

I suspect this is a dupe of [DEP0800 error when trying to deploy MAUI app on windows platform #2741](https://github.com/microsoft/WindowsAppSDK/issues/2741#)

>Error DEP0800: The required framework "C:\Users\ltemimi.nuget\packages\microsoft.windowsappsdk\1.1.1\buildTransitive..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1001.524.1918.0_x64__8wekyb3d8bbwe from: (Microsoft.WindowsAppRuntime.1.1.msix) failed with error ***0x8000000B***

0x8000000B = E_BOUNDS ?

@sachintaMSFT ?

@michael-hawker Does this repro with 1.1.3?

**Comment by michael-hawker** [comment] 2022-08-23 00:31
@DrusTheAxe sorry missed this notification before (I was out for a week); it did repo on 1.1.3, and I just tried with 1.1.4 as well, same issue 😥:
```
Copying file "D:\a\Labs-Windows\Labs-Windows\labs\CiTestExp\tests\CiTestExp.Tests.WinAppSdk\bin\x64\Release\net6.0-windows10.0.19041.0\AppxManifest.xml" to layout "AppxManifest.xml"...
Checking whether required frameworks are installed...
Framework: Microsoft.WindowsAppRuntime.1.1/X86. Skipping installation because framework package architecture does not match target architecture X64 and app package architecture X64.
Framework: Microsoft.WindowsAppRuntime.1.1/X86. Skipping installation because framework package architecture does not match target architecture X64 and app package architecture X64.
Framework: Microsoft.WindowsAppRuntime.1.1/X64, app package version 1004.584.2120.0 is not currently installed.
Framework: Microsoft.WindowsAppRuntime.1.1/ARM64. Skipping installation because framework package architecture does not match target architecture X64 and app package architecture X64.
Installing missing frameworks...
DEP0800: The required framework "C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.1.4\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80073CF9] Deployment Add operation with target volume C: on Package Microsoft.WindowsAppRuntime.1.1_1004.584.2120.0_x64__8wekyb3d8bbwe from:  (Microsoft.WindowsAppRuntime.1.1.msix)  failed with error 0x8000000B. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues.
```

See our CI run here: https://github.com/CommunityToolkit/Labs-Windows/runs/7963041945?check_suite_focus=true (works fine with 1.0.3, but not 1.1.x.) Our PR is here: https://github.com/CommunityToolkit/Labs-Windows/pull/183

**Comment by sachintaMSFT** [comment] 2022-08-29 23:14
It is a duplicate of the issue# https://github.com/microsoft/WindowsAppSDK/issues/2829. Latest status of the root cause and the fix is being shared there.

**Closed by sachintaMSFT** 2022-08-29 23:14 UTC
Labels: bug, duplicate, area-App deployment, area-Installer
