### ISSUE TITLE
StorageItemContentProperties.GetImagePropertiesAsync causes an access violation when the same code works fine in the UWP version

### ISSUE THREAD

**Issue by stevewhims** [microsoft/WindowsAppSDK#1141] opened 2021-07-29 00:48 UTC
**Describe the bug**
**StorageItemContentProperties.GetImagePropertiesAsync** causes an access violation when the same code works fine in the UWP version.

**Steps to reproduce the bug**
Clone the [PhotoEditor1141](https://github.com/stevewhims/PhotoEditor1141) repro project, open the solution in Visual Studio, change the configuration to something other than arm64, build and run. You should see thumbnails for the files in your Pictures folder. Now find the MainWindow::LoadImageInfoAsync method, and uncomment that first line. Hit F5 to debug, and you'll get an access violation. You can set a breakpoint and demonstrate that the app does get beyond the uncommented line, so I don't know what's causing the AV.

**Expected behavior**
No AV, just like with the original UWP version of this app.

**Version Info**
0.8.1; running on Windows 10 or Windows 11 Preview.

NuGet package version: 
0.8.1 stable.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Vibranium            |    |
| All versions of Win11 preview |    |

This is an attempted port of the [UWP Photo Editor sample app](https://docs.microsoft.com/samples/microsoft/windows-appsample-photo-editor/photo-editor-cwinrt-sample-application/). See [A Windows App SDK 0.8.1 port of the UWP Photo Editor sample app](https://github.com/stevewhims/PhotoEditor).

NOTE: the issue repros with the Pictures and Videos known folders, but not with the Object3D known folder.

**Comment by riverar** [comment] 2021-07-29 01:22
I can't reproduce the AV on 19043.1110, but I did change the code to search within the Objects3D known folder as opposed to Pictures (to avoid a deep recursive search through my large photos hierarchy).

Can you still repro if you change the library you're reading from?

**Comment by stevewhims** [comment] 2021-07-29 21:42
> I can't reproduce the AV on 19043.1110, but I did change the code to search within the Objects3D known folder as opposed to Pictures (to avoid a deep recursive search through my large photos hierarchy).
> 
> Can you still repro if you change the library you're reading from?

Hi, @riverar. If I narrow down the contents of the Pictures known folder to just two images (no folders), then I can still repro the issue with the repro project. The repro project is a port of a UWP app that specifically uses that folder.

However, good idea to investigate whether that's the only folder affected by this. So I tried out the Videos known folder and got the same issue. I then tried the Object3D known folder and that time I didn't get the AV.

Hopefully that info helps a bit in resolving the issue.

Many thanks!
Steve

**Comment by GhostsAndMoreGhosts** [comment] 2021-07-31 08:48
**Problem (1)** :

 Engineers should fix the crippled supppper slow _Single Threaded_ Storage Broker (RuntumeBroker.exe).

**Problem (2)** :

 Storage brokers are completely useless gatekeepers for medium or high IL process. exactly what happening here - redirecting storageitems through storage broker even though it's a medium IL process.  

_Engineers should also fix  implementation of windows.storage.*  apis when used from medium IL/high IL process that the Storage broker should not be invoked at all  **even if the app is "packaged"**._   

 linking : #661

**Comment by btueffers** [comment] 2021-08-02 19:19
We're now tracking this issue internally and will be closing the issue on GitHub.

**Closed by btueffers** 2021-08-02 19:19 UTC

**Comment by smaillet-ms** [comment] 2021-08-04 17:58
I think that closing this here is premature. This doesn't appear to be an OS platform issue. As stated in the comments here it works correctly as a normal UWP app. Additionally, it states that the app is able to step over the function and the crash occurs later. Unfortunately it is deep in the WINUI code base and SourceLink is apparently not available/supported for that. (I'm also unfamailiar with that code base anyway). The full stack trace of the actual crash is:
>	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::CacheManager::InitCollectionsCache() Line 775	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::CacheManager::GetItem(int indexInItemCollection, IInspectable * * ppItem) Line 856	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::GenerateContainerAtIndexImpl(int indexInItemCollection, ABI::Microsoft::UI::Xaml::IUIElement * * ppReturnValue) Line 164	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanelGenerated::GenerateContainerAtIndex(int index, ABI::Microsoft::UI::Xaml::IUIElement * * ppReturnValue) Line 565	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::GenerateAnchorsForWindow(const ABI::Windows::Foundation::Rect & windowToFill, const ABI::Microsoft::UI::Xaml::Controls::EstimationReference * headerReference, const ABI::Microsoft::UI::Xaml::Controls::EstimationReference * containerReference) Line 1324	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::DetectAndHandleDisconnectedView() Line 1165	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::DetermineWindowAndAnchors() Line 2305	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::RunVirtualization() Line 567	C++
 	Microsoft.ui.xaml.dll!DirectUI::ModernCollectionBasePanel::MeasureOverride(ABI::Windows::Foundation::Size availableSize, ABI::Windows::Foundation::Size * pReturnValue) Line 476	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::FrameworkElementGenerated::MeasureOverrideProtected(ABI::Windows::Foundation::Size) Line 1030	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::MeasureOverrideFromCore(CFrameworkElement * nativeTarget, float inWidth, float inHeight, float * outWidth, float * outHeight) Line 246	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CFxCallbacks::FrameworkElement_MeasureOverride(CFrameworkElement *) Line 737	C++
 	Microsoft.ui.xaml.dll!CFrameworkElement::MeasureCore(XSIZEF availableSize, XSIZEF & desiredSize) Line 1573	C++
 	Microsoft.ui.xaml.dll!CUIElement::MeasureInternal(XSIZEF availableSize) Line 3975	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3837	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CLayoutManager::UpdateLayout(unsigned int controlWidth, unsigned int controlHeight) Line 278	C++
 	Microsoft.ui.xaml.dll!CCoreServices::NWDrawTree(HWWalk * pHWWalk, CWindowRenderTarget * pRenderTarget, VisualTree * pVisualTree, unsigned int forceRedraw, XRECT_WH * prcDirtyRect) Line 6112	C++
 	Microsoft.ui.xaml.dll!CCoreServices::NWDrawMainTree(CWindowRenderTarget * pIRenderTarget, bool fForceRedraw, XRECT_WH * prcDirtyRect) Line 5916	C++
 	Microsoft.ui.xaml.dll!CWindowRenderTarget::Draw(CCoreServices * fForceRedraw, unsigned int prcDirtyRect, XRECT_WH *) Line 134	C++
 	Microsoft.ui.xaml.dll!CXcpBrowserHost::OnTick() Line 342	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::Tick() Line 1231	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::OnReentrancyProtectedWindowMessage(HWND__ * msg, unsigned int lParam, unsigned __int64) Line 834	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ *) Line 706	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 664	C++
 	Microsoft.ui.xaml.dll!CDeferredInvoke::DispatchQueuedMessage(bool * dispatchedWork, bool * hasMoreWork) Line 190	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CXcpDispatcher::MessageTimerCallback() Line 1312	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CXcpDispatcher::MessageTimerCallbackStatic(void * myUserData) Line 1304	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CXcpDispatcher::Init::__l75::<lambda_3e1276e0d827edcdd41a81b89b1d2778>::operator()(ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *) Line 379	C++
 	Microsoft.ui.xaml.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl ABI::Windows::Foundation::ITypedEventHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Microsoft::UI::Dispatching::DispatcherQueueTimer *,ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *>,IInspectable *>::*)(ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *,IInspectable *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,ABI::Windows::Foundation::ITypedEventHandler<ABI::Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::FtmBase>,<lambda_3e1276e0d827edcdd41a81b89b1d2778> &,1,ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer *,IInspectable *>::Invoke(ABI::Microsoft::UI::Dispatching::IDispatcherQueueTimer * <args_0>, IInspectable * <args_1>) Line 245	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::WRL::Details::CreateAgileHelper::__l2::<lambda_82cf8073f4f042d1a68771c460cb9f49>::operator()(Microsoft::UI::Dispatching::IDispatcherQueueTimer * &&) Line 440	C++
 	CoreMessagingXP.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl Windows::Foundation::ITypedEventHandler_impl<Windows::Foundation::Internal::AggregateType<Microsoft::UI::Dispatching::DispatcherQueueTimer *,Microsoft::UI::Dispatching::IDispatcherQueueTimer *>,IInspectable *>::*)(Microsoft::UI::Dispatching::IDispatcherQueueTimer *,IInspectable *)>::DelegateInvokeHelper<Microsoft::WRL::Implements<Microsoft::WRL::RuntimeClassFlags<2>,Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::FtmBase>,<lambda_82cf8073f4f042d1a68771c460cb9f49>,-1,Microsoft::UI::Dispatching::IDispatcherQueueTimer *,IInspectable *>::Invoke(Microsoft::UI::Dispatching::IDispatcherQueueTimer * <args_0>, IInspectable * <args_1>) Line 354	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::InvokeModeOptions<-2>>::InvokeAll::__l2::<lambda_1e854da9c9ccd42f6138c3b007a32877>::operator()(Microsoft::WRL::ComPtr<IUnknown> &) Line 964	C++
 	CoreMessagingXP.dll!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<<lambda_1e854da9c9ccd42f6138c3b007a32877>,Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>>(Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::InvokeModeOptions<-2>>::InvokeAll::__l2::<lambda_1e854da9c9ccd42f6138c3b007a32877> invokeOne, Microsoft::WRL::Details::EventTargetArray * targetArray, Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::InvokeModeOptions<-2>> * pEvent) Line 121	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::InvokeModeOptions<-2>>::DoInvoke(Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::InvokeModeOptions<-2>>::InvokeAll::__l2::<lambda_1e854da9c9ccd42f6138c3b007a32877>) Line 954	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Microsoft::UI::Dispatching::DispatcherQueueTimer *,IInspectable *>,Microsoft::WRL::InvokeModeOptions<-2>>::InvokeAll(Microsoft::UI::Dispatching::DispatcherQueueTimer * <args_0>, void * <args_1>) Line 964	C++
 	CoreMessagingXP.dll!Microsoft::UI::Dispatching::DispatcherQueueTimer::TimerCallback(void * userInfo) Line 358	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutHandler::ImportAdapter$::__l2::<lambda_654db17c35df07198786f0867aa10de6>::operator()() Line 22	C++
 	CoreMessagingXP.dll!CFlat::SehSafe::Execute<<lambda_654db17c35df07198786f0867aa10de6>>(void * hostData, Microsoft::CoreUI::Dispatch::TimeoutHandler::ImportAdapter$::__l2::<lambda_654db17c35df07198786f0867aa10de6> && body) Line 11	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutHandler::ImportAdapter$(CFlat::Box$1<CFlat::FunctionPointerAndUserData$1<long (__cdecl*)(void *)>> * func$) Line 24	C++
 	[Inline Frame] CoreMessagingXP.dll!CFlat::DelegateImpl<Microsoft::CoreUI::Dispatch::TimeoutHandler,0,void __cdecl(void),long __cdecl(void *),0>::Invoke() Line 337	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Timeout::CallHandlerWithActivationContext() Line 32	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::CoreUI::Support::ActivationContext::CallbackWithActivationContext(Microsoft::CoreUI::Dispatch::Timeout *) Line 212	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Timeout::CallHandler() Line 27	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::TimeoutManager::Callback_OnDispatch() Line 305	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem() Line 778	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(Microsoft::CoreUI::Dispatch::RunnablePriorityMask) Line 406	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(Microsoft::CoreUI::Dispatch::RunMode mode) Line 420	C++
 	[Inline Frame] CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessagingEventLoopBridge::Callback_OnSystemDispatch(Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority) Line 632	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::Callback_OnGroupDispatch(Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority priority, CFlat::Ref<System::IntPtr> sessionExportAdapter) Line 159	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::NoContext_GroupDispatchHandler(Microsoft::CoreUI::Dispatch::SystemCoreMessaging$GroupPriority priority, void * context) Line 63	C++
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::SystemCoreMessaging::NoContext_HighPriorityDispatchHandler(void * context) Line 121	C++
 	[Inline Frame] CoreMessaging.dll!Microsoft::CoreUI::DispatchGroupHandler::ImportAdapter$::__l2::<lambda_72be19825923cb708ba996fdf6b354f1>::operator()() Line 68	C++
 	CoreMessaging.dll!CFlat::SehSafe::Execute<<lambda_72be19825923cb708ba996fdf6b354f1>>(void * hostData, Microsoft::CoreUI::DispatchGroupHandler::ImportAdapter$::__l2::<lambda_72be19825923cb708ba996fdf6b354f1> && body) Line 11	C++
 	CoreMessaging.dll!Microsoft::CoreUI::DispatchGroupHandler::ImportAdapter$(CFlat::Box$1<CFlat::FunctionPointerAndUserData$1<long (__cdecl*)(void *)>> * func$) Line 70	C++
 	CoreMessaging.dll!Microsoft::CoreUI::BatchAgnosticDispatchGroup::Callback_OnDispatchCore() Line 40	C++
 	[Inline Frame] CoreMessaging.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem() Line 778	C++
 	[Inline Frame] CoreMessaging.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(Microsoft::CoreUI::Dispatch::RunnablePriorityMask) Line 406	C++
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(Microsoft::CoreUI::Dispatch::RunMode mode) Line 420	C++
 	[Inline Frame] CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::DrainCoreMessagingQueue(Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority) Line 488	C++
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch(bool handlingCompletion, Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority priority, CFlat::Ref<System::IntPtr> sessionExportAdapter) Line 706	C++
 	[Inline Frame] CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw(Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority) Line 634	C++
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::DoWork(Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority priority, bool handlingCompletion) Line 198	C++
 	CoreMessaging.dll!Microsoft::CoreUI::Dispatch::UserAdapter::WindowProc(HWND__ * hwnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 130	C++
 	user32.dll!UserCallWinProcCheckWow(_ACTIVATION_CONTEXT * pActCtx, __int64(*)(tagWND *, unsigned int, unsigned __int64, __int64) pfn, HWND__ * hwnd, _WM_VALUE msg, unsigned __int64 wParam, __int64 lParam, void * fEnableLiteHooks, int) Line 282	C++
 	user32.dll!DispatchClientMessage(tagWND * pwnd, unsigned int message, unsigned __int64 wParam, __int64 lParam, unsigned __int64 pfn) Line 3435	C++
 	user32.dll!__fnDWORD(_FNDWORDMSG * pmsg) Line 1214	C++
 	ntdll.dll!KiUserCallbackDispatch() Line 607	Unknown
 	win32u.dll!ZwUserGetMessage() Line 189	Unknown
 	user32.dll!GetMessageW(tagMSG * pmsg, HWND__ * hwnd, unsigned int wMsgFilterMin, unsigned int wMsgFilterMax) Line 538	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::RunDesktopWindowMessageLoop() Line 1164	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::StartDesktop() Line 209	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::StartImpl(ABI::Microsoft::UI::Xaml::IApplicationInitializationCallback *) Line 163	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::Start(ABI::Microsoft::UI::Xaml::IApplicationInitializationCallback * pCallback) Line 756	C++
 	PhotoEditor.exe!winrt::impl::consume_Microsoft_UI_Xaml_IApplicationStatics<winrt::Microsoft::UI::Xaml::IApplicationStatics>::Start(const winrt::Microsoft::UI::Xaml::ApplicationInitializationCallback & callback) Line 157	C++
 	PhotoEditor.exe!winrt::Microsoft::UI::Xaml::Application::Start::__l2::<lambda>(const winrt::Microsoft::UI::Xaml::IApplicationStatics & f) Line 12146	C++
 	PhotoEditor.exe!winrt::impl::factory_cache_entry<winrt::Microsoft::UI::Xaml::Application,winrt::Microsoft::UI::Xaml::IApplicationStatics>::call<void <lambda>(const winrt::Microsoft::UI::Xaml::IApplicationStatics &) &>(winrt::Microsoft::UI::Xaml::Application::Start::__l2::void <lambda>(const winrt::Microsoft::UI::Xaml::IApplicationStatics &) & callback) Line 6286	C++
 	PhotoEditor.exe!winrt::impl::call_factory<winrt::Microsoft::UI::Xaml::Application,winrt::Microsoft::UI::Xaml::IApplicationStatics,void <lambda>(const winrt::Microsoft::UI::Xaml::IApplicationStatics &)>(winrt::Microsoft::UI::Xaml::Application::Start::__l2::void <lambda>(const winrt::Microsoft::UI::Xaml::IApplicationStatics &) && callback) Line 6309	C++
 	PhotoEditor.exe!winrt::Microsoft::UI::Xaml::Application::Start(const winrt::Microsoft::UI::Xaml::ApplicationInitializationCallback & callback) Line 12147	C++
 	PhotoEditor.exe!wWinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, wchar_t * __formal, int __formal) Line 54	C++
 	PhotoEditor.exe!invoke_main() Line 123	C++
 	PhotoEditor.exe!__scrt_common_main_seh() Line 288	C++
 	PhotoEditor.exe!__scrt_common_main() Line 331	C++
 	PhotoEditor.exe!wWinMainCRTStartup(void * __formal) Line 17	C++
 	kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long(*)(void *) StartAddress, void * Argument) Line 75	C
 	ntdll.dll!RtlUserThreadStart(long(*)(void *) StartAddress, void * Argument) Line 1152	C

**Comment by AdamBraden** [comment] 2021-08-31 03:52
@Scottj1s or @manodasanW - does this look related to https://github.com/microsoft/CsWinRT/issues/635 ?
