### ISSUE TITLE
Support extended title bar for non-XAML Windows Runtime apps

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#408] opened 2021-02-01 05:00 UTC
# Proposal: Support extended title bar for non-XAML Windows Runtime apps
Today only XAML apps can extend their content to the title bar and apps that don't use XAML can't.

## Summary
Extend title bar requires a XAML content to be displayed and Window.Current.SetTitleBar is a XAML API. However please provide a lower-level API in CoreWindow for doing the same in non-XAML apps. Maybe it could accept a Windows.Foundation.Rect and set that as the drag region.

## Rationale

* Non XAML developers should be able to get the same features

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to extend the title bar in non-XAML apps eg: DirectX games | Must |

**Comment by mdtauk** [comment] 2021-02-01 05:12
CoreWindow is a UWP only construct.  WinUI 3 introduces the Window, and this supports extending into the titlebar area.

Not sure if this can be made to work with GDI apps, which can override the drawing of the titlebar already (though not easily) and WPF which can custom draw it's windows (not as simply as WinUI)

**Comment by Jaiganeshkumaran** [comment] 2021-02-01 05:14
> CoreWindow is a UWP only construct. WinUI 3 introduces the Window, and this supports extending into the titlebar area.
> 
> Not sure if this can be made to work with GDI apps, which can override the drawing of the titlebar already (though not easily) and WPF which can custom draw it's windows (not as simply as WinUI)

True but I'm taking about UWP apps not using XAML at all. Eg: DirectX games that render the screen on their own without using any XAML stuff.

**Comment by mdtauk** [comment] 2021-02-01 05:17
> > CoreWindow is a UWP only construct. WinUI 3 introduces the Window, and this supports extending into the titlebar area.
> > Not sure if this can be made to work with GDI apps, which can override the drawing of the titlebar already (though not easily) and WPF which can custom draw it's windows (not as simply as WinUI)
> 
> True but I'm taking about UWP apps not using XAML at all. Eg: DirectX games that render the screen on their own without using any XAML stuff.

Windows Runtime includes WinUI 3 desktop I guess now.

**Comment by Jaiganeshkumaran** [comment] 2021-02-01 05:18
@mdtauk However there are also non-WinUI 3 or OS XAML apps using low level graphics and they aren't able to extend title bar under CoreWindow

**Comment by mdtauk** [comment] 2021-02-01 05:20
I did not know that.  I know there is a different behaviour with Full Screen apps, as well as no titlebars on Xbox

**Comment by Jaiganeshkumaran** [comment] 2021-02-01 05:23
From the docs:
``
Simple color customization is available to Windows apps using XAML, DirectX, and HTML. Full customization is available only to Windows apps using XAML.
``

**Comment by andrewleader** [comment] 2021-02-01 20:16
@rkarman can you look at this?

**Comment by rkarman** [comment] 2021-02-19 23:06
Somehow missed this assignment... Sorry about that.
This is a duplicate of, or at least related to issue #49 , since bringing that API to Reunion would be framework agnostic and thus work for windows with any type of content in them.
Assigning to @mevey who is working on the Titlebar feature area.

**Comment by AzAgarampur** [comment] 2021-02-24 22:31
> Today only XAML apps can extend their content to the title bar and apps that don't use XAML can't.

Win32, Winforms, WPF, etc can handle `WM_NCCALCSIZE` to remove the standard window frame then use `DwmExtendFrameIntoClientArea` to extend the window frame into the client area, allowing you to draw on it. This is basically what `ApplicationFrameHost.exe` does. (Although I'm not sure why it still extends the frame using `DwmExtendFrameIntoClientArea`, as it will be covered by the UWP drawn content anyways...)

**Comment by Jaiganeshkumaran** [comment] 2021-02-25 02:08
> > Today only XAML apps can extend their content to the title bar and apps that don't use XAML can't.
> 
> Win32, Winforms, WPF, etc can handle `WM_NCCALCSIZE` to remove the standard window frame then use `DwmExtendFrameIntoClientArea` to extend the window frame into the client area, allowing you to draw on it. This is basically what `ApplicationFrameHost.exe` does. (Although I'm not sure why it still extends the frame using `DwmExtendFrameIntoClientArea`, as it will be covered by the UWP drawn content anyways...)

You don't get it. I'm not taking about desktop Win32 apps. I'm taking about UWP apps that don't use the XAML framework for rendering (eg: DirectX, HTML, custom UI with composition)

**Comment by mevey** [comment] 2021-02-25 19:33
We are working on a proposal and roadmap to enable non-XAML apps to customize the titlebar area. We will share this with you in the coming weeks for feedback.

**Comment by martibravo** [comment] 2021-11-02 10:31
If you are using the new Windowing APIs you can extend content to the titlebar and set custom Drag Areas defined by an array of RectInt32 values.

Just use `AppWindowTitlebar.ExtendsContentIntoTitlebar = true;` and set your drag rectangles with `AppWindowTitlebar.SetDragRectangles = new RectInt32[]{...};`

**Comment by rkarman** [comment] 2022-02-01 18:41
The AppWindow APIs for extending window content into the TitleBar is accessible to non-WinUI apps as well as pointed out by martibravo above, thus I am closing this issue.

If the limitation that ExtendsContentIntoTitleBar is only available on Win11 and later is an issue, please open a request for downlevel support separately.

**Closed by rkarman** 2022-02-01 18:41 UTC
Labels: feature proposal, area-Windowing
