### ISSUE TITLE
The ui not change when i edit the template

### ISSUE THREAD

**Issue by daniDevKr** [microsoft/WindowsAppSDK#3526] opened 2023-03-22 17:02 UTC
### Describe the bug

I have a custom control with a collection-type field.
When i run the app in debug mode and try to add items to the `Fields` collection, the ui not change and  the XAML editor show the error:

> Error XHR0015 Failed to add HelloItem to ObservableCollection`1. Unable to find element.

### Steps to reproduce the bug

1. I start the debug;
2. I edit the template adding new `TextBlock` to the fields collection.

### Expected behavior

I expect that the ui show me the new items.

### Screenshots

![image](https://user-images.githubusercontent.com/29796059/226978243-cb11f0ca-b2f9-4b64-9ce8-fc8b7932ad76.png)

### NuGet package version

Windows App SDK 1.2.5: 1.2.230313.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

The source code [Link](https://github.com/jhonToni/WinuiCustomControl1)

**Comment by MuyuanMS** [comment] 2024-11-13 09:09
Unfortunately, I was not able to reproduce the issue (Or are you trying to have the running App updating as you edit?)
Given this was reported long ago in 1.2, I will close the issue for now unless it still exists in 1.6.

**Closed by MuyuanMS** 2024-11-13 09:09 UTC
Labels: bug, area-DeveloperTools
