### ISSUE TITLE
WebView/WebView2 memory leak

### ISSUE THREAD

**Issue by tj-jyk** [microsoft/WindowsAppSDK#1158] opened 2021-08-02 10:14 UTC
**Describe the bug**

WebView2 (and old WebView) exhibits a memory leak when creating and deleting the control in a loop. In my application, the user can change the content every (x) seconds and with a WebView/WebView2 control the user will get a memory leak. 

**Steps to reproduce the bug**

[GitHub repo](https://github.com/tj-jyk/WebView_WebView_memory_leak)

1. Start a loop / a timer `var timer = new DispatcherTimer
			{
				Interval = TimeSpan.FromSeconds(1)
			};
			timer.Tick += Timer_Tick;
			timer.Start();`
2.  In a loop logic find the old WebView/WebView2 control in a DOM `VisualTreeHelper.GetChildrenCount(parent);  ..... VisualTreeHelper.GetChild(parent, i) ...`)
3.  Remove the old WebView from the DOM `(VisualTreeHelper.DisconnectChildrenRecursive(rootGrid);)`
4.  For a WebView call `webViewToRemove.Navigate(new Uri("about:blank"));` For a WebView2:  `webViewToRemove.Close(); `
5. Add a new WebView/WebView2 control to the DOM `rootGrid.Children.Add(newWebView);`
6. Application crashes after 15 minutes.

**Screenshots**

![image](https://user-images.githubusercontent.com/29145276/127843163-d17ed5a5-18a8-4c60-bd2d-e25d30f7a497.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19042)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by dragonDScript** [comment] 2021-08-02 10:29
I can reproduce, it crashes after 20 minutes.

**Comment by btueffers** [comment] 2021-08-06 20:40
Hi @tj-jyk, we're monitoring the issue that was opened in the WinUI repo. If the issue isn't able to be resolved with their advice we recommend that you open an Issue in [the WebView2 repo](https://github.com/MicrosoftEdge/WebView2Feedback/issues)

**Comment by btueffers** [comment] 2021-08-16 19:33
Hi @tj-jyk, thank you for opening the issue under the MicrosoftEdge organization.

**Closed by btueffers** 2021-08-16 19:33 UTC
