### ISSUE TITLE
On-Screen keyboard not showing

### ISSUE THREAD

**Issue by byrialsen** [microsoft/WindowsAppSDK#2151] opened 2022-02-24 16:25 UTC
### Describe the bug

I have created a windowsappsdk / MSIX app and I have serious problems with on-screen keyboard running on a new Surface Go 2 Tablet with 100% updated Windows 10. 

Scenario 1 
Running in tablet mode when I touch/hit a textbox the onscreen keyboard will not appear automatically. If I manually show the taskbar, hit the keyboard icon in the system tray the on-screen keyboard shows but hides again immediately.

Scenario 2
Running in normal mode the same thing happens except that when the on-screen keyboard is activated from system tray icon, the app/textbox looses focus and when focus is set back to my app/textbox by touching the app, then the on-screen keyboard will disappears.

Has anyone experienced similar. 

### Steps to reproduce the bug

No additional info

### Expected behavior

Textbox focus with touch should show the on-screen keyboard.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022

**Comment by byrialsen** [comment] 2022-02-28 21:13
Hi.

I really hope someone has an idea what the problem. Is is really correct that touch input on-screen keyboard is not working 🙃🙃

I have added a simple repo here: [https://github.com/byrialsen/OnScreenKeyboard](https://github.com/byrialsen/OnScreenKeyboard)

**Comment by riverar** [comment] 2022-02-28 21:28
Dupe of microsoft/microsoft-ui-xaml#6291, known broken I'm afraid.

**Comment by byrialsen** [comment] 2022-02-28 21:34
@riverar. Thanks for the feedback but I am quite sure it was working for me with WindowsAppSdk 1.0.0 some time ago. But now it seems broken like described.
Hmm not good as my customer specific app should go in production in a few days🙈.

**Comment by MuyuanMS** [comment] 2024-11-01 05:33
Duplicate issue https://github.com/microsoft/microsoft-ui-xaml/issues/6291 has been fixed, closing this issue as well

**Closed by MuyuanMS** 2024-11-01 05:33 UTC
