### ISSUE TITLE
please change nuget package version scheme so we can easily know what we're using

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/WindowsAppSDK#4682] opened 2024-08-26 20:53 UTC
### Describe the bug

just going to ask again to please change the version scheme of the Nuget packages to one that we can all understand. the current date format for the last part of the nuget package makes us all sad. today i have to open Nuget Package explorer and count the number of packages just to double-check / confirm the package number we're using. 

i promise if you do this now for 1.6 and 1.5 they will still follow semver rules and we'll all be happy

if this is actually changing for 1.6 then thank you and please disregard 🙏 

### Steps to reproduce the bug

1. use windows app sdk

### Expected behavior

packages should be in the format `1.6.0`, `1.6.1`, `1.6.2`

### NuGet package version

Windows App SDK 1.6 Preview 2: 1.6.240821007-preview2

**Comment by codendone** [comment] 2024-08-27 02:36
Closing as duplicate of #4212.

**Closed by codendone** 2024-08-27 02:36 UTC
Labels: needs-triage
